# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/lab1/mul_lab1/mul_lab1.srcs/sources_1/bd/design_1/ip/design_1_mul_0_0/design_1_mul_0_0.xci
# IP: The module: 'design_1_mul_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/lab1/mul_lab1/mul_lab1.gen/sources_1/bd/design_1/ip/design_1_mul_0_0/constraints/mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mul_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/lab1/mul_lab1/mul_lab1.srcs/sources_1/bd/design_1/ip/design_1_mul_0_0/design_1_mul_0_0.xci
# IP: The module: 'design_1_mul_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/lab1/mul_lab1/mul_lab1.gen/sources_1/bd/design_1/ip/design_1_mul_0_0/constraints/mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mul_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
