# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/project2/cordic/HLS/cordic_3a_lab/cordic/cordic.srcs/sources_1/bd/cordic/ip/cordic_rst_ps7_0_50M_0/cordic_rst_ps7_0_50M_0.xci
# IP: The module: 'cordic_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/project2/cordic/HLS/cordic_3a_lab/cordic/cordic.gen/sources_1/bd/cordic/ip/cordic_rst_ps7_0_50M_0/cordic_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/project2/cordic/HLS/cordic_3a_lab/cordic/cordic.gen/sources_1/bd/cordic/ip/cordic_rst_ps7_0_50M_0/cordic_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/project2/cordic/HLS/cordic_3a_lab/cordic/cordic.gen/sources_1/bd/cordic/ip/cordic_rst_ps7_0_50M_0/cordic_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/project2/cordic/HLS/cordic_3a_lab/cordic/cordic.srcs/sources_1/bd/cordic/ip/cordic_rst_ps7_0_50M_0/cordic_rst_ps7_0_50M_0.xci
# IP: The module: 'cordic_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/project2/cordic/HLS/cordic_3a_lab/cordic/cordic.gen/sources_1/bd/cordic/ip/cordic_rst_ps7_0_50M_0/cordic_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/project2/cordic/HLS/cordic_3a_lab/cordic/cordic.gen/sources_1/bd/cordic/ip/cordic_rst_ps7_0_50M_0/cordic_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/ieng6/students/162/mak025/Read_the_docs/project_files/project2/cordic/HLS/cordic_3a_lab/cordic/cordic.gen/sources_1/bd/cordic/ip/cordic_rst_ps7_0_50M_0/cordic_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
