# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/chole_bhature/chole_bhature.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature || ORIG_REF_NAME==chole_bhature} -quiet] -quiet

# IP: bd/chole_bhature/ip/chole_bhature_processing_system7_0_0/chole_bhature_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature_processing_system7_0_0 || ORIG_REF_NAME==chole_bhature_processing_system7_0_0} -quiet] -quiet

# IP: bd/chole_bhature/ip/chole_bhature_bnn_0_0/chole_bhature_bnn_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature_bnn_0_0 || ORIG_REF_NAME==chole_bhature_bnn_0_0} -quiet] -quiet

# IP: bd/chole_bhature/ip/chole_bhature_axi_dma_0_0/chole_bhature_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature_axi_dma_0_0 || ORIG_REF_NAME==chole_bhature_axi_dma_0_0} -quiet] -quiet

# IP: bd/chole_bhature/ip/chole_bhature_axi_smc_0/chole_bhature_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature_axi_smc_0 || ORIG_REF_NAME==chole_bhature_axi_smc_0} -quiet] -quiet

# IP: bd/chole_bhature/ip/chole_bhature_rst_ps7_0_50M_0/chole_bhature_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature_rst_ps7_0_50M_0 || ORIG_REF_NAME==chole_bhature_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/chole_bhature/ip/chole_bhature_axi_mem_intercon_imp_xbar_0/chole_bhature_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==chole_bhature_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/chole_bhature/ip/chole_bhature_axi_mem_intercon_0/chole_bhature_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature_axi_mem_intercon_0 || ORIG_REF_NAME==chole_bhature_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/chole_bhature/ip/chole_bhature_axi_mem_intercon_imp_auto_us_0/chole_bhature_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==chole_bhature_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/chole_bhature/ip/chole_bhature_axi_mem_intercon_imp_auto_us_1/chole_bhature_axi_mem_intercon_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature_axi_mem_intercon_imp_auto_us_1 || ORIG_REF_NAME==chole_bhature_axi_mem_intercon_imp_auto_us_1} -quiet] -quiet

# IP: bd/chole_bhature/ip/chole_bhature_axi_mem_intercon_imp_auto_pc_0/chole_bhature_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chole_bhature_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==chole_bhature_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# XDC: /home/linux/ieng6/students/162/mak025/chole_bhature/project_files/project5_bnn/hls_streaming/pynq_bnn/pynq_bnn.gen/sources_1/bd/chole_bhature/chole_bhature_ooc.xdc
