// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_compute_L3_Pipeline_STREAM_L3_UPDATE_L3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        l2_to_l3_dout,
        l2_to_l3_empty_n,
        l2_to_l3_read,
        l2_to_l3_num_data_valid,
        l2_to_l3_fifo_cap,
        acc_load_out,
        acc_load_out_ap_vld,
        acc_1_load_out,
        acc_1_load_out_ap_vld,
        acc_2_load_out,
        acc_2_load_out_ap_vld,
        acc_3_load_out,
        acc_3_load_out_ap_vld,
        acc_4_load_out,
        acc_4_load_out_ap_vld,
        acc_5_load_out,
        acc_5_load_out_ap_vld,
        acc_6_load_out,
        acc_6_load_out_ap_vld,
        acc_7_load_out,
        acc_7_load_out_ap_vld,
        acc_8_load_out,
        acc_8_load_out_ap_vld,
        acc_9_load_out,
        acc_9_load_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] l2_to_l3_dout;
input   l2_to_l3_empty_n;
output   l2_to_l3_read;
input  [2:0] l2_to_l3_num_data_valid;
input  [2:0] l2_to_l3_fifo_cap;
output  [11:0] acc_load_out;
output   acc_load_out_ap_vld;
output  [11:0] acc_1_load_out;
output   acc_1_load_out_ap_vld;
output  [11:0] acc_2_load_out;
output   acc_2_load_out_ap_vld;
output  [11:0] acc_3_load_out;
output   acc_3_load_out_ap_vld;
output  [11:0] acc_4_load_out;
output   acc_4_load_out_ap_vld;
output  [11:0] acc_5_load_out;
output   acc_5_load_out_ap_vld;
output  [11:0] acc_6_load_out;
output   acc_6_load_out_ap_vld;
output  [11:0] acc_7_load_out;
output   acc_7_load_out_ap_vld;
output  [11:0] acc_8_load_out;
output   acc_8_load_out_ap_vld;
output  [11:0] acc_9_load_out;
output   acc_9_load_out_ap_vld;

reg ap_idle;
reg l2_to_l3_read;
reg acc_load_out_ap_vld;
reg acc_1_load_out_ap_vld;
reg acc_2_load_out_ap_vld;
reg acc_3_load_out_ap_vld;
reg acc_4_load_out_ap_vld;
reg acc_5_load_out_ap_vld;
reg acc_6_load_out_ap_vld;
reg acc_7_load_out_ap_vld;
reg acc_8_load_out_ap_vld;
reg acc_9_load_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg   [0:0] first_iter_0_reg_2063;
reg    ap_block_state3_pp0_stage0_iter2_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln141_fu_377_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [4:0] WEIGHTS_L3_address0;
wire   [31:0] WEIGHTS_L3_q0;
reg    l2_to_l3_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [0:0] icmp_ln141_reg_2048;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln141_reg_2048_pp0_iter1_reg;
reg   [0:0] icmp_ln141_reg_2048_pp0_iter2_reg;
reg   [0:0] icmp_ln141_reg_2048_pp0_iter3_reg;
wire   [0:0] icmp_ln145_fu_397_p2;
reg   [0:0] icmp_ln145_reg_2052;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [3:0] select_ln141_fu_403_p3;
reg   [3:0] select_ln141_reg_2057;
reg   [3:0] select_ln141_reg_2057_pp0_iter2_reg;
reg   [3:0] select_ln141_reg_2057_pp0_iter3_reg;
reg   [3:0] select_ln141_reg_2057_pp0_iter4_reg;
wire   [0:0] first_iter_0_fu_411_p2;
wire   [1:0] s10_fu_1615_p2;
reg   [1:0] s10_reg_2072;
wire   [2:0] add_ln38_fu_1629_p2;
reg   [2:0] add_ln38_reg_2077;
wire   [2:0] add_ln38_1_fu_1643_p2;
reg   [2:0] add_ln38_1_reg_2082;
wire   [2:0] add_ln38_3_fu_1657_p2;
reg   [2:0] add_ln38_3_reg_2087;
wire   [2:0] add_ln38_4_fu_1671_p2;
reg   [2:0] add_ln38_4_reg_2092;
wire   [2:0] add_ln38_5_fu_1685_p2;
reg   [2:0] add_ln38_5_reg_2097;
wire   [5:0] add_ln40_1_fu_1745_p2;
reg   [5:0] add_ln40_1_reg_2102;
wire   [63:0] zext_ln147_fu_466_p1;
wire    ap_block_pp0_stage0_grp0;
reg   [3:0] n_1_fu_164;
wire   [3:0] add_ln145_fu_417_p2;
wire    ap_loop_init;
reg   [1:0] k_fu_168;
wire   [1:0] select_ln141_1_fu_437_p3;
reg   [4:0] indvar_flatten_fu_172;
wire   [4:0] add_ln141_fu_383_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg   [31:0] p_03_fu_176;
reg   [11:0] acc_9_fu_180;
wire   [11:0] acc_10_fu_1845_p2;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [11:0] acc_8_fu_184;
reg   [11:0] acc_7_fu_188;
reg   [11:0] acc_6_fu_192;
reg   [11:0] acc_5_fu_196;
reg   [11:0] acc_4_fu_200;
reg   [11:0] acc_3_fu_204;
reg   [11:0] acc_2_fu_208;
reg   [11:0] acc_1_fu_212;
reg   [11:0] acc_fu_216;
wire    ap_block_pp0_stage0_01001_grp0;
reg    WEIGHTS_L3_ce0_local;
wire   [1:0] add_ln141_1_fu_431_p2;
wire   [4:0] shl_ln_fu_453_p3;
wire   [4:0] zext_ln141_fu_449_p1;
wire   [4:0] add_ln147_fu_460_p2;
wire   [0:0] trunc_ln20_1_fu_731_p1;
wire   [0:0] xor_ln20_fu_735_p2;
wire   [0:0] trunc_ln20_fu_479_p1;
wire   [0:0] xor_ln20_1_fu_741_p2;
wire   [0:0] tmp_fu_483_p3;
wire   [0:0] tmp_31_fu_751_p3;
wire   [0:0] xor_ln20_2_fu_759_p2;
wire   [0:0] xor_ln20_3_fu_765_p2;
wire   [0:0] tmp_1_fu_491_p3;
wire   [0:0] tmp_32_fu_775_p3;
wire   [0:0] xor_ln20_4_fu_783_p2;
wire   [0:0] xor_ln20_5_fu_789_p2;
wire   [1:0] zext_ln20_1_fu_771_p1;
wire   [1:0] zext_ln20_2_fu_795_p1;
wire   [1:0] add_ln20_fu_799_p2;
wire   [1:0] zext_ln20_fu_747_p1;
wire   [0:0] tmp_2_fu_499_p3;
wire   [0:0] tmp_33_fu_811_p3;
wire   [0:0] xor_ln20_6_fu_819_p2;
wire   [0:0] xor_ln20_7_fu_825_p2;
wire   [0:0] tmp_3_fu_507_p3;
wire   [0:0] tmp_34_fu_835_p3;
wire   [0:0] xor_ln20_8_fu_843_p2;
wire   [0:0] xor_ln20_9_fu_849_p2;
wire   [0:0] tmp_4_fu_515_p3;
wire   [0:0] tmp_35_fu_859_p3;
wire   [0:0] xor_ln20_10_fu_867_p2;
wire   [0:0] xor_ln20_11_fu_873_p2;
wire   [1:0] zext_ln20_3_fu_831_p1;
wire   [1:0] zext_ln20_5_fu_879_p1;
wire   [1:0] add_ln20_2_fu_883_p2;
wire   [1:0] zext_ln20_4_fu_855_p1;
wire   [0:0] tmp_5_fu_523_p3;
wire   [0:0] tmp_36_fu_895_p3;
wire   [0:0] xor_ln20_12_fu_903_p2;
wire   [0:0] xor_ln20_13_fu_909_p2;
wire   [0:0] tmp_6_fu_531_p3;
wire   [0:0] tmp_37_fu_919_p3;
wire   [0:0] xor_ln20_14_fu_927_p2;
wire   [0:0] xor_ln20_15_fu_933_p2;
wire   [0:0] tmp_7_fu_539_p3;
wire   [0:0] tmp_38_fu_943_p3;
wire   [0:0] xor_ln20_16_fu_951_p2;
wire   [0:0] xor_ln20_17_fu_957_p2;
wire   [1:0] zext_ln20_6_fu_915_p1;
wire   [1:0] zext_ln20_8_fu_963_p1;
wire   [1:0] add_ln20_4_fu_967_p2;
wire   [1:0] zext_ln20_7_fu_939_p1;
wire   [0:0] tmp_8_fu_547_p3;
wire   [0:0] tmp_39_fu_979_p3;
wire   [0:0] xor_ln20_18_fu_987_p2;
wire   [0:0] xor_ln20_19_fu_993_p2;
wire   [0:0] tmp_9_fu_555_p3;
wire   [0:0] tmp_40_fu_1003_p3;
wire   [0:0] xor_ln20_20_fu_1011_p2;
wire   [0:0] xor_ln20_21_fu_1017_p2;
wire   [0:0] tmp_10_fu_563_p3;
wire   [0:0] tmp_41_fu_1027_p3;
wire   [0:0] xor_ln20_22_fu_1035_p2;
wire   [0:0] xor_ln20_23_fu_1041_p2;
wire   [1:0] zext_ln20_9_fu_999_p1;
wire   [1:0] zext_ln20_11_fu_1047_p1;
wire   [1:0] add_ln20_6_fu_1051_p2;
wire   [1:0] zext_ln20_10_fu_1023_p1;
wire   [0:0] tmp_11_fu_571_p3;
wire   [0:0] tmp_42_fu_1063_p3;
wire   [0:0] xor_ln20_24_fu_1071_p2;
wire   [0:0] xor_ln20_25_fu_1077_p2;
wire   [0:0] tmp_12_fu_579_p3;
wire   [0:0] tmp_43_fu_1087_p3;
wire   [0:0] xor_ln20_26_fu_1095_p2;
wire   [0:0] xor_ln20_27_fu_1101_p2;
wire   [0:0] tmp_13_fu_587_p3;
wire   [0:0] tmp_44_fu_1111_p3;
wire   [0:0] xor_ln20_28_fu_1119_p2;
wire   [0:0] xor_ln20_29_fu_1125_p2;
wire   [1:0] zext_ln20_12_fu_1083_p1;
wire   [1:0] zext_ln20_14_fu_1131_p1;
wire   [1:0] add_ln20_8_fu_1135_p2;
wire   [1:0] zext_ln20_13_fu_1107_p1;
wire   [0:0] tmp_14_fu_595_p3;
wire   [0:0] tmp_45_fu_1147_p3;
wire   [0:0] xor_ln20_30_fu_1155_p2;
wire   [0:0] xor_ln20_31_fu_1161_p2;
wire   [0:0] tmp_15_fu_603_p3;
wire   [0:0] tmp_46_fu_1171_p3;
wire   [0:0] xor_ln20_32_fu_1179_p2;
wire   [0:0] xor_ln20_33_fu_1185_p2;
wire   [0:0] tmp_16_fu_611_p3;
wire   [0:0] tmp_47_fu_1195_p3;
wire   [0:0] xor_ln20_34_fu_1203_p2;
wire   [0:0] xor_ln20_35_fu_1209_p2;
wire   [1:0] zext_ln20_15_fu_1167_p1;
wire   [1:0] zext_ln20_17_fu_1215_p1;
wire   [1:0] add_ln20_10_fu_1219_p2;
wire   [1:0] zext_ln20_16_fu_1191_p1;
wire   [0:0] tmp_17_fu_619_p3;
wire   [0:0] tmp_48_fu_1231_p3;
wire   [0:0] xor_ln20_36_fu_1239_p2;
wire   [0:0] xor_ln20_37_fu_1245_p2;
wire   [0:0] tmp_18_fu_627_p3;
wire   [0:0] tmp_49_fu_1255_p3;
wire   [0:0] xor_ln20_38_fu_1263_p2;
wire   [0:0] xor_ln20_39_fu_1269_p2;
wire   [0:0] tmp_19_fu_635_p3;
wire   [0:0] tmp_50_fu_1279_p3;
wire   [0:0] xor_ln20_40_fu_1287_p2;
wire   [0:0] xor_ln20_41_fu_1293_p2;
wire   [1:0] zext_ln20_18_fu_1251_p1;
wire   [1:0] zext_ln20_20_fu_1299_p1;
wire   [1:0] add_ln20_12_fu_1303_p2;
wire   [1:0] zext_ln20_19_fu_1275_p1;
wire   [0:0] tmp_51_fu_1315_p3;
wire   [0:0] xor_ln20_42_fu_1323_p2;
wire   [0:0] tmp_20_fu_643_p3;
wire   [0:0] xor_ln20_43_fu_1329_p2;
wire   [0:0] tmp_52_fu_1339_p3;
wire   [0:0] xor_ln20_44_fu_1347_p2;
wire   [0:0] tmp_21_fu_651_p3;
wire   [0:0] xor_ln20_45_fu_1353_p2;
wire   [0:0] tmp_53_fu_1363_p3;
wire   [0:0] xor_ln20_46_fu_1371_p2;
wire   [0:0] tmp_22_fu_659_p3;
wire   [0:0] xor_ln20_47_fu_1377_p2;
wire   [1:0] zext_ln20_22_fu_1359_p1;
wire   [1:0] zext_ln20_23_fu_1383_p1;
wire   [1:0] add_ln20_14_fu_1387_p2;
wire   [1:0] zext_ln20_21_fu_1335_p1;
wire   [0:0] tmp_54_fu_1399_p3;
wire   [0:0] xor_ln20_48_fu_1407_p2;
wire   [0:0] tmp_23_fu_667_p3;
wire   [0:0] xor_ln20_49_fu_1413_p2;
wire   [0:0] tmp_55_fu_1423_p3;
wire   [0:0] xor_ln20_50_fu_1431_p2;
wire   [0:0] tmp_24_fu_675_p3;
wire   [0:0] xor_ln20_51_fu_1437_p2;
wire   [0:0] tmp_56_fu_1447_p3;
wire   [0:0] xor_ln20_52_fu_1455_p2;
wire   [0:0] tmp_25_fu_683_p3;
wire   [0:0] xor_ln20_53_fu_1461_p2;
wire   [1:0] zext_ln20_25_fu_1443_p1;
wire   [1:0] zext_ln20_26_fu_1467_p1;
wire   [1:0] add_ln20_16_fu_1471_p2;
wire   [1:0] zext_ln20_24_fu_1419_p1;
wire   [0:0] tmp_57_fu_1483_p3;
wire   [0:0] xor_ln20_54_fu_1491_p2;
wire   [0:0] tmp_26_fu_691_p3;
wire   [0:0] xor_ln20_55_fu_1497_p2;
wire   [0:0] tmp_58_fu_1507_p3;
wire   [0:0] xor_ln20_56_fu_1515_p2;
wire   [0:0] tmp_27_fu_699_p3;
wire   [0:0] xor_ln20_57_fu_1521_p2;
wire   [0:0] tmp_59_fu_1531_p3;
wire   [0:0] xor_ln20_58_fu_1539_p2;
wire   [0:0] tmp_28_fu_707_p3;
wire   [0:0] xor_ln20_59_fu_1545_p2;
wire   [1:0] zext_ln20_27_fu_1503_p1;
wire   [1:0] zext_ln20_28_fu_1527_p1;
wire   [1:0] add_ln20_18_fu_1555_p2;
wire   [1:0] zext_ln20_29_fu_1551_p1;
wire   [0:0] tmp_29_fu_715_p3;
wire   [0:0] tmp_60_fu_1567_p3;
wire   [0:0] xor_ln36_fu_1575_p2;
wire   [0:0] xor_ln36_1_fu_1581_p2;
wire   [0:0] tmp_30_fu_723_p3;
wire   [0:0] tmp_61_fu_1591_p3;
wire   [0:0] xor_ln36_2_fu_1599_p2;
wire   [0:0] xor_ln36_3_fu_1605_p2;
wire   [1:0] zext_ln36_1_fu_1611_p1;
wire   [1:0] zext_ln36_fu_1587_p1;
wire   [1:0] s0_fu_805_p2;
wire   [1:0] s1_fu_889_p2;
wire   [2:0] zext_ln38_1_fu_1625_p1;
wire   [2:0] zext_ln38_fu_1621_p1;
wire   [1:0] s2_fu_973_p2;
wire   [1:0] s3_fu_1057_p2;
wire   [2:0] zext_ln38_3_fu_1639_p1;
wire   [2:0] zext_ln38_2_fu_1635_p1;
wire   [1:0] s4_fu_1141_p2;
wire   [1:0] s5_fu_1225_p2;
wire   [2:0] zext_ln38_7_fu_1653_p1;
wire   [2:0] zext_ln38_6_fu_1649_p1;
wire   [1:0] s6_fu_1309_p2;
wire   [1:0] s7_fu_1393_p2;
wire   [2:0] zext_ln38_11_fu_1667_p1;
wire   [2:0] zext_ln38_10_fu_1663_p1;
wire   [1:0] s8_fu_1477_p2;
wire   [1:0] s9_fu_1561_p2;
wire   [2:0] zext_ln38_14_fu_1681_p1;
wire   [2:0] zext_ln38_13_fu_1677_p1;
wire   [3:0] zext_ln38_5_fu_1694_p1;
wire   [3:0] zext_ln38_4_fu_1691_p1;
wire   [3:0] add_ln38_2_fu_1697_p2;
wire   [3:0] zext_ln38_12_fu_1710_p1;
wire   [3:0] zext_ln38_15_fu_1713_p1;
wire   [3:0] add_ln38_7_fu_1719_p2;
wire   [4:0] zext_ln38_17_fu_1725_p1;
wire   [4:0] zext_ln38_9_fu_1707_p1;
wire   [4:0] add_ln38_6_fu_1729_p2;
wire   [4:0] zext_ln38_8_fu_1703_p1;
wire   [4:0] add_ln38_8_fu_1735_p2;
wire   [5:0] zext_ln40_fu_1741_p1;
wire   [5:0] zext_ln38_16_fu_1716_p1;
wire   [6:0] shl_ln1_fu_1751_p3;
wire   [6:0] add_ln40_fu_1758_p2;
wire   [11:0] tmp_s_fu_1798_p21;
wire   [11:0] tmp_s_fu_1798_p23;
wire  signed [11:0] sext_ln147_fu_1764_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_1366;
wire   [3:0] tmp_s_fu_1798_p1;
wire   [3:0] tmp_s_fu_1798_p3;
wire   [3:0] tmp_s_fu_1798_p5;
wire   [3:0] tmp_s_fu_1798_p7;
wire   [3:0] tmp_s_fu_1798_p9;
wire   [3:0] tmp_s_fu_1798_p11;
wire   [3:0] tmp_s_fu_1798_p13;
wire   [3:0] tmp_s_fu_1798_p15;
wire  signed [3:0] tmp_s_fu_1798_p17;
wire  signed [3:0] tmp_s_fu_1798_p19;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 n_1_fu_164 = 4'd0;
#0 k_fu_168 = 2'd0;
#0 indvar_flatten_fu_172 = 5'd0;
#0 p_03_fu_176 = 32'd0;
#0 acc_9_fu_180 = 12'd0;
#0 acc_8_fu_184 = 12'd0;
#0 acc_7_fu_188 = 12'd0;
#0 acc_6_fu_192 = 12'd0;
#0 acc_5_fu_196 = 12'd0;
#0 acc_4_fu_200 = 12'd0;
#0 acc_3_fu_204 = 12'd0;
#0 acc_2_fu_208 = 12'd0;
#0 acc_1_fu_212 = 12'd0;
#0 acc_fu_216 = 12'd0;
#0 ap_done_reg = 1'b0;
end

bnn_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_WEIGHTS_L3_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 20 ),
    .AddressWidth( 5 ))
WEIGHTS_L3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(WEIGHTS_L3_address0),
    .ce0(WEIGHTS_L3_ce0_local),
    .q0(WEIGHTS_L3_q0)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_21_4_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 12 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 12 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 12 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 12 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 12 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 12 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 12 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 12 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
sparsemux_21_4_12_1_1_U983(
    .din0(acc_fu_216),
    .din1(acc_1_fu_212),
    .din2(acc_2_fu_208),
    .din3(acc_3_fu_204),
    .din4(acc_4_fu_200),
    .din5(acc_5_fu_196),
    .din6(acc_6_fu_192),
    .din7(acc_7_fu_188),
    .din8(acc_8_fu_184),
    .din9(acc_9_fu_180),
    .def(tmp_s_fu_1798_p21),
    .sel(select_ln141_reg_2057_pp0_iter4_reg),
    .dout(tmp_s_fu_1798_p23)
);

bnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_1_fu_212 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln141_reg_2057_pp0_iter4_reg == 4'd1))) begin
            acc_1_fu_212 <= acc_10_fu_1845_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_2_fu_208 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln141_reg_2057_pp0_iter4_reg == 4'd2))) begin
            acc_2_fu_208 <= acc_10_fu_1845_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_3_fu_204 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln141_reg_2057_pp0_iter4_reg == 4'd3))) begin
            acc_3_fu_204 <= acc_10_fu_1845_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_4_fu_200 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln141_reg_2057_pp0_iter4_reg == 4'd4))) begin
            acc_4_fu_200 <= acc_10_fu_1845_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_5_fu_196 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln141_reg_2057_pp0_iter4_reg == 4'd5))) begin
            acc_5_fu_196 <= acc_10_fu_1845_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_6_fu_192 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln141_reg_2057_pp0_iter4_reg == 4'd6))) begin
            acc_6_fu_192 <= acc_10_fu_1845_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_7_fu_188 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln141_reg_2057_pp0_iter4_reg == 4'd7))) begin
            acc_7_fu_188 <= acc_10_fu_1845_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_8_fu_184 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln141_reg_2057_pp0_iter4_reg == 4'd8))) begin
            acc_8_fu_184 <= acc_10_fu_1845_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_9_fu_180 <= 12'd0;
        end else if ((1'b1 == ap_condition_1366)) begin
            acc_9_fu_180 <= acc_10_fu_1845_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_fu_216 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (select_ln141_reg_2057_pp0_iter4_reg == 4'd0))) begin
            acc_fu_216 <= acc_10_fu_1845_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln141_fu_377_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_172 <= add_ln141_fu_383_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_172 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            k_fu_168 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            k_fu_168 <= select_ln141_1_fu_437_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            n_1_fu_164 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            n_1_fu_164 <= add_ln145_fu_417_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln38_1_reg_2082 <= add_ln38_1_fu_1643_p2;
        add_ln38_3_reg_2087 <= add_ln38_3_fu_1657_p2;
        add_ln38_4_reg_2092 <= add_ln38_4_fu_1671_p2;
        add_ln38_5_reg_2097 <= add_ln38_5_fu_1685_p2;
        add_ln38_reg_2077 <= add_ln38_fu_1629_p2;
        add_ln40_1_reg_2102 <= add_ln40_1_fu_1745_p2;
        s10_reg_2072 <= s10_fu_1615_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln141_reg_2048 <= icmp_ln141_fu_377_p2;
        icmp_ln141_reg_2048_pp0_iter1_reg <= icmp_ln141_reg_2048;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln141_reg_2048_pp0_iter2_reg <= icmp_ln141_reg_2048_pp0_iter1_reg;
        icmp_ln141_reg_2048_pp0_iter3_reg <= icmp_ln141_reg_2048_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_iter_0_reg_2063 <= first_iter_0_fu_411_p2;
        icmp_ln145_reg_2052 <= icmp_ln145_fu_397_p2;
        select_ln141_reg_2057 <= select_ln141_fu_403_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (first_iter_0_reg_2063 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_03_fu_176 <= l2_to_l3_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        select_ln141_reg_2057_pp0_iter2_reg <= select_ln141_reg_2057;
        select_ln141_reg_2057_pp0_iter3_reg <= select_ln141_reg_2057_pp0_iter2_reg;
        select_ln141_reg_2057_pp0_iter4_reg <= select_ln141_reg_2057_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        WEIGHTS_L3_ce0_local = 1'b1;
    end else begin
        WEIGHTS_L3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln141_reg_2048_pp0_iter3_reg == 1'd1))) begin
        acc_1_load_out_ap_vld = 1'b1;
    end else begin
        acc_1_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln141_reg_2048_pp0_iter3_reg == 1'd1))) begin
        acc_2_load_out_ap_vld = 1'b1;
    end else begin
        acc_2_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln141_reg_2048_pp0_iter3_reg == 1'd1))) begin
        acc_3_load_out_ap_vld = 1'b1;
    end else begin
        acc_3_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln141_reg_2048_pp0_iter3_reg == 1'd1))) begin
        acc_4_load_out_ap_vld = 1'b1;
    end else begin
        acc_4_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln141_reg_2048_pp0_iter3_reg == 1'd1))) begin
        acc_5_load_out_ap_vld = 1'b1;
    end else begin
        acc_5_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln141_reg_2048_pp0_iter3_reg == 1'd1))) begin
        acc_6_load_out_ap_vld = 1'b1;
    end else begin
        acc_6_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln141_reg_2048_pp0_iter3_reg == 1'd1))) begin
        acc_7_load_out_ap_vld = 1'b1;
    end else begin
        acc_7_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln141_reg_2048_pp0_iter3_reg == 1'd1))) begin
        acc_8_load_out_ap_vld = 1'b1;
    end else begin
        acc_8_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln141_reg_2048_pp0_iter3_reg == 1'd1))) begin
        acc_9_load_out_ap_vld = 1'b1;
    end else begin
        acc_9_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln141_reg_2048_pp0_iter3_reg == 1'd1))) begin
        acc_load_out_ap_vld = 1'b1;
    end else begin
        acc_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln141_fu_377_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_172;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (first_iter_0_reg_2063 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        l2_to_l3_blk_n = l2_to_l3_empty_n;
    end else begin
        l2_to_l3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (first_iter_0_reg_2063 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        l2_to_l3_read = 1'b1;
    end else begin
        l2_to_l3_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign WEIGHTS_L3_address0 = zext_ln147_fu_466_p1;

assign acc_10_fu_1845_p2 = ($signed(tmp_s_fu_1798_p23) + $signed(sext_ln147_fu_1764_p1));

assign acc_1_load_out = acc_1_fu_212;

assign acc_2_load_out = acc_2_fu_208;

assign acc_3_load_out = acc_3_fu_204;

assign acc_4_load_out = acc_4_fu_200;

assign acc_5_load_out = acc_5_fu_196;

assign acc_6_load_out = acc_6_fu_192;

assign acc_7_load_out = acc_7_fu_188;

assign acc_8_load_out = acc_8_fu_184;

assign acc_9_load_out = acc_9_fu_180;

assign acc_load_out = acc_fu_216;

assign add_ln141_1_fu_431_p2 = (k_fu_168 + 2'd1);

assign add_ln141_fu_383_p2 = (ap_sig_allocacmp_indvar_flatten_load + 5'd1);

assign add_ln145_fu_417_p2 = (select_ln141_fu_403_p3 + 4'd1);

assign add_ln147_fu_460_p2 = (shl_ln_fu_453_p3 + zext_ln141_fu_449_p1);

assign add_ln20_10_fu_1219_p2 = (zext_ln20_15_fu_1167_p1 + zext_ln20_17_fu_1215_p1);

assign add_ln20_12_fu_1303_p2 = (zext_ln20_18_fu_1251_p1 + zext_ln20_20_fu_1299_p1);

assign add_ln20_14_fu_1387_p2 = (zext_ln20_22_fu_1359_p1 + zext_ln20_23_fu_1383_p1);

assign add_ln20_16_fu_1471_p2 = (zext_ln20_25_fu_1443_p1 + zext_ln20_26_fu_1467_p1);

assign add_ln20_18_fu_1555_p2 = (zext_ln20_27_fu_1503_p1 + zext_ln20_28_fu_1527_p1);

assign add_ln20_2_fu_883_p2 = (zext_ln20_3_fu_831_p1 + zext_ln20_5_fu_879_p1);

assign add_ln20_4_fu_967_p2 = (zext_ln20_6_fu_915_p1 + zext_ln20_8_fu_963_p1);

assign add_ln20_6_fu_1051_p2 = (zext_ln20_9_fu_999_p1 + zext_ln20_11_fu_1047_p1);

assign add_ln20_8_fu_1135_p2 = (zext_ln20_12_fu_1083_p1 + zext_ln20_14_fu_1131_p1);

assign add_ln20_fu_799_p2 = (zext_ln20_1_fu_771_p1 + zext_ln20_2_fu_795_p1);

assign add_ln38_1_fu_1643_p2 = (zext_ln38_3_fu_1639_p1 + zext_ln38_2_fu_1635_p1);

assign add_ln38_2_fu_1697_p2 = (zext_ln38_5_fu_1694_p1 + zext_ln38_4_fu_1691_p1);

assign add_ln38_3_fu_1657_p2 = (zext_ln38_7_fu_1653_p1 + zext_ln38_6_fu_1649_p1);

assign add_ln38_4_fu_1671_p2 = (zext_ln38_11_fu_1667_p1 + zext_ln38_10_fu_1663_p1);

assign add_ln38_5_fu_1685_p2 = (zext_ln38_14_fu_1681_p1 + zext_ln38_13_fu_1677_p1);

assign add_ln38_6_fu_1729_p2 = (zext_ln38_17_fu_1725_p1 + zext_ln38_9_fu_1707_p1);

assign add_ln38_7_fu_1719_p2 = (zext_ln38_12_fu_1710_p1 + zext_ln38_15_fu_1713_p1);

assign add_ln38_8_fu_1735_p2 = (add_ln38_6_fu_1729_p2 + zext_ln38_8_fu_1703_p1);

assign add_ln38_fu_1629_p2 = (zext_ln38_1_fu_1625_p1 + zext_ln38_fu_1621_p1);

assign add_ln40_1_fu_1745_p2 = (zext_ln40_fu_1741_p1 + zext_ln38_16_fu_1716_p1);

assign add_ln40_fu_1758_p2 = ($signed(shl_ln1_fu_1751_p3) + $signed(7'd96));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2_grp1 = ((first_iter_0_reg_2063 == 1'd1) & (l2_to_l3_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_1366 = (~(select_ln141_reg_2057_pp0_iter4_reg == 4'd8) & ~(select_ln141_reg_2057_pp0_iter4_reg == 4'd7) & ~(select_ln141_reg_2057_pp0_iter4_reg == 4'd6) & ~(select_ln141_reg_2057_pp0_iter4_reg == 4'd5) & ~(select_ln141_reg_2057_pp0_iter4_reg == 4'd4) & ~(select_ln141_reg_2057_pp0_iter4_reg == 4'd3) & ~(select_ln141_reg_2057_pp0_iter4_reg == 4'd2) & ~(select_ln141_reg_2057_pp0_iter4_reg == 4'd1) & ~(select_ln141_reg_2057_pp0_iter4_reg == 4'd0) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign first_iter_0_fu_411_p2 = ((select_ln141_fu_403_p3 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_377_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 5'd20) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_397_p2 = ((n_1_fu_164 == 4'd10) ? 1'b1 : 1'b0);

assign s0_fu_805_p2 = (add_ln20_fu_799_p2 + zext_ln20_fu_747_p1);

assign s10_fu_1615_p2 = (zext_ln36_1_fu_1611_p1 + zext_ln36_fu_1587_p1);

assign s1_fu_889_p2 = (add_ln20_2_fu_883_p2 + zext_ln20_4_fu_855_p1);

assign s2_fu_973_p2 = (add_ln20_4_fu_967_p2 + zext_ln20_7_fu_939_p1);

assign s3_fu_1057_p2 = (add_ln20_6_fu_1051_p2 + zext_ln20_10_fu_1023_p1);

assign s4_fu_1141_p2 = (add_ln20_8_fu_1135_p2 + zext_ln20_13_fu_1107_p1);

assign s5_fu_1225_p2 = (add_ln20_10_fu_1219_p2 + zext_ln20_16_fu_1191_p1);

assign s6_fu_1309_p2 = (add_ln20_12_fu_1303_p2 + zext_ln20_19_fu_1275_p1);

assign s7_fu_1393_p2 = (add_ln20_14_fu_1387_p2 + zext_ln20_21_fu_1335_p1);

assign s8_fu_1477_p2 = (add_ln20_16_fu_1471_p2 + zext_ln20_24_fu_1419_p1);

assign s9_fu_1561_p2 = (add_ln20_18_fu_1555_p2 + zext_ln20_29_fu_1551_p1);

assign select_ln141_1_fu_437_p3 = ((icmp_ln145_reg_2052[0:0] == 1'b1) ? add_ln141_1_fu_431_p2 : k_fu_168);

assign select_ln141_fu_403_p3 = ((icmp_ln145_fu_397_p2[0:0] == 1'b1) ? 4'd0 : n_1_fu_164);

assign sext_ln147_fu_1764_p1 = $signed(add_ln40_fu_1758_p2);

assign shl_ln1_fu_1751_p3 = {{add_ln40_1_reg_2102}, {1'd0}};

assign shl_ln_fu_453_p3 = {{select_ln141_reg_2057}, {1'd0}};

assign tmp_10_fu_563_p3 = p_03_fu_176[32'd11];

assign tmp_11_fu_571_p3 = p_03_fu_176[32'd12];

assign tmp_12_fu_579_p3 = p_03_fu_176[32'd13];

assign tmp_13_fu_587_p3 = p_03_fu_176[32'd14];

assign tmp_14_fu_595_p3 = p_03_fu_176[32'd15];

assign tmp_15_fu_603_p3 = p_03_fu_176[32'd16];

assign tmp_16_fu_611_p3 = p_03_fu_176[32'd17];

assign tmp_17_fu_619_p3 = p_03_fu_176[32'd18];

assign tmp_18_fu_627_p3 = p_03_fu_176[32'd19];

assign tmp_19_fu_635_p3 = p_03_fu_176[32'd20];

assign tmp_1_fu_491_p3 = p_03_fu_176[32'd2];

assign tmp_20_fu_643_p3 = p_03_fu_176[32'd21];

assign tmp_21_fu_651_p3 = p_03_fu_176[32'd22];

assign tmp_22_fu_659_p3 = p_03_fu_176[32'd23];

assign tmp_23_fu_667_p3 = p_03_fu_176[32'd24];

assign tmp_24_fu_675_p3 = p_03_fu_176[32'd25];

assign tmp_25_fu_683_p3 = p_03_fu_176[32'd26];

assign tmp_26_fu_691_p3 = p_03_fu_176[32'd27];

assign tmp_27_fu_699_p3 = p_03_fu_176[32'd28];

assign tmp_28_fu_707_p3 = p_03_fu_176[32'd29];

assign tmp_29_fu_715_p3 = p_03_fu_176[32'd30];

assign tmp_2_fu_499_p3 = p_03_fu_176[32'd3];

assign tmp_30_fu_723_p3 = p_03_fu_176[32'd31];

assign tmp_31_fu_751_p3 = WEIGHTS_L3_q0[32'd1];

assign tmp_32_fu_775_p3 = WEIGHTS_L3_q0[32'd2];

assign tmp_33_fu_811_p3 = WEIGHTS_L3_q0[32'd3];

assign tmp_34_fu_835_p3 = WEIGHTS_L3_q0[32'd4];

assign tmp_35_fu_859_p3 = WEIGHTS_L3_q0[32'd5];

assign tmp_36_fu_895_p3 = WEIGHTS_L3_q0[32'd6];

assign tmp_37_fu_919_p3 = WEIGHTS_L3_q0[32'd7];

assign tmp_38_fu_943_p3 = WEIGHTS_L3_q0[32'd8];

assign tmp_39_fu_979_p3 = WEIGHTS_L3_q0[32'd9];

assign tmp_3_fu_507_p3 = p_03_fu_176[32'd4];

assign tmp_40_fu_1003_p3 = WEIGHTS_L3_q0[32'd10];

assign tmp_41_fu_1027_p3 = WEIGHTS_L3_q0[32'd11];

assign tmp_42_fu_1063_p3 = WEIGHTS_L3_q0[32'd12];

assign tmp_43_fu_1087_p3 = WEIGHTS_L3_q0[32'd13];

assign tmp_44_fu_1111_p3 = WEIGHTS_L3_q0[32'd14];

assign tmp_45_fu_1147_p3 = WEIGHTS_L3_q0[32'd15];

assign tmp_46_fu_1171_p3 = WEIGHTS_L3_q0[32'd16];

assign tmp_47_fu_1195_p3 = WEIGHTS_L3_q0[32'd17];

assign tmp_48_fu_1231_p3 = WEIGHTS_L3_q0[32'd18];

assign tmp_49_fu_1255_p3 = WEIGHTS_L3_q0[32'd19];

assign tmp_4_fu_515_p3 = p_03_fu_176[32'd5];

assign tmp_50_fu_1279_p3 = WEIGHTS_L3_q0[32'd20];

assign tmp_51_fu_1315_p3 = WEIGHTS_L3_q0[32'd21];

assign tmp_52_fu_1339_p3 = WEIGHTS_L3_q0[32'd22];

assign tmp_53_fu_1363_p3 = WEIGHTS_L3_q0[32'd23];

assign tmp_54_fu_1399_p3 = WEIGHTS_L3_q0[32'd24];

assign tmp_55_fu_1423_p3 = WEIGHTS_L3_q0[32'd25];

assign tmp_56_fu_1447_p3 = WEIGHTS_L3_q0[32'd26];

assign tmp_57_fu_1483_p3 = WEIGHTS_L3_q0[32'd27];

assign tmp_58_fu_1507_p3 = WEIGHTS_L3_q0[32'd28];

assign tmp_59_fu_1531_p3 = WEIGHTS_L3_q0[32'd29];

assign tmp_5_fu_523_p3 = p_03_fu_176[32'd6];

assign tmp_60_fu_1567_p3 = WEIGHTS_L3_q0[32'd30];

assign tmp_61_fu_1591_p3 = WEIGHTS_L3_q0[32'd31];

assign tmp_6_fu_531_p3 = p_03_fu_176[32'd7];

assign tmp_7_fu_539_p3 = p_03_fu_176[32'd8];

assign tmp_8_fu_547_p3 = p_03_fu_176[32'd9];

assign tmp_9_fu_555_p3 = p_03_fu_176[32'd10];

assign tmp_fu_483_p3 = p_03_fu_176[32'd1];

assign tmp_s_fu_1798_p21 = 'bx;

assign trunc_ln20_1_fu_731_p1 = WEIGHTS_L3_q0[0:0];

assign trunc_ln20_fu_479_p1 = p_03_fu_176[0:0];

assign xor_ln20_10_fu_867_p2 = (tmp_4_fu_515_p3 ^ tmp_35_fu_859_p3);

assign xor_ln20_11_fu_873_p2 = (xor_ln20_10_fu_867_p2 ^ 1'd1);

assign xor_ln20_12_fu_903_p2 = (tmp_5_fu_523_p3 ^ tmp_36_fu_895_p3);

assign xor_ln20_13_fu_909_p2 = (xor_ln20_12_fu_903_p2 ^ 1'd1);

assign xor_ln20_14_fu_927_p2 = (tmp_6_fu_531_p3 ^ tmp_37_fu_919_p3);

assign xor_ln20_15_fu_933_p2 = (xor_ln20_14_fu_927_p2 ^ 1'd1);

assign xor_ln20_16_fu_951_p2 = (tmp_7_fu_539_p3 ^ tmp_38_fu_943_p3);

assign xor_ln20_17_fu_957_p2 = (xor_ln20_16_fu_951_p2 ^ 1'd1);

assign xor_ln20_18_fu_987_p2 = (tmp_8_fu_547_p3 ^ tmp_39_fu_979_p3);

assign xor_ln20_19_fu_993_p2 = (xor_ln20_18_fu_987_p2 ^ 1'd1);

assign xor_ln20_1_fu_741_p2 = (xor_ln20_fu_735_p2 ^ trunc_ln20_fu_479_p1);

assign xor_ln20_20_fu_1011_p2 = (tmp_9_fu_555_p3 ^ tmp_40_fu_1003_p3);

assign xor_ln20_21_fu_1017_p2 = (xor_ln20_20_fu_1011_p2 ^ 1'd1);

assign xor_ln20_22_fu_1035_p2 = (tmp_41_fu_1027_p3 ^ tmp_10_fu_563_p3);

assign xor_ln20_23_fu_1041_p2 = (xor_ln20_22_fu_1035_p2 ^ 1'd1);

assign xor_ln20_24_fu_1071_p2 = (tmp_42_fu_1063_p3 ^ tmp_11_fu_571_p3);

assign xor_ln20_25_fu_1077_p2 = (xor_ln20_24_fu_1071_p2 ^ 1'd1);

assign xor_ln20_26_fu_1095_p2 = (tmp_43_fu_1087_p3 ^ tmp_12_fu_579_p3);

assign xor_ln20_27_fu_1101_p2 = (xor_ln20_26_fu_1095_p2 ^ 1'd1);

assign xor_ln20_28_fu_1119_p2 = (tmp_44_fu_1111_p3 ^ tmp_13_fu_587_p3);

assign xor_ln20_29_fu_1125_p2 = (xor_ln20_28_fu_1119_p2 ^ 1'd1);

assign xor_ln20_2_fu_759_p2 = (tmp_fu_483_p3 ^ tmp_31_fu_751_p3);

assign xor_ln20_30_fu_1155_p2 = (tmp_45_fu_1147_p3 ^ tmp_14_fu_595_p3);

assign xor_ln20_31_fu_1161_p2 = (xor_ln20_30_fu_1155_p2 ^ 1'd1);

assign xor_ln20_32_fu_1179_p2 = (tmp_46_fu_1171_p3 ^ tmp_15_fu_603_p3);

assign xor_ln20_33_fu_1185_p2 = (xor_ln20_32_fu_1179_p2 ^ 1'd1);

assign xor_ln20_34_fu_1203_p2 = (tmp_47_fu_1195_p3 ^ tmp_16_fu_611_p3);

assign xor_ln20_35_fu_1209_p2 = (xor_ln20_34_fu_1203_p2 ^ 1'd1);

assign xor_ln20_36_fu_1239_p2 = (tmp_48_fu_1231_p3 ^ tmp_17_fu_619_p3);

assign xor_ln20_37_fu_1245_p2 = (xor_ln20_36_fu_1239_p2 ^ 1'd1);

assign xor_ln20_38_fu_1263_p2 = (tmp_49_fu_1255_p3 ^ tmp_18_fu_627_p3);

assign xor_ln20_39_fu_1269_p2 = (xor_ln20_38_fu_1263_p2 ^ 1'd1);

assign xor_ln20_3_fu_765_p2 = (xor_ln20_2_fu_759_p2 ^ 1'd1);

assign xor_ln20_40_fu_1287_p2 = (tmp_50_fu_1279_p3 ^ tmp_19_fu_635_p3);

assign xor_ln20_41_fu_1293_p2 = (xor_ln20_40_fu_1287_p2 ^ 1'd1);

assign xor_ln20_42_fu_1323_p2 = (tmp_51_fu_1315_p3 ^ 1'd1);

assign xor_ln20_43_fu_1329_p2 = (xor_ln20_42_fu_1323_p2 ^ tmp_20_fu_643_p3);

assign xor_ln20_44_fu_1347_p2 = (tmp_52_fu_1339_p3 ^ 1'd1);

assign xor_ln20_45_fu_1353_p2 = (xor_ln20_44_fu_1347_p2 ^ tmp_21_fu_651_p3);

assign xor_ln20_46_fu_1371_p2 = (tmp_53_fu_1363_p3 ^ 1'd1);

assign xor_ln20_47_fu_1377_p2 = (xor_ln20_46_fu_1371_p2 ^ tmp_22_fu_659_p3);

assign xor_ln20_48_fu_1407_p2 = (tmp_54_fu_1399_p3 ^ 1'd1);

assign xor_ln20_49_fu_1413_p2 = (xor_ln20_48_fu_1407_p2 ^ tmp_23_fu_667_p3);

assign xor_ln20_4_fu_783_p2 = (tmp_32_fu_775_p3 ^ tmp_1_fu_491_p3);

assign xor_ln20_50_fu_1431_p2 = (tmp_55_fu_1423_p3 ^ 1'd1);

assign xor_ln20_51_fu_1437_p2 = (xor_ln20_50_fu_1431_p2 ^ tmp_24_fu_675_p3);

assign xor_ln20_52_fu_1455_p2 = (tmp_56_fu_1447_p3 ^ 1'd1);

assign xor_ln20_53_fu_1461_p2 = (xor_ln20_52_fu_1455_p2 ^ tmp_25_fu_683_p3);

assign xor_ln20_54_fu_1491_p2 = (tmp_57_fu_1483_p3 ^ 1'd1);

assign xor_ln20_55_fu_1497_p2 = (xor_ln20_54_fu_1491_p2 ^ tmp_26_fu_691_p3);

assign xor_ln20_56_fu_1515_p2 = (tmp_58_fu_1507_p3 ^ 1'd1);

assign xor_ln20_57_fu_1521_p2 = (xor_ln20_56_fu_1515_p2 ^ tmp_27_fu_699_p3);

assign xor_ln20_58_fu_1539_p2 = (tmp_59_fu_1531_p3 ^ 1'd1);

assign xor_ln20_59_fu_1545_p2 = (xor_ln20_58_fu_1539_p2 ^ tmp_28_fu_707_p3);

assign xor_ln20_5_fu_789_p2 = (xor_ln20_4_fu_783_p2 ^ 1'd1);

assign xor_ln20_6_fu_819_p2 = (tmp_33_fu_811_p3 ^ tmp_2_fu_499_p3);

assign xor_ln20_7_fu_825_p2 = (xor_ln20_6_fu_819_p2 ^ 1'd1);

assign xor_ln20_8_fu_843_p2 = (tmp_3_fu_507_p3 ^ tmp_34_fu_835_p3);

assign xor_ln20_9_fu_849_p2 = (xor_ln20_8_fu_843_p2 ^ 1'd1);

assign xor_ln20_fu_735_p2 = (trunc_ln20_1_fu_731_p1 ^ 1'd1);

assign xor_ln36_1_fu_1581_p2 = (xor_ln36_fu_1575_p2 ^ 1'd1);

assign xor_ln36_2_fu_1599_p2 = (tmp_61_fu_1591_p3 ^ tmp_30_fu_723_p3);

assign xor_ln36_3_fu_1605_p2 = (xor_ln36_2_fu_1599_p2 ^ 1'd1);

assign xor_ln36_fu_1575_p2 = (tmp_60_fu_1567_p3 ^ tmp_29_fu_715_p3);

assign zext_ln141_fu_449_p1 = select_ln141_1_fu_437_p3;

assign zext_ln147_fu_466_p1 = add_ln147_fu_460_p2;

assign zext_ln20_10_fu_1023_p1 = xor_ln20_21_fu_1017_p2;

assign zext_ln20_11_fu_1047_p1 = xor_ln20_23_fu_1041_p2;

assign zext_ln20_12_fu_1083_p1 = xor_ln20_25_fu_1077_p2;

assign zext_ln20_13_fu_1107_p1 = xor_ln20_27_fu_1101_p2;

assign zext_ln20_14_fu_1131_p1 = xor_ln20_29_fu_1125_p2;

assign zext_ln20_15_fu_1167_p1 = xor_ln20_31_fu_1161_p2;

assign zext_ln20_16_fu_1191_p1 = xor_ln20_33_fu_1185_p2;

assign zext_ln20_17_fu_1215_p1 = xor_ln20_35_fu_1209_p2;

assign zext_ln20_18_fu_1251_p1 = xor_ln20_37_fu_1245_p2;

assign zext_ln20_19_fu_1275_p1 = xor_ln20_39_fu_1269_p2;

assign zext_ln20_1_fu_771_p1 = xor_ln20_3_fu_765_p2;

assign zext_ln20_20_fu_1299_p1 = xor_ln20_41_fu_1293_p2;

assign zext_ln20_21_fu_1335_p1 = xor_ln20_43_fu_1329_p2;

assign zext_ln20_22_fu_1359_p1 = xor_ln20_45_fu_1353_p2;

assign zext_ln20_23_fu_1383_p1 = xor_ln20_47_fu_1377_p2;

assign zext_ln20_24_fu_1419_p1 = xor_ln20_49_fu_1413_p2;

assign zext_ln20_25_fu_1443_p1 = xor_ln20_51_fu_1437_p2;

assign zext_ln20_26_fu_1467_p1 = xor_ln20_53_fu_1461_p2;

assign zext_ln20_27_fu_1503_p1 = xor_ln20_55_fu_1497_p2;

assign zext_ln20_28_fu_1527_p1 = xor_ln20_57_fu_1521_p2;

assign zext_ln20_29_fu_1551_p1 = xor_ln20_59_fu_1545_p2;

assign zext_ln20_2_fu_795_p1 = xor_ln20_5_fu_789_p2;

assign zext_ln20_3_fu_831_p1 = xor_ln20_7_fu_825_p2;

assign zext_ln20_4_fu_855_p1 = xor_ln20_9_fu_849_p2;

assign zext_ln20_5_fu_879_p1 = xor_ln20_11_fu_873_p2;

assign zext_ln20_6_fu_915_p1 = xor_ln20_13_fu_909_p2;

assign zext_ln20_7_fu_939_p1 = xor_ln20_15_fu_933_p2;

assign zext_ln20_8_fu_963_p1 = xor_ln20_17_fu_957_p2;

assign zext_ln20_9_fu_999_p1 = xor_ln20_19_fu_993_p2;

assign zext_ln20_fu_747_p1 = xor_ln20_1_fu_741_p2;

assign zext_ln36_1_fu_1611_p1 = xor_ln36_3_fu_1605_p2;

assign zext_ln36_fu_1587_p1 = xor_ln36_1_fu_1581_p2;

assign zext_ln38_10_fu_1663_p1 = s6_fu_1309_p2;

assign zext_ln38_11_fu_1667_p1 = s7_fu_1393_p2;

assign zext_ln38_12_fu_1710_p1 = add_ln38_4_reg_2092;

assign zext_ln38_13_fu_1677_p1 = s8_fu_1477_p2;

assign zext_ln38_14_fu_1681_p1 = s9_fu_1561_p2;

assign zext_ln38_15_fu_1713_p1 = add_ln38_5_reg_2097;

assign zext_ln38_16_fu_1716_p1 = s10_reg_2072;

assign zext_ln38_17_fu_1725_p1 = add_ln38_7_fu_1719_p2;

assign zext_ln38_1_fu_1625_p1 = s1_fu_889_p2;

assign zext_ln38_2_fu_1635_p1 = s2_fu_973_p2;

assign zext_ln38_3_fu_1639_p1 = s3_fu_1057_p2;

assign zext_ln38_4_fu_1691_p1 = add_ln38_reg_2077;

assign zext_ln38_5_fu_1694_p1 = add_ln38_1_reg_2082;

assign zext_ln38_6_fu_1649_p1 = s4_fu_1141_p2;

assign zext_ln38_7_fu_1653_p1 = s5_fu_1225_p2;

assign zext_ln38_8_fu_1703_p1 = add_ln38_2_fu_1697_p2;

assign zext_ln38_9_fu_1707_p1 = add_ln38_3_reg_2087;

assign zext_ln38_fu_1621_p1 = s0_fu_805_p2;

assign zext_ln40_fu_1741_p1 = add_ln38_8_fu_1735_p2;

endmodule //bnn_compute_L3_Pipeline_STREAM_L3_UPDATE_L3
