// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_compute_L2 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        l1_to_l2_dout,
        l1_to_l2_empty_n,
        l1_to_l2_read,
        l1_to_l2_num_data_valid,
        l1_to_l2_fifo_cap,
        l2_to_l3_din,
        l2_to_l3_full_n,
        l2_to_l3_write,
        l2_to_l3_num_data_valid,
        l2_to_l3_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] l1_to_l2_dout;
input   l1_to_l2_empty_n;
output   l1_to_l2_read;
input  [2:0] l1_to_l2_num_data_valid;
input  [2:0] l1_to_l2_fifo_cap;
output  [31:0] l2_to_l3_din;
input   l2_to_l3_full_n;
output   l2_to_l3_write;
input  [31:0] l2_to_l3_num_data_valid;
input  [31:0] l2_to_l3_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_start;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_done;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_idle;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_ready;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_l1_to_l2_read;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_1_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_1_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_2_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_2_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_3_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_3_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_4_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_4_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_5_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_5_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_6_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_6_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_7_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_7_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_8_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_8_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_9_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_9_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_10_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_10_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_11_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_11_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_12_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_12_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_13_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_13_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_14_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_14_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_15_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_15_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_16_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_16_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_17_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_17_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_18_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_18_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_19_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_19_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_20_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_20_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_21_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_21_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_22_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_22_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_23_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_23_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_24_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_24_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_25_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_25_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_26_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_26_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_27_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_27_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_28_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_28_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_29_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_29_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_30_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_30_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_31_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_31_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_32_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_32_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_33_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_33_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_34_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_34_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_35_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_35_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_36_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_36_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_37_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_37_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_38_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_38_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_39_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_39_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_40_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_40_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_41_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_41_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_42_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_42_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_43_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_43_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_44_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_44_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_45_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_45_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_46_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_46_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_47_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_47_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_48_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_48_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_49_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_49_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_50_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_50_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_51_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_51_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_52_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_52_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_53_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_53_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_54_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_54_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_55_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_55_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_56_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_56_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_57_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_57_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_58_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_58_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_59_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_59_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_60_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_60_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_61_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_61_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_62_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_62_load_out_ap_vld;
wire   [11:0] grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_63_load_out;
wire    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_63_load_out_ap_vld;
wire    grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_start;
wire    grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_done;
wire    grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_idle;
wire    grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_ready;
wire   [31:0] grp_compute_L2_Pipeline_PACK_L2_fu_356_l2_to_l3_din;
wire    grp_compute_L2_Pipeline_PACK_L2_fu_356_l2_to_l3_write;
reg    grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_start_reg;
reg    ap_block_state1_ignore_call66;
wire    ap_CS_fsm_state2;
reg    grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_start_reg = 1'b0;
#0 grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_start_reg = 1'b0;
end

bnn_compute_L2_Pipeline_STREAM_L2_UPDATE_L2 grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_start),
    .ap_done(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_done),
    .ap_idle(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_idle),
    .ap_ready(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_ready),
    .l1_to_l2_dout(l1_to_l2_dout),
    .l1_to_l2_empty_n(l1_to_l2_empty_n),
    .l1_to_l2_read(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_l1_to_l2_read),
    .l1_to_l2_num_data_valid(3'd0),
    .l1_to_l2_fifo_cap(3'd0),
    .acc_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_load_out),
    .acc_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_load_out_ap_vld),
    .acc_1_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_1_load_out),
    .acc_1_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_1_load_out_ap_vld),
    .acc_2_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_2_load_out),
    .acc_2_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_2_load_out_ap_vld),
    .acc_3_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_3_load_out),
    .acc_3_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_3_load_out_ap_vld),
    .acc_4_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_4_load_out),
    .acc_4_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_4_load_out_ap_vld),
    .acc_5_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_5_load_out),
    .acc_5_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_5_load_out_ap_vld),
    .acc_6_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_6_load_out),
    .acc_6_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_6_load_out_ap_vld),
    .acc_7_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_7_load_out),
    .acc_7_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_7_load_out_ap_vld),
    .acc_8_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_8_load_out),
    .acc_8_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_8_load_out_ap_vld),
    .acc_9_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_9_load_out),
    .acc_9_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_9_load_out_ap_vld),
    .acc_10_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_10_load_out),
    .acc_10_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_10_load_out_ap_vld),
    .acc_11_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_11_load_out),
    .acc_11_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_11_load_out_ap_vld),
    .acc_12_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_12_load_out),
    .acc_12_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_12_load_out_ap_vld),
    .acc_13_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_13_load_out),
    .acc_13_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_13_load_out_ap_vld),
    .acc_14_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_14_load_out),
    .acc_14_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_14_load_out_ap_vld),
    .acc_15_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_15_load_out),
    .acc_15_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_15_load_out_ap_vld),
    .acc_16_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_16_load_out),
    .acc_16_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_16_load_out_ap_vld),
    .acc_17_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_17_load_out),
    .acc_17_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_17_load_out_ap_vld),
    .acc_18_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_18_load_out),
    .acc_18_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_18_load_out_ap_vld),
    .acc_19_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_19_load_out),
    .acc_19_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_19_load_out_ap_vld),
    .acc_20_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_20_load_out),
    .acc_20_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_20_load_out_ap_vld),
    .acc_21_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_21_load_out),
    .acc_21_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_21_load_out_ap_vld),
    .acc_22_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_22_load_out),
    .acc_22_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_22_load_out_ap_vld),
    .acc_23_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_23_load_out),
    .acc_23_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_23_load_out_ap_vld),
    .acc_24_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_24_load_out),
    .acc_24_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_24_load_out_ap_vld),
    .acc_25_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_25_load_out),
    .acc_25_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_25_load_out_ap_vld),
    .acc_26_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_26_load_out),
    .acc_26_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_26_load_out_ap_vld),
    .acc_27_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_27_load_out),
    .acc_27_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_27_load_out_ap_vld),
    .acc_28_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_28_load_out),
    .acc_28_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_28_load_out_ap_vld),
    .acc_29_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_29_load_out),
    .acc_29_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_29_load_out_ap_vld),
    .acc_30_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_30_load_out),
    .acc_30_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_30_load_out_ap_vld),
    .acc_31_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_31_load_out),
    .acc_31_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_31_load_out_ap_vld),
    .acc_32_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_32_load_out),
    .acc_32_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_32_load_out_ap_vld),
    .acc_33_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_33_load_out),
    .acc_33_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_33_load_out_ap_vld),
    .acc_34_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_34_load_out),
    .acc_34_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_34_load_out_ap_vld),
    .acc_35_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_35_load_out),
    .acc_35_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_35_load_out_ap_vld),
    .acc_36_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_36_load_out),
    .acc_36_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_36_load_out_ap_vld),
    .acc_37_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_37_load_out),
    .acc_37_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_37_load_out_ap_vld),
    .acc_38_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_38_load_out),
    .acc_38_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_38_load_out_ap_vld),
    .acc_39_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_39_load_out),
    .acc_39_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_39_load_out_ap_vld),
    .acc_40_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_40_load_out),
    .acc_40_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_40_load_out_ap_vld),
    .acc_41_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_41_load_out),
    .acc_41_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_41_load_out_ap_vld),
    .acc_42_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_42_load_out),
    .acc_42_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_42_load_out_ap_vld),
    .acc_43_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_43_load_out),
    .acc_43_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_43_load_out_ap_vld),
    .acc_44_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_44_load_out),
    .acc_44_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_44_load_out_ap_vld),
    .acc_45_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_45_load_out),
    .acc_45_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_45_load_out_ap_vld),
    .acc_46_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_46_load_out),
    .acc_46_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_46_load_out_ap_vld),
    .acc_47_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_47_load_out),
    .acc_47_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_47_load_out_ap_vld),
    .acc_48_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_48_load_out),
    .acc_48_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_48_load_out_ap_vld),
    .acc_49_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_49_load_out),
    .acc_49_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_49_load_out_ap_vld),
    .acc_50_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_50_load_out),
    .acc_50_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_50_load_out_ap_vld),
    .acc_51_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_51_load_out),
    .acc_51_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_51_load_out_ap_vld),
    .acc_52_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_52_load_out),
    .acc_52_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_52_load_out_ap_vld),
    .acc_53_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_53_load_out),
    .acc_53_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_53_load_out_ap_vld),
    .acc_54_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_54_load_out),
    .acc_54_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_54_load_out_ap_vld),
    .acc_55_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_55_load_out),
    .acc_55_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_55_load_out_ap_vld),
    .acc_56_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_56_load_out),
    .acc_56_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_56_load_out_ap_vld),
    .acc_57_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_57_load_out),
    .acc_57_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_57_load_out_ap_vld),
    .acc_58_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_58_load_out),
    .acc_58_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_58_load_out_ap_vld),
    .acc_59_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_59_load_out),
    .acc_59_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_59_load_out_ap_vld),
    .acc_60_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_60_load_out),
    .acc_60_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_60_load_out_ap_vld),
    .acc_61_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_61_load_out),
    .acc_61_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_61_load_out_ap_vld),
    .acc_62_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_62_load_out),
    .acc_62_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_62_load_out_ap_vld),
    .acc_63_load_out(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_63_load_out),
    .acc_63_load_out_ap_vld(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_63_load_out_ap_vld)
);

bnn_compute_L2_Pipeline_PACK_L2 grp_compute_L2_Pipeline_PACK_L2_fu_356(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_start),
    .ap_done(grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_done),
    .ap_idle(grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_idle),
    .ap_ready(grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_ready),
    .l2_to_l3_din(grp_compute_L2_Pipeline_PACK_L2_fu_356_l2_to_l3_din),
    .l2_to_l3_full_n(l2_to_l3_full_n),
    .l2_to_l3_write(grp_compute_L2_Pipeline_PACK_L2_fu_356_l2_to_l3_write),
    .l2_to_l3_num_data_valid(l2_to_l3_num_data_valid),
    .l2_to_l3_fifo_cap(l2_to_l3_fifo_cap),
    .acc_32_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_32_load_out),
    .acc_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_load_out),
    .acc_33_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_33_load_out),
    .acc_1_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_1_load_out),
    .acc_34_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_34_load_out),
    .acc_2_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_2_load_out),
    .acc_35_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_35_load_out),
    .acc_3_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_3_load_out),
    .acc_36_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_36_load_out),
    .acc_4_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_4_load_out),
    .acc_37_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_37_load_out),
    .acc_5_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_5_load_out),
    .acc_38_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_38_load_out),
    .acc_6_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_6_load_out),
    .acc_39_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_39_load_out),
    .acc_7_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_7_load_out),
    .acc_40_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_40_load_out),
    .acc_8_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_8_load_out),
    .acc_41_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_41_load_out),
    .acc_9_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_9_load_out),
    .acc_42_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_42_load_out),
    .acc_10_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_10_load_out),
    .acc_43_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_43_load_out),
    .acc_11_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_11_load_out),
    .acc_44_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_44_load_out),
    .acc_12_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_12_load_out),
    .acc_45_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_45_load_out),
    .acc_13_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_13_load_out),
    .acc_46_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_46_load_out),
    .acc_14_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_14_load_out),
    .acc_47_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_47_load_out),
    .acc_15_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_15_load_out),
    .acc_48_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_48_load_out),
    .acc_16_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_16_load_out),
    .acc_49_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_49_load_out),
    .acc_17_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_17_load_out),
    .acc_50_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_50_load_out),
    .acc_18_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_18_load_out),
    .acc_51_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_51_load_out),
    .acc_19_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_19_load_out),
    .acc_52_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_52_load_out),
    .acc_20_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_20_load_out),
    .acc_53_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_53_load_out),
    .acc_21_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_21_load_out),
    .acc_54_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_54_load_out),
    .acc_22_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_22_load_out),
    .acc_55_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_55_load_out),
    .acc_23_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_23_load_out),
    .acc_56_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_56_load_out),
    .acc_24_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_24_load_out),
    .acc_57_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_57_load_out),
    .acc_25_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_25_load_out),
    .acc_58_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_58_load_out),
    .acc_26_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_26_load_out),
    .acc_59_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_59_load_out),
    .acc_27_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_27_load_out),
    .acc_60_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_60_load_out),
    .acc_28_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_28_load_out),
    .acc_61_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_61_load_out),
    .acc_29_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_29_load_out),
    .acc_62_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_62_load_out),
    .acc_30_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_30_load_out),
    .acc_63_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_63_load_out),
    .acc_31_load_reload(grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_acc_31_load_out)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_start_reg <= 1'b1;
        end else if ((grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_ready == 1'b1)) begin
            grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call66) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_start_reg <= 1'b1;
        end else if ((grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_ready == 1'b1)) begin
            grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call66 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_start = grp_compute_L2_Pipeline_PACK_L2_fu_356_ap_start_reg;

assign grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_start = grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_ap_start_reg;

assign l1_to_l2_read = grp_compute_L2_Pipeline_STREAM_L2_UPDATE_L2_fu_282_l1_to_l2_read;

assign l2_to_l3_din = grp_compute_L2_Pipeline_PACK_L2_fu_356_l2_to_l3_din;

assign l2_to_l3_write = grp_compute_L2_Pipeline_PACK_L2_fu_356_l2_to_l3_write;

assign start_out = real_start;

endmodule //bnn_compute_L2
