// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_compute_L3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        l2_to_l3_dout,
        l2_to_l3_empty_n,
        l2_to_l3_read,
        l2_to_l3_num_data_valid,
        l2_to_l3_fifo_cap,
        out_r_TDATA,
        out_r_TVALID,
        out_r_TREADY,
        out_r_TKEEP,
        out_r_TSTRB,
        out_r_TLAST
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] l2_to_l3_dout;
input   l2_to_l3_empty_n;
output   l2_to_l3_read;
input  [2:0] l2_to_l3_num_data_valid;
input  [2:0] l2_to_l3_fifo_cap;
output  [31:0] out_r_TDATA;
output   out_r_TVALID;
input   out_r_TREADY;
output  [3:0] out_r_TKEEP;
output  [3:0] out_r_TSTRB;
output  [0:0] out_r_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_start;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_done;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_idle;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_ready;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_l2_to_l3_read;
wire   [11:0] grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_load_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_load_out_ap_vld;
wire   [11:0] grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_1_load_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_1_load_out_ap_vld;
wire   [11:0] grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_2_load_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_2_load_out_ap_vld;
wire   [11:0] grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_3_load_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_3_load_out_ap_vld;
wire   [11:0] grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_4_load_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_4_load_out_ap_vld;
wire   [11:0] grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_5_load_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_5_load_out_ap_vld;
wire   [11:0] grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_6_load_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_6_load_out_ap_vld;
wire   [11:0] grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_7_load_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_7_load_out_ap_vld;
wire   [11:0] grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_8_load_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_8_load_out_ap_vld;
wire   [11:0] grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_9_load_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_9_load_out_ap_vld;
wire    grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_start;
wire    grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_done;
wire    grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_idle;
wire    grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_ready;
wire    grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TREADY;
wire   [31:0] grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TDATA;
wire    grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID;
wire   [3:0] grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TKEEP;
wire   [3:0] grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TSTRB;
wire   [0:0] grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TLAST;
reg    grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_start_reg;
reg    ap_block_state1_ignore_call13;
wire    ap_CS_fsm_state2;
reg    grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] out_r_TDATA_reg;
reg   [3:0] out_r_TKEEP_reg;
reg   [3:0] out_r_TSTRB_reg;
reg   [0:0] out_r_TLAST_reg;
wire    ap_CS_fsm_state5;
wire    regslice_both_out_r_V_data_V_U_apdone_blk;
reg   [4:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg   [31:0] out_r_TDATA_int_regslice;
wire    out_r_TVALID_int_regslice;
wire    out_r_TREADY_int_regslice;
wire    regslice_both_out_r_V_data_V_U_vld_out;
wire    regslice_both_out_r_V_keep_V_U_apdone_blk;
reg   [3:0] out_r_TKEEP_int_regslice;
wire    regslice_both_out_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_r_V_keep_V_U_vld_out;
wire    regslice_both_out_r_V_strb_V_U_apdone_blk;
reg   [3:0] out_r_TSTRB_int_regslice;
wire    regslice_both_out_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_r_V_strb_V_U_vld_out;
wire    regslice_both_out_r_V_last_V_U_apdone_blk;
reg   [0:0] out_r_TLAST_int_regslice;
wire    regslice_both_out_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_r_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_start_reg = 1'b0;
#0 grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_start_reg = 1'b0;
end

bnn_compute_L3_Pipeline_STREAM_L3_UPDATE_L3 grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_start),
    .ap_done(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_done),
    .ap_idle(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_idle),
    .ap_ready(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_ready),
    .l2_to_l3_dout(l2_to_l3_dout),
    .l2_to_l3_empty_n(l2_to_l3_empty_n),
    .l2_to_l3_read(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_l2_to_l3_read),
    .l2_to_l3_num_data_valid(3'd0),
    .l2_to_l3_fifo_cap(3'd0),
    .acc_load_out(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_load_out),
    .acc_load_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_load_out_ap_vld),
    .acc_1_load_out(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_1_load_out),
    .acc_1_load_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_1_load_out_ap_vld),
    .acc_2_load_out(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_2_load_out),
    .acc_2_load_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_2_load_out_ap_vld),
    .acc_3_load_out(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_3_load_out),
    .acc_3_load_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_3_load_out_ap_vld),
    .acc_4_load_out(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_4_load_out),
    .acc_4_load_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_4_load_out_ap_vld),
    .acc_5_load_out(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_5_load_out),
    .acc_5_load_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_5_load_out_ap_vld),
    .acc_6_load_out(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_6_load_out),
    .acc_6_load_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_6_load_out_ap_vld),
    .acc_7_load_out(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_7_load_out),
    .acc_7_load_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_7_load_out_ap_vld),
    .acc_8_load_out(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_8_load_out),
    .acc_8_load_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_8_load_out_ap_vld),
    .acc_9_load_out(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_9_load_out),
    .acc_9_load_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_9_load_out_ap_vld)
);

bnn_compute_L3_Pipeline_WRITE_L3 grp_compute_L3_Pipeline_WRITE_L3_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_start),
    .ap_done(grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_done),
    .ap_idle(grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_idle),
    .ap_ready(grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_ready),
    .out_r_TREADY(grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TREADY),
    .acc_load_reload(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_load_out),
    .acc_1_load_reload(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_1_load_out),
    .acc_2_load_reload(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_2_load_out),
    .acc_3_load_reload(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_3_load_out),
    .acc_4_load_reload(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_4_load_out),
    .acc_5_load_reload(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_5_load_out),
    .acc_6_load_reload(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_6_load_out),
    .acc_7_load_reload(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_7_load_out),
    .acc_8_load_reload(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_8_load_out),
    .acc_9_load_reload(grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_acc_9_load_out),
    .out_r_TDATA(grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TDATA),
    .out_r_TVALID(grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID),
    .out_r_TKEEP(grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TKEEP),
    .out_r_TSTRB(grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TSTRB),
    .out_r_TLAST(grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TLAST)
);

bnn_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_r_TDATA_int_regslice),
    .vld_in(grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID),
    .ack_in(out_r_TREADY_int_regslice),
    .data_out(out_r_TDATA),
    .vld_out(regslice_both_out_r_V_data_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_data_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_r_TKEEP_int_regslice),
    .vld_in(grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID),
    .ack_in(regslice_both_out_r_V_keep_V_U_ack_in_dummy),
    .data_out(out_r_TKEEP),
    .vld_out(regslice_both_out_r_V_keep_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_keep_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_r_TSTRB_int_regslice),
    .vld_in(grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID),
    .ack_in(regslice_both_out_r_V_strb_V_U_ack_in_dummy),
    .data_out(out_r_TSTRB),
    .vld_out(regslice_both_out_r_V_strb_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_strb_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_r_TLAST_int_regslice),
    .vld_in(grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID),
    .ack_in(regslice_both_out_r_V_last_V_U_ack_in_dummy),
    .data_out(out_r_TLAST),
    .vld_out(regslice_both_out_r_V_last_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (regslice_both_out_r_V_data_V_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call13) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_start_reg <= 1'b1;
        end else if ((grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_ready == 1'b1)) begin
            grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_ready == 1'b1)) begin
            grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_TDATA_reg <= grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TDATA;
        out_r_TKEEP_reg <= grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TKEEP;
        out_r_TLAST_reg <= grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TLAST;
        out_r_TSTRB_reg <= grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TSTRB;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_r_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (regslice_both_out_r_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (regslice_both_out_r_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_TDATA_int_regslice = grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TDATA;
    end else begin
        out_r_TDATA_int_regslice = out_r_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_TKEEP_int_regslice = grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TKEEP;
    end else begin
        out_r_TKEEP_int_regslice = out_r_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_TLAST_int_regslice = grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TLAST;
    end else begin
        out_r_TLAST_int_regslice = out_r_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_TSTRB_int_regslice = grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TSTRB;
    end else begin
        out_r_TSTRB_int_regslice = out_r_TSTRB_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (regslice_both_out_r_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call13 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_start = grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_ap_start_reg;

assign grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_start = grp_compute_L3_Pipeline_WRITE_L3_fu_100_ap_start_reg;

assign grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TREADY = (out_r_TREADY_int_regslice & ap_CS_fsm_state4);

assign l2_to_l3_read = grp_compute_L3_Pipeline_STREAM_L3_UPDATE_L3_fu_82_l2_to_l3_read;

assign out_r_TVALID = regslice_both_out_r_V_data_V_U_vld_out;

assign out_r_TVALID_int_regslice = grp_compute_L3_Pipeline_WRITE_L3_fu_100_out_r_TVALID;

endmodule //bnn_compute_L3
