# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/linux/ieng6/students/162/mak025/chole_bhature/project_files/project3/Q9/dft_1024/dft_1024.srcs/sources_1/bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_us_1/design_dft_1024_axi_mem_intercon_imp_auto_us_1.xci
# IP: The module: 'design_dft_1024_axi_mem_intercon_imp_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/linux/ieng6/students/162/mak025/chole_bhature/project_files/project3/Q9/dft_1024/dft_1024.gen/sources_1/bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_us_1/design_dft_1024_axi_mem_intercon_imp_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_1024_axi_mem_intercon_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/linux/ieng6/students/162/mak025/chole_bhature/project_files/project3/Q9/dft_1024/dft_1024.gen/sources_1/bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_us_1/design_dft_1024_axi_mem_intercon_imp_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_1024_axi_mem_intercon_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/linux/ieng6/students/162/mak025/chole_bhature/project_files/project3/Q9/dft_1024/dft_1024.srcs/sources_1/bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_us_1/design_dft_1024_axi_mem_intercon_imp_auto_us_1.xci
# IP: The module: 'design_dft_1024_axi_mem_intercon_imp_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/linux/ieng6/students/162/mak025/chole_bhature/project_files/project3/Q9/dft_1024/dft_1024.gen/sources_1/bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_us_1/design_dft_1024_axi_mem_intercon_imp_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_1024_axi_mem_intercon_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/linux/ieng6/students/162/mak025/chole_bhature/project_files/project3/Q9/dft_1024/dft_1024.gen/sources_1/bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_us_1/design_dft_1024_axi_mem_intercon_imp_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_1024_axi_mem_intercon_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
