// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dft_dft,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=1050654,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=2335,HLS_SYN_LUT=3768,HLS_VERSION=2024_2}" *)

module dft (
        ap_clk,
        ap_rst_n,
        real_sample_stream_TDATA,
        real_sample_stream_TVALID,
        real_sample_stream_TREADY,
        real_sample_stream_TKEEP,
        real_sample_stream_TSTRB,
        real_sample_stream_TLAST,
        imag_sample_stream_TDATA,
        imag_sample_stream_TVALID,
        imag_sample_stream_TREADY,
        imag_sample_stream_TKEEP,
        imag_sample_stream_TSTRB,
        imag_sample_stream_TLAST,
        real_op_stream_TDATA,
        real_op_stream_TVALID,
        real_op_stream_TREADY,
        real_op_stream_TKEEP,
        real_op_stream_TSTRB,
        real_op_stream_TLAST,
        imag_op_stream_TDATA,
        imag_op_stream_TVALID,
        imag_op_stream_TREADY,
        imag_op_stream_TKEEP,
        imag_op_stream_TSTRB,
        imag_op_stream_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] real_sample_stream_TDATA;
input   real_sample_stream_TVALID;
output   real_sample_stream_TREADY;
input  [3:0] real_sample_stream_TKEEP;
input  [3:0] real_sample_stream_TSTRB;
input  [0:0] real_sample_stream_TLAST;
input  [31:0] imag_sample_stream_TDATA;
input   imag_sample_stream_TVALID;
output   imag_sample_stream_TREADY;
input  [3:0] imag_sample_stream_TKEEP;
input  [3:0] imag_sample_stream_TSTRB;
input  [0:0] imag_sample_stream_TLAST;
output  [31:0] real_op_stream_TDATA;
output   real_op_stream_TVALID;
input   real_op_stream_TREADY;
output  [3:0] real_op_stream_TKEEP;
output  [3:0] real_op_stream_TSTRB;
output  [0:0] real_op_stream_TLAST;
output  [31:0] imag_op_stream_TDATA;
output   imag_op_stream_TVALID;
input   imag_op_stream_TREADY;
output  [3:0] imag_op_stream_TKEEP;
output  [3:0] imag_op_stream_TSTRB;
output  [0:0] imag_op_stream_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [9:0] real_sample_address0;
reg    real_sample_ce0;
reg    real_sample_we0;
wire   [31:0] real_sample_q0;
reg   [9:0] imag_sample_address0;
reg    imag_sample_ce0;
reg    imag_sample_we0;
wire   [31:0] imag_sample_q0;
reg   [9:0] real_op_address0;
reg    real_op_ce0;
reg    real_op_we0;
reg   [31:0] real_op_d0;
wire   [31:0] real_op_q0;
reg    real_op_ce1;
wire   [31:0] real_op_q1;
reg   [9:0] imag_op_address0;
reg    imag_op_ce0;
reg    imag_op_we0;
reg   [31:0] imag_op_d0;
wire   [31:0] imag_op_q0;
reg    imag_op_ce1;
wire   [31:0] imag_op_q1;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_start;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_done;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_idle;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_ready;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_we0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_d0;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_we0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_d0;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_stream_TREADY;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_stream_TREADY;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_we0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_d0;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_we0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_d0;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_start;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_done;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_idle;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_ready;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_sample_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_sample_ce0;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_sample_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_sample_ce0;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_we0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_d0;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_address1;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_ce1;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_we0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_d0;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_address1;
wire    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_ce1;
wire    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_start;
wire    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_done;
wire    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_idle;
wire    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_ready;
wire    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TREADY;
wire    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TREADY;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_ce0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TDATA;
wire    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID;
wire   [3:0] grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TKEEP;
wire   [3:0] grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TSTRB;
wire   [0:0] grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TLAST;
wire   [9:0] grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_ce0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TDATA;
wire    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID;
wire   [3:0] grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TKEEP;
wire   [3:0] grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TSTRB;
wire   [0:0] grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TLAST;
reg    grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [31:0] real_op_stream_TDATA_reg;
reg   [3:0] real_op_stream_TKEEP_reg;
reg   [3:0] real_op_stream_TSTRB_reg;
reg   [0:0] real_op_stream_TLAST_reg;
reg   [31:0] imag_op_stream_TDATA_reg;
reg   [3:0] imag_op_stream_TKEEP_reg;
reg   [3:0] imag_op_stream_TSTRB_reg;
reg   [0:0] imag_op_stream_TLAST_reg;
wire    ap_CS_fsm_state8;
wire    regslice_both_real_op_stream_V_data_V_U_apdone_blk;
wire    regslice_both_imag_op_stream_V_data_V_U_apdone_blk;
reg    ap_block_state8;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_both_real_sample_stream_V_data_V_U_apdone_blk;
wire   [31:0] real_sample_stream_TDATA_int_regslice;
wire    real_sample_stream_TVALID_int_regslice;
reg    real_sample_stream_TREADY_int_regslice;
wire    regslice_both_real_sample_stream_V_data_V_U_ack_in;
wire    regslice_both_real_sample_stream_V_keep_V_U_apdone_blk;
wire   [3:0] real_sample_stream_TKEEP_int_regslice;
wire    regslice_both_real_sample_stream_V_keep_V_U_vld_out;
wire    regslice_both_real_sample_stream_V_keep_V_U_ack_in;
wire    regslice_both_real_sample_stream_V_strb_V_U_apdone_blk;
wire   [3:0] real_sample_stream_TSTRB_int_regslice;
wire    regslice_both_real_sample_stream_V_strb_V_U_vld_out;
wire    regslice_both_real_sample_stream_V_strb_V_U_ack_in;
wire    regslice_both_real_sample_stream_V_last_V_U_apdone_blk;
wire   [0:0] real_sample_stream_TLAST_int_regslice;
wire    regslice_both_real_sample_stream_V_last_V_U_vld_out;
wire    regslice_both_real_sample_stream_V_last_V_U_ack_in;
wire    regslice_both_imag_sample_stream_V_data_V_U_apdone_blk;
wire   [31:0] imag_sample_stream_TDATA_int_regslice;
wire    imag_sample_stream_TVALID_int_regslice;
reg    imag_sample_stream_TREADY_int_regslice;
wire    regslice_both_imag_sample_stream_V_data_V_U_ack_in;
wire    regslice_both_imag_sample_stream_V_keep_V_U_apdone_blk;
wire   [3:0] imag_sample_stream_TKEEP_int_regslice;
wire    regslice_both_imag_sample_stream_V_keep_V_U_vld_out;
wire    regslice_both_imag_sample_stream_V_keep_V_U_ack_in;
wire    regslice_both_imag_sample_stream_V_strb_V_U_apdone_blk;
wire   [3:0] imag_sample_stream_TSTRB_int_regslice;
wire    regslice_both_imag_sample_stream_V_strb_V_U_vld_out;
wire    regslice_both_imag_sample_stream_V_strb_V_U_ack_in;
wire    regslice_both_imag_sample_stream_V_last_V_U_apdone_blk;
wire   [0:0] imag_sample_stream_TLAST_int_regslice;
wire    regslice_both_imag_sample_stream_V_last_V_U_vld_out;
wire    regslice_both_imag_sample_stream_V_last_V_U_ack_in;
reg   [31:0] real_op_stream_TDATA_int_regslice;
wire    real_op_stream_TVALID_int_regslice;
wire    real_op_stream_TREADY_int_regslice;
wire    regslice_both_real_op_stream_V_data_V_U_vld_out;
wire    regslice_both_real_op_stream_V_keep_V_U_apdone_blk;
reg   [3:0] real_op_stream_TKEEP_int_regslice;
wire    regslice_both_real_op_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_real_op_stream_V_keep_V_U_vld_out;
wire    regslice_both_real_op_stream_V_strb_V_U_apdone_blk;
reg   [3:0] real_op_stream_TSTRB_int_regslice;
wire    regslice_both_real_op_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_real_op_stream_V_strb_V_U_vld_out;
wire    regslice_both_real_op_stream_V_last_V_U_apdone_blk;
reg   [0:0] real_op_stream_TLAST_int_regslice;
wire    regslice_both_real_op_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_real_op_stream_V_last_V_U_vld_out;
reg   [31:0] imag_op_stream_TDATA_int_regslice;
wire    imag_op_stream_TVALID_int_regslice;
wire    imag_op_stream_TREADY_int_regslice;
wire    regslice_both_imag_op_stream_V_data_V_U_vld_out;
wire    regslice_both_imag_op_stream_V_keep_V_U_apdone_blk;
reg   [3:0] imag_op_stream_TKEEP_int_regslice;
wire    regslice_both_imag_op_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_imag_op_stream_V_keep_V_U_vld_out;
wire    regslice_both_imag_op_stream_V_strb_V_U_apdone_blk;
reg   [3:0] imag_op_stream_TSTRB_int_regslice;
wire    regslice_both_imag_op_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_imag_op_stream_V_strb_V_U_vld_out;
wire    regslice_both_imag_op_stream_V_last_V_U_apdone_blk;
reg   [0:0] imag_op_stream_TLAST_int_regslice;
wire    regslice_both_imag_op_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_imag_op_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_start_reg = 1'b0;
#0 grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_start_reg = 1'b0;
#0 grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_start_reg = 1'b0;
end

dft_real_sample_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
real_sample_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(real_sample_address0),
    .ce0(real_sample_ce0),
    .we0(real_sample_we0),
    .d0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_d0),
    .q0(real_sample_q0)
);

dft_real_sample_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
imag_sample_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(imag_sample_address0),
    .ce0(imag_sample_ce0),
    .we0(imag_sample_we0),
    .d0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_d0),
    .q0(imag_sample_q0)
);

dft_real_op_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
real_op_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(real_op_address0),
    .ce0(real_op_ce0),
    .we0(real_op_we0),
    .d0(real_op_d0),
    .q0(real_op_q0),
    .address1(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_address1),
    .ce1(real_op_ce1),
    .q1(real_op_q1)
);

dft_real_op_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
imag_op_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(imag_op_address0),
    .ce0(imag_op_ce0),
    .we0(imag_op_we0),
    .d0(imag_op_d0),
    .q0(imag_op_q0),
    .address1(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_address1),
    .ce1(imag_op_ce1),
    .q1(imag_op_q1)
);

dft_dft_Pipeline_VITIS_LOOP_25_1 grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_start),
    .ap_done(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_done),
    .ap_idle(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_idle),
    .ap_ready(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_ready),
    .real_sample_stream_TVALID(real_sample_stream_TVALID_int_regslice),
    .imag_sample_stream_TVALID(imag_sample_stream_TVALID_int_regslice),
    .real_op_address0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_address0),
    .real_op_ce0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_ce0),
    .real_op_we0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_we0),
    .real_op_d0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_d0),
    .imag_op_address0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_address0),
    .imag_op_ce0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_ce0),
    .imag_op_we0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_we0),
    .imag_op_d0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_d0),
    .real_sample_stream_TDATA(real_sample_stream_TDATA_int_regslice),
    .real_sample_stream_TREADY(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_stream_TREADY),
    .real_sample_stream_TKEEP(real_sample_stream_TKEEP_int_regslice),
    .real_sample_stream_TSTRB(real_sample_stream_TSTRB_int_regslice),
    .real_sample_stream_TLAST(real_sample_stream_TLAST_int_regslice),
    .imag_sample_stream_TDATA(imag_sample_stream_TDATA_int_regslice),
    .imag_sample_stream_TREADY(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_stream_TREADY),
    .imag_sample_stream_TKEEP(imag_sample_stream_TKEEP_int_regslice),
    .imag_sample_stream_TSTRB(imag_sample_stream_TSTRB_int_regslice),
    .imag_sample_stream_TLAST(imag_sample_stream_TLAST_int_regslice),
    .real_sample_address0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_address0),
    .real_sample_ce0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_ce0),
    .real_sample_we0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_we0),
    .real_sample_d0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_d0),
    .imag_sample_address0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_address0),
    .imag_sample_ce0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_ce0),
    .imag_sample_we0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_we0),
    .imag_sample_d0(grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_d0)
);

dft_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3 grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_start),
    .ap_done(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_done),
    .ap_idle(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_idle),
    .ap_ready(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_ready),
    .real_sample_address0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_sample_address0),
    .real_sample_ce0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_sample_ce0),
    .real_sample_q0(real_sample_q0),
    .imag_sample_address0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_sample_address0),
    .imag_sample_ce0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_sample_ce0),
    .imag_sample_q0(imag_sample_q0),
    .real_op_address0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_address0),
    .real_op_ce0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_ce0),
    .real_op_we0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_we0),
    .real_op_d0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_d0),
    .real_op_address1(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_address1),
    .real_op_ce1(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_ce1),
    .real_op_q1(real_op_q1),
    .imag_op_address0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_address0),
    .imag_op_ce0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_ce0),
    .imag_op_we0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_we0),
    .imag_op_d0(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_d0),
    .imag_op_address1(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_address1),
    .imag_op_ce1(grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_ce1),
    .imag_op_q1(imag_op_q1)
);

dft_dft_Pipeline_VITIS_LOOP_50_4 grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_start),
    .ap_done(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_done),
    .ap_idle(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_idle),
    .ap_ready(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_ready),
    .real_op_stream_TREADY(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TREADY),
    .imag_op_stream_TREADY(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TREADY),
    .real_op_address0(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_address0),
    .real_op_ce0(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_ce0),
    .real_op_q0(real_op_q0),
    .real_op_stream_TDATA(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TDATA),
    .real_op_stream_TVALID(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID),
    .real_op_stream_TKEEP(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TKEEP),
    .real_op_stream_TSTRB(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TSTRB),
    .real_op_stream_TLAST(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TLAST),
    .imag_op_address0(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_address0),
    .imag_op_ce0(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_ce0),
    .imag_op_q0(imag_op_q0),
    .imag_op_stream_TDATA(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TDATA),
    .imag_op_stream_TVALID(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID),
    .imag_op_stream_TKEEP(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TKEEP),
    .imag_op_stream_TSTRB(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TSTRB),
    .imag_op_stream_TLAST(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TLAST)
);

dft_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

dft_regslice_both #(
    .DataWidth( 32 ))
regslice_both_real_sample_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_sample_stream_TDATA),
    .vld_in(real_sample_stream_TVALID),
    .ack_in(regslice_both_real_sample_stream_V_data_V_U_ack_in),
    .data_out(real_sample_stream_TDATA_int_regslice),
    .vld_out(real_sample_stream_TVALID_int_regslice),
    .ack_out(real_sample_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_real_sample_stream_V_data_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 4 ))
regslice_both_real_sample_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_sample_stream_TKEEP),
    .vld_in(real_sample_stream_TVALID),
    .ack_in(regslice_both_real_sample_stream_V_keep_V_U_ack_in),
    .data_out(real_sample_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_real_sample_stream_V_keep_V_U_vld_out),
    .ack_out(real_sample_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_real_sample_stream_V_keep_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 4 ))
regslice_both_real_sample_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_sample_stream_TSTRB),
    .vld_in(real_sample_stream_TVALID),
    .ack_in(regslice_both_real_sample_stream_V_strb_V_U_ack_in),
    .data_out(real_sample_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_real_sample_stream_V_strb_V_U_vld_out),
    .ack_out(real_sample_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_real_sample_stream_V_strb_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 1 ))
regslice_both_real_sample_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_sample_stream_TLAST),
    .vld_in(real_sample_stream_TVALID),
    .ack_in(regslice_both_real_sample_stream_V_last_V_U_ack_in),
    .data_out(real_sample_stream_TLAST_int_regslice),
    .vld_out(regslice_both_real_sample_stream_V_last_V_U_vld_out),
    .ack_out(real_sample_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_real_sample_stream_V_last_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 32 ))
regslice_both_imag_sample_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_sample_stream_TDATA),
    .vld_in(imag_sample_stream_TVALID),
    .ack_in(regslice_both_imag_sample_stream_V_data_V_U_ack_in),
    .data_out(imag_sample_stream_TDATA_int_regslice),
    .vld_out(imag_sample_stream_TVALID_int_regslice),
    .ack_out(imag_sample_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_imag_sample_stream_V_data_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 4 ))
regslice_both_imag_sample_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_sample_stream_TKEEP),
    .vld_in(imag_sample_stream_TVALID),
    .ack_in(regslice_both_imag_sample_stream_V_keep_V_U_ack_in),
    .data_out(imag_sample_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_imag_sample_stream_V_keep_V_U_vld_out),
    .ack_out(imag_sample_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_imag_sample_stream_V_keep_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 4 ))
regslice_both_imag_sample_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_sample_stream_TSTRB),
    .vld_in(imag_sample_stream_TVALID),
    .ack_in(regslice_both_imag_sample_stream_V_strb_V_U_ack_in),
    .data_out(imag_sample_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_imag_sample_stream_V_strb_V_U_vld_out),
    .ack_out(imag_sample_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_imag_sample_stream_V_strb_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 1 ))
regslice_both_imag_sample_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_sample_stream_TLAST),
    .vld_in(imag_sample_stream_TVALID),
    .ack_in(regslice_both_imag_sample_stream_V_last_V_U_ack_in),
    .data_out(imag_sample_stream_TLAST_int_regslice),
    .vld_out(regslice_both_imag_sample_stream_V_last_V_U_vld_out),
    .ack_out(imag_sample_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_imag_sample_stream_V_last_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 32 ))
regslice_both_real_op_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_op_stream_TDATA_int_regslice),
    .vld_in(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID),
    .ack_in(real_op_stream_TREADY_int_regslice),
    .data_out(real_op_stream_TDATA),
    .vld_out(regslice_both_real_op_stream_V_data_V_U_vld_out),
    .ack_out(real_op_stream_TREADY),
    .apdone_blk(regslice_both_real_op_stream_V_data_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 4 ))
regslice_both_real_op_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_op_stream_TKEEP_int_regslice),
    .vld_in(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID),
    .ack_in(regslice_both_real_op_stream_V_keep_V_U_ack_in_dummy),
    .data_out(real_op_stream_TKEEP),
    .vld_out(regslice_both_real_op_stream_V_keep_V_U_vld_out),
    .ack_out(real_op_stream_TREADY),
    .apdone_blk(regslice_both_real_op_stream_V_keep_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 4 ))
regslice_both_real_op_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_op_stream_TSTRB_int_regslice),
    .vld_in(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID),
    .ack_in(regslice_both_real_op_stream_V_strb_V_U_ack_in_dummy),
    .data_out(real_op_stream_TSTRB),
    .vld_out(regslice_both_real_op_stream_V_strb_V_U_vld_out),
    .ack_out(real_op_stream_TREADY),
    .apdone_blk(regslice_both_real_op_stream_V_strb_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 1 ))
regslice_both_real_op_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(real_op_stream_TLAST_int_regslice),
    .vld_in(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID),
    .ack_in(regslice_both_real_op_stream_V_last_V_U_ack_in_dummy),
    .data_out(real_op_stream_TLAST),
    .vld_out(regslice_both_real_op_stream_V_last_V_U_vld_out),
    .ack_out(real_op_stream_TREADY),
    .apdone_blk(regslice_both_real_op_stream_V_last_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 32 ))
regslice_both_imag_op_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_op_stream_TDATA_int_regslice),
    .vld_in(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID),
    .ack_in(imag_op_stream_TREADY_int_regslice),
    .data_out(imag_op_stream_TDATA),
    .vld_out(regslice_both_imag_op_stream_V_data_V_U_vld_out),
    .ack_out(imag_op_stream_TREADY),
    .apdone_blk(regslice_both_imag_op_stream_V_data_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 4 ))
regslice_both_imag_op_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_op_stream_TKEEP_int_regslice),
    .vld_in(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID),
    .ack_in(regslice_both_imag_op_stream_V_keep_V_U_ack_in_dummy),
    .data_out(imag_op_stream_TKEEP),
    .vld_out(regslice_both_imag_op_stream_V_keep_V_U_vld_out),
    .ack_out(imag_op_stream_TREADY),
    .apdone_blk(regslice_both_imag_op_stream_V_keep_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 4 ))
regslice_both_imag_op_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_op_stream_TSTRB_int_regslice),
    .vld_in(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID),
    .ack_in(regslice_both_imag_op_stream_V_strb_V_U_ack_in_dummy),
    .data_out(imag_op_stream_TSTRB),
    .vld_out(regslice_both_imag_op_stream_V_strb_V_U_vld_out),
    .ack_out(imag_op_stream_TREADY),
    .apdone_blk(regslice_both_imag_op_stream_V_strb_V_U_apdone_blk)
);

dft_regslice_both #(
    .DataWidth( 1 ))
regslice_both_imag_op_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(imag_op_stream_TLAST_int_regslice),
    .vld_in(grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID),
    .ack_in(regslice_both_imag_op_stream_V_last_V_U_ack_in_dummy),
    .data_out(imag_op_stream_TLAST),
    .vld_out(regslice_both_imag_op_stream_V_last_V_U_vld_out),
    .ack_out(imag_op_stream_TREADY),
    .apdone_blk(regslice_both_imag_op_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_start_reg <= 1'b1;
        end else if ((grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_ready == 1'b1)) begin
            grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_start_reg <= 1'b1;
        end else if ((grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_ready == 1'b1)) begin
            grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_start_reg <= 1'b1;
        end else if ((grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_ready == 1'b1)) begin
            grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID == 1'b1))) begin
        imag_op_stream_TDATA_reg <= grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TDATA;
        imag_op_stream_TKEEP_reg <= grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TKEEP;
        imag_op_stream_TLAST_reg <= grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TLAST;
        imag_op_stream_TSTRB_reg <= grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID == 1'b1))) begin
        real_op_stream_TDATA_reg <= grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TDATA;
        real_op_stream_TKEEP_reg <= grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TKEEP;
        real_op_stream_TLAST_reg <= grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TLAST;
        real_op_stream_TSTRB_reg <= grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TSTRB;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state8)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        imag_op_address0 = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_op_address0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        imag_op_address0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_address0;
    end else begin
        imag_op_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        imag_op_ce0 = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_op_ce0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        imag_op_ce0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_ce0;
    end else begin
        imag_op_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_op_ce1 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_ce1;
    end else begin
        imag_op_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_op_d0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        imag_op_d0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_d0;
    end else begin
        imag_op_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID == 1'b1))) begin
        imag_op_stream_TDATA_int_regslice = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TDATA;
    end else begin
        imag_op_stream_TDATA_int_regslice = imag_op_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID == 1'b1))) begin
        imag_op_stream_TKEEP_int_regslice = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TKEEP;
    end else begin
        imag_op_stream_TKEEP_int_regslice = imag_op_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID == 1'b1))) begin
        imag_op_stream_TLAST_int_regslice = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TLAST;
    end else begin
        imag_op_stream_TLAST_int_regslice = imag_op_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID == 1'b1))) begin
        imag_op_stream_TSTRB_int_regslice = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TSTRB;
    end else begin
        imag_op_stream_TSTRB_int_regslice = imag_op_stream_TSTRB_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_op_we0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_op_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        imag_op_we0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_op_we0;
    end else begin
        imag_op_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_sample_address0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_sample_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        imag_sample_address0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_address0;
    end else begin
        imag_sample_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_sample_ce0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_imag_sample_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        imag_sample_ce0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_ce0;
    end else begin
        imag_sample_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imag_sample_stream_TREADY_int_regslice = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_stream_TREADY;
    end else begin
        imag_sample_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imag_sample_we0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_imag_sample_we0;
    end else begin
        imag_sample_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        real_op_address0 = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        real_op_address0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        real_op_address0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_address0;
    end else begin
        real_op_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        real_op_ce0 = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        real_op_ce0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        real_op_ce0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_ce0;
    end else begin
        real_op_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        real_op_ce1 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_ce1;
    end else begin
        real_op_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        real_op_d0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        real_op_d0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_d0;
    end else begin
        real_op_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID == 1'b1))) begin
        real_op_stream_TDATA_int_regslice = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TDATA;
    end else begin
        real_op_stream_TDATA_int_regslice = real_op_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID == 1'b1))) begin
        real_op_stream_TKEEP_int_regslice = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TKEEP;
    end else begin
        real_op_stream_TKEEP_int_regslice = real_op_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID == 1'b1))) begin
        real_op_stream_TLAST_int_regslice = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TLAST;
    end else begin
        real_op_stream_TLAST_int_regslice = real_op_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID == 1'b1))) begin
        real_op_stream_TSTRB_int_regslice = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TSTRB;
    end else begin
        real_op_stream_TSTRB_int_regslice = real_op_stream_TSTRB_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        real_op_we0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_op_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        real_op_we0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_op_we0;
    end else begin
        real_op_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        real_sample_address0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_sample_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        real_sample_address0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_address0;
    end else begin
        real_sample_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        real_sample_ce0 = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_real_sample_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        real_sample_ce0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_ce0;
    end else begin
        real_sample_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        real_sample_stream_TREADY_int_regslice = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_stream_TREADY;
    end else begin
        real_sample_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        real_sample_we0 = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_real_sample_we0;
    end else begin
        real_sample_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state8 = ((regslice_both_imag_op_stream_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_real_op_stream_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_start = grp_dft_Pipeline_VITIS_LOOP_25_1_fu_96_ap_start_reg;

assign grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_start = grp_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_fu_120_ap_start_reg;

assign grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_start = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_ap_start_reg;

assign grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TREADY = (imag_op_stream_TREADY_int_regslice & ap_CS_fsm_state7);

assign grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TREADY = (real_op_stream_TREADY_int_regslice & ap_CS_fsm_state7);

assign imag_op_stream_TVALID = regslice_both_imag_op_stream_V_data_V_U_vld_out;

assign imag_op_stream_TVALID_int_regslice = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_imag_op_stream_TVALID;

assign imag_sample_stream_TREADY = regslice_both_imag_sample_stream_V_data_V_U_ack_in;

assign real_op_stream_TVALID = regslice_both_real_op_stream_V_data_V_U_vld_out;

assign real_op_stream_TVALID_int_regslice = grp_dft_Pipeline_VITIS_LOOP_50_4_fu_132_real_op_stream_TVALID;

assign real_sample_stream_TREADY = regslice_both_real_sample_stream_V_data_V_U_ack_in;


reg find_kernel_block = 0;
// synthesis translate_off
`include "dft_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //dft

