// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dft_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        real_sample_address0,
        real_sample_ce0,
        real_sample_q0,
        imag_sample_address0,
        imag_sample_ce0,
        imag_sample_q0,
        real_op_address0,
        real_op_ce0,
        real_op_we0,
        real_op_d0,
        real_op_address1,
        real_op_ce1,
        real_op_q1,
        imag_op_address0,
        imag_op_ce0,
        imag_op_we0,
        imag_op_d0,
        imag_op_address1,
        imag_op_ce1,
        imag_op_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] real_sample_address0;
output   real_sample_ce0;
input  [31:0] real_sample_q0;
output  [9:0] imag_sample_address0;
output   imag_sample_ce0;
input  [31:0] imag_sample_q0;
output  [9:0] real_op_address0;
output   real_op_ce0;
output   real_op_we0;
output  [31:0] real_op_d0;
output  [9:0] real_op_address1;
output   real_op_ce1;
input  [31:0] real_op_q1;
output  [9:0] imag_op_address0;
output   imag_op_ce0;
output   imag_op_we0;
output  [31:0] imag_op_d0;
output  [9:0] imag_op_address1;
output   imag_op_ce1;
input  [31:0] imag_op_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln37_fu_192_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] cos_coefficients_table_address0;
wire   [31:0] cos_coefficients_table_q0;
wire   [9:0] sin_coefficients_table_address0;
wire   [31:0] sin_coefficients_table_q0;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] select_ln17_fu_221_p3;
reg   [10:0] select_ln17_reg_313;
reg   [10:0] select_ln17_reg_313_pp0_iter2_reg;
reg   [10:0] select_ln17_reg_313_pp0_iter3_reg;
reg   [10:0] select_ln17_reg_313_pp0_iter4_reg;
reg   [10:0] select_ln17_reg_313_pp0_iter5_reg;
reg   [10:0] select_ln17_reg_313_pp0_iter6_reg;
reg   [10:0] select_ln17_reg_313_pp0_iter7_reg;
reg   [10:0] select_ln17_reg_313_pp0_iter8_reg;
reg   [10:0] select_ln17_reg_313_pp0_iter9_reg;
reg   [10:0] select_ln17_reg_313_pp0_iter10_reg;
wire   [10:0] select_ln37_fu_235_p3;
reg   [10:0] select_ln37_reg_318;
wire   [9:0] mul_ln42_fu_251_p2;
reg   [9:0] mul_ln42_reg_323;
reg   [31:0] rs_reg_348;
reg   [31:0] is_reg_354;
reg   [31:0] c_reg_360;
reg   [31:0] s_reg_366;
wire   [31:0] grp_fu_158_p2;
reg   [31:0] mul_reg_372;
wire   [31:0] grp_fu_162_p2;
reg   [31:0] mul1_reg_377;
wire   [31:0] grp_fu_166_p2;
reg   [31:0] mul2_reg_382;
wire   [31:0] grp_fu_170_p2;
reg   [31:0] mul3_reg_387;
reg   [9:0] real_op_addr_reg_392;
reg   [9:0] real_op_addr_reg_392_pp0_iter12_reg;
reg   [9:0] real_op_addr_reg_392_pp0_iter13_reg;
reg   [9:0] real_op_addr_reg_392_pp0_iter14_reg;
reg   [9:0] real_op_addr_reg_392_pp0_iter15_reg;
reg   [9:0] real_op_addr_reg_392_pp0_iter16_reg;
reg   [9:0] real_op_addr_reg_392_pp0_iter17_reg;
reg   [9:0] imag_op_addr_reg_398;
reg   [9:0] imag_op_addr_reg_398_pp0_iter12_reg;
reg   [9:0] imag_op_addr_reg_398_pp0_iter13_reg;
reg   [9:0] imag_op_addr_reg_398_pp0_iter14_reg;
reg   [9:0] imag_op_addr_reg_398_pp0_iter15_reg;
reg   [9:0] imag_op_addr_reg_398_pp0_iter16_reg;
reg   [9:0] imag_op_addr_reg_398_pp0_iter17_reg;
wire   [31:0] grp_fu_142_p2;
reg   [31:0] sub_reg_404;
reg   [31:0] real_op_load_reg_409;
wire   [31:0] grp_fu_146_p2;
reg   [31:0] add1_reg_414;
reg   [31:0] imag_op_load_reg_419;
wire   [31:0] grp_fu_150_p2;
reg   [31:0] add_reg_424;
wire   [31:0] grp_fu_154_p2;
reg   [31:0] add2_reg_429;
wire   [63:0] zext_ln37_fu_273_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln42_fu_278_p1;
wire   [63:0] zext_ln41_fu_283_p1;
reg   [10:0] i_fu_44;
wire   [10:0] add_ln41_fu_257_p2;
wire    ap_loop_init;
reg   [10:0] j_fu_48;
reg   [20:0] indvar_flatten_fu_52;
wire   [20:0] add_ln37_fu_198_p2;
reg   [20:0] ap_sig_allocacmp_indvar_flatten_load;
reg    real_sample_ce0_local;
reg    imag_sample_ce0_local;
reg    cos_coefficients_table_ce0_local;
reg    sin_coefficients_table_ce0_local;
reg    real_op_ce1_local;
reg    real_op_we0_local;
reg    real_op_ce0_local;
reg    imag_op_ce1_local;
reg    imag_op_we0_local;
reg    imag_op_ce0_local;
wire   [0:0] icmp_ln41_fu_215_p2;
wire   [10:0] add_ln37_1_fu_229_p2;
wire  signed [9:0] mul_ln42_fu_251_p0;
wire  signed [9:0] mul_ln42_fu_251_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 i_fu_44 = 11'd0;
#0 j_fu_48 = 11'd0;
#0 indvar_flatten_fu_52 = 21'd0;
#0 ap_done_reg = 1'b0;
end

dft_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_cos_coefficients_table_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
cos_coefficients_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cos_coefficients_table_address0),
    .ce0(cos_coefficients_table_ce0_local),
    .q0(cos_coefficients_table_q0)
);

dft_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3_sin_coefficients_table_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
sin_coefficients_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sin_coefficients_table_address0),
    .ce0(sin_coefficients_table_ce0_local),
    .q0(sin_coefficients_table_q0)
);

dft_fsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_5_full_dsp_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_reg_372),
    .din1(mul1_reg_377),
    .ce(1'b1),
    .dout(grp_fu_142_p2)
);

dft_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul2_reg_382),
    .din1(mul3_reg_387),
    .ce(1'b1),
    .dout(grp_fu_146_p2)
);

dft_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(real_op_load_reg_409),
    .din1(sub_reg_404),
    .ce(1'b1),
    .dout(grp_fu_150_p2)
);

dft_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(imag_op_load_reg_419),
    .din1(add1_reg_414),
    .ce(1'b1),
    .dout(grp_fu_154_p2)
);

dft_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rs_reg_348),
    .din1(c_reg_360),
    .ce(1'b1),
    .dout(grp_fu_158_p2)
);

dft_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(is_reg_354),
    .din1(s_reg_366),
    .ce(1'b1),
    .dout(grp_fu_162_p2)
);

dft_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rs_reg_348),
    .din1(s_reg_366),
    .ce(1'b1),
    .dout(grp_fu_166_p2)
);

dft_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(is_reg_354),
    .din1(c_reg_360),
    .ce(1'b1),
    .dout(grp_fu_170_p2)
);

dft_mul_10s_10s_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
mul_10s_10s_10_1_1_U21(
    .din0(mul_ln42_fu_251_p0),
    .din1(mul_ln42_fu_251_p1),
    .dout(mul_ln42_fu_251_p2)
);

dft_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter17_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_44 <= 11'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_44 <= add_ln41_fu_257_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln37_fu_192_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_52 <= add_ln37_fu_198_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_52 <= 21'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_48 <= 11'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_48 <= select_ln37_fu_235_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add1_reg_414 <= grp_fu_146_p2;
        add2_reg_429 <= grp_fu_154_p2;
        add_reg_424 <= grp_fu_150_p2;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        c_reg_360 <= cos_coefficients_table_q0;
        imag_op_addr_reg_398 <= zext_ln41_fu_283_p1;
        imag_op_addr_reg_398_pp0_iter12_reg <= imag_op_addr_reg_398;
        imag_op_addr_reg_398_pp0_iter13_reg <= imag_op_addr_reg_398_pp0_iter12_reg;
        imag_op_addr_reg_398_pp0_iter14_reg <= imag_op_addr_reg_398_pp0_iter13_reg;
        imag_op_addr_reg_398_pp0_iter15_reg <= imag_op_addr_reg_398_pp0_iter14_reg;
        imag_op_addr_reg_398_pp0_iter16_reg <= imag_op_addr_reg_398_pp0_iter15_reg;
        imag_op_addr_reg_398_pp0_iter17_reg <= imag_op_addr_reg_398_pp0_iter16_reg;
        is_reg_354 <= imag_sample_q0;
        mul1_reg_377 <= grp_fu_162_p2;
        mul2_reg_382 <= grp_fu_166_p2;
        mul3_reg_387 <= grp_fu_170_p2;
        mul_reg_372 <= grp_fu_158_p2;
        real_op_addr_reg_392 <= zext_ln41_fu_283_p1;
        real_op_addr_reg_392_pp0_iter12_reg <= real_op_addr_reg_392;
        real_op_addr_reg_392_pp0_iter13_reg <= real_op_addr_reg_392_pp0_iter12_reg;
        real_op_addr_reg_392_pp0_iter14_reg <= real_op_addr_reg_392_pp0_iter13_reg;
        real_op_addr_reg_392_pp0_iter15_reg <= real_op_addr_reg_392_pp0_iter14_reg;
        real_op_addr_reg_392_pp0_iter16_reg <= real_op_addr_reg_392_pp0_iter15_reg;
        real_op_addr_reg_392_pp0_iter17_reg <= real_op_addr_reg_392_pp0_iter16_reg;
        rs_reg_348 <= real_sample_q0;
        s_reg_366 <= sin_coefficients_table_q0;
        select_ln17_reg_313_pp0_iter10_reg <= select_ln17_reg_313_pp0_iter9_reg;
        select_ln17_reg_313_pp0_iter2_reg <= select_ln17_reg_313;
        select_ln17_reg_313_pp0_iter3_reg <= select_ln17_reg_313_pp0_iter2_reg;
        select_ln17_reg_313_pp0_iter4_reg <= select_ln17_reg_313_pp0_iter3_reg;
        select_ln17_reg_313_pp0_iter5_reg <= select_ln17_reg_313_pp0_iter4_reg;
        select_ln17_reg_313_pp0_iter6_reg <= select_ln17_reg_313_pp0_iter5_reg;
        select_ln17_reg_313_pp0_iter7_reg <= select_ln17_reg_313_pp0_iter6_reg;
        select_ln17_reg_313_pp0_iter8_reg <= select_ln17_reg_313_pp0_iter7_reg;
        select_ln17_reg_313_pp0_iter9_reg <= select_ln17_reg_313_pp0_iter8_reg;
        sub_reg_404 <= grp_fu_142_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        mul_ln42_reg_323 <= mul_ln42_fu_251_p2;
        select_ln17_reg_313 <= select_ln17_fu_221_p3;
        select_ln37_reg_318 <= select_ln37_fu_235_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        imag_op_load_reg_419 <= imag_op_q1;
        real_op_load_reg_409 <= real_op_q1;
    end
end

always @ (*) begin
    if (((icmp_ln37_fu_192_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter17_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 21'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        cos_coefficients_table_ce0_local = 1'b1;
    end else begin
        cos_coefficients_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        imag_op_ce0_local = 1'b1;
    end else begin
        imag_op_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        imag_op_ce1_local = 1'b1;
    end else begin
        imag_op_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        imag_op_we0_local = 1'b1;
    end else begin
        imag_op_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        imag_sample_ce0_local = 1'b1;
    end else begin
        imag_sample_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        real_op_ce0_local = 1'b1;
    end else begin
        real_op_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        real_op_ce1_local = 1'b1;
    end else begin
        real_op_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        real_op_we0_local = 1'b1;
    end else begin
        real_op_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        real_sample_ce0_local = 1'b1;
    end else begin
        real_sample_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sin_coefficients_table_ce0_local = 1'b1;
    end else begin
        sin_coefficients_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_1_fu_229_p2 = (j_fu_48 + 11'd1);

assign add_ln37_fu_198_p2 = (ap_sig_allocacmp_indvar_flatten_load + 21'd1);

assign add_ln41_fu_257_p2 = (select_ln17_fu_221_p3 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cos_coefficients_table_address0 = zext_ln42_fu_278_p1;

assign icmp_ln37_fu_192_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 21'd1048576) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_215_p2 = ((i_fu_44 == 11'd1024) ? 1'b1 : 1'b0);

assign imag_op_address0 = imag_op_addr_reg_398_pp0_iter17_reg;

assign imag_op_address1 = zext_ln41_fu_283_p1;

assign imag_op_ce0 = imag_op_ce0_local;

assign imag_op_ce1 = imag_op_ce1_local;

assign imag_op_d0 = add2_reg_429;

assign imag_op_we0 = imag_op_we0_local;

assign imag_sample_address0 = zext_ln37_fu_273_p1;

assign imag_sample_ce0 = imag_sample_ce0_local;

assign mul_ln42_fu_251_p0 = select_ln17_fu_221_p3[9:0];

assign mul_ln42_fu_251_p1 = select_ln37_fu_235_p3[9:0];

assign real_op_address0 = real_op_addr_reg_392_pp0_iter17_reg;

assign real_op_address1 = zext_ln41_fu_283_p1;

assign real_op_ce0 = real_op_ce0_local;

assign real_op_ce1 = real_op_ce1_local;

assign real_op_d0 = add_reg_424;

assign real_op_we0 = real_op_we0_local;

assign real_sample_address0 = zext_ln37_fu_273_p1;

assign real_sample_ce0 = real_sample_ce0_local;

assign select_ln17_fu_221_p3 = ((icmp_ln41_fu_215_p2[0:0] == 1'b1) ? 11'd0 : i_fu_44);

assign select_ln37_fu_235_p3 = ((icmp_ln41_fu_215_p2[0:0] == 1'b1) ? add_ln37_1_fu_229_p2 : j_fu_48);

assign sin_coefficients_table_address0 = zext_ln42_fu_278_p1;

assign zext_ln37_fu_273_p1 = select_ln37_reg_318;

assign zext_ln41_fu_283_p1 = select_ln17_reg_313_pp0_iter10_reg;

assign zext_ln42_fu_278_p1 = mul_ln42_reg_323;

endmodule //dft_dft_Pipeline_VITIS_LOOP_37_2_VITIS_LOOP_41_3
