// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bnn_bnn,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.153000,HLS_SYN_LAT=106,HLS_SYN_TPT=107,HLS_SYN_MEM=154,HLS_SYN_DSP=0,HLS_SYN_FF=13690,HLS_SYN_LUT=46994,HLS_VERSION=2024_2}" *)

module bnn (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        in_r_TDATA,
        in_r_TKEEP,
        in_r_TSTRB,
        in_r_TLAST,
        in_r_TID,
        out_r_TDATA,
        out_r_TKEEP,
        out_r_TSTRB,
        out_r_TLAST,
        out_r_TID,
        in_r_TVALID,
        in_r_TREADY,
        out_r_TVALID,
        out_r_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [31:0] in_r_TDATA;
input  [3:0] in_r_TKEEP;
input  [3:0] in_r_TSTRB;
input  [0:0] in_r_TLAST;
input  [31:0] in_r_TID;
output  [31:0] out_r_TDATA;
output  [3:0] out_r_TKEEP;
output  [3:0] out_r_TSTRB;
output  [0:0] out_r_TLAST;
output  [31:0] out_r_TID;
input   in_r_TVALID;
output   in_r_TREADY;
output   out_r_TVALID;
input   out_r_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    compute_L1_U0_ap_start;
wire    compute_L1_U0_ap_done;
wire    compute_L1_U0_ap_continue;
wire    compute_L1_U0_ap_idle;
wire    compute_L1_U0_ap_ready;
wire    compute_L1_U0_start_out;
wire    compute_L1_U0_start_write;
wire    compute_L1_U0_in_r_TREADY;
wire   [64:0] compute_L1_U0_l1_to_l2_din;
wire    compute_L1_U0_l1_to_l2_write;
wire    compute_L2_U0_ap_start;
wire    compute_L2_U0_ap_done;
wire    compute_L2_U0_ap_continue;
wire    compute_L2_U0_ap_idle;
wire    compute_L2_U0_ap_ready;
wire    compute_L2_U0_start_out;
wire    compute_L2_U0_start_write;
wire    compute_L2_U0_l1_to_l2_read;
wire   [64:0] compute_L2_U0_l2_to_l3_din;
wire    compute_L2_U0_l2_to_l3_write;
wire   [31:0] compute_L2_U0_l2_to_l3_num_data_valid;
wire   [31:0] compute_L2_U0_l2_to_l3_fifo_cap;
wire    compute_L3_U0_ap_start;
wire    compute_L3_U0_ap_done;
wire    compute_L3_U0_ap_continue;
wire    compute_L3_U0_ap_idle;
wire    compute_L3_U0_ap_ready;
wire    compute_L3_U0_l2_to_l3_read;
wire   [31:0] compute_L3_U0_out_r_TDATA;
wire    compute_L3_U0_out_r_TVALID;
wire   [3:0] compute_L3_U0_out_r_TKEEP;
wire   [3:0] compute_L3_U0_out_r_TSTRB;
wire   [0:0] compute_L3_U0_out_r_TLAST;
wire   [31:0] compute_L3_U0_out_r_TID;
wire    l1_to_l2_full_n;
wire   [64:0] l1_to_l2_dout;
wire    l1_to_l2_empty_n;
wire   [2:0] l1_to_l2_num_data_valid;
wire   [2:0] l1_to_l2_fifo_cap;
wire    l2_to_l3_full_n;
wire   [64:0] l2_to_l3_dout;
wire    l2_to_l3_empty_n;
wire   [2:0] l2_to_l3_num_data_valid;
wire   [2:0] l2_to_l3_fifo_cap;
wire   [0:0] start_for_compute_L2_U0_din;
wire    start_for_compute_L2_U0_full_n;
wire   [0:0] start_for_compute_L2_U0_dout;
wire    start_for_compute_L2_U0_empty_n;
wire   [0:0] start_for_compute_L3_U0_din;
wire    start_for_compute_L3_U0_full_n;
wire   [0:0] start_for_compute_L3_U0_dout;
wire    start_for_compute_L3_U0_empty_n;

bnn_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

bnn_compute_L1 compute_L1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(compute_L1_U0_ap_start),
    .start_full_n(start_for_compute_L2_U0_full_n),
    .ap_done(compute_L1_U0_ap_done),
    .ap_continue(compute_L1_U0_ap_continue),
    .ap_idle(compute_L1_U0_ap_idle),
    .ap_ready(compute_L1_U0_ap_ready),
    .start_out(compute_L1_U0_start_out),
    .start_write(compute_L1_U0_start_write),
    .in_r_TDATA(in_r_TDATA),
    .in_r_TVALID(in_r_TVALID),
    .in_r_TREADY(compute_L1_U0_in_r_TREADY),
    .in_r_TKEEP(in_r_TKEEP),
    .in_r_TSTRB(in_r_TSTRB),
    .in_r_TLAST(in_r_TLAST),
    .in_r_TID(in_r_TID),
    .l1_to_l2_din(compute_L1_U0_l1_to_l2_din),
    .l1_to_l2_full_n(l1_to_l2_full_n),
    .l1_to_l2_write(compute_L1_U0_l1_to_l2_write),
    .l1_to_l2_num_data_valid(l1_to_l2_num_data_valid),
    .l1_to_l2_fifo_cap(l1_to_l2_fifo_cap)
);

bnn_compute_L2 compute_L2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(compute_L2_U0_ap_start),
    .start_full_n(start_for_compute_L3_U0_full_n),
    .ap_done(compute_L2_U0_ap_done),
    .ap_continue(compute_L2_U0_ap_continue),
    .ap_idle(compute_L2_U0_ap_idle),
    .ap_ready(compute_L2_U0_ap_ready),
    .start_out(compute_L2_U0_start_out),
    .start_write(compute_L2_U0_start_write),
    .l1_to_l2_dout(l1_to_l2_dout),
    .l1_to_l2_empty_n(l1_to_l2_empty_n),
    .l1_to_l2_read(compute_L2_U0_l1_to_l2_read),
    .l1_to_l2_num_data_valid(l1_to_l2_num_data_valid),
    .l1_to_l2_fifo_cap(l1_to_l2_fifo_cap),
    .l2_to_l3_din(compute_L2_U0_l2_to_l3_din),
    .l2_to_l3_full_n(l2_to_l3_full_n),
    .l2_to_l3_write(compute_L2_U0_l2_to_l3_write),
    .l2_to_l3_num_data_valid(compute_L2_U0_l2_to_l3_num_data_valid),
    .l2_to_l3_fifo_cap(compute_L2_U0_l2_to_l3_fifo_cap)
);

bnn_compute_L3 compute_L3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(compute_L3_U0_ap_start),
    .ap_done(compute_L3_U0_ap_done),
    .ap_continue(compute_L3_U0_ap_continue),
    .ap_idle(compute_L3_U0_ap_idle),
    .ap_ready(compute_L3_U0_ap_ready),
    .l2_to_l3_dout(l2_to_l3_dout),
    .l2_to_l3_empty_n(l2_to_l3_empty_n),
    .l2_to_l3_read(compute_L3_U0_l2_to_l3_read),
    .l2_to_l3_num_data_valid(l2_to_l3_num_data_valid),
    .l2_to_l3_fifo_cap(l2_to_l3_fifo_cap),
    .out_r_TDATA(compute_L3_U0_out_r_TDATA),
    .out_r_TVALID(compute_L3_U0_out_r_TVALID),
    .out_r_TREADY(out_r_TREADY),
    .out_r_TKEEP(compute_L3_U0_out_r_TKEEP),
    .out_r_TSTRB(compute_L3_U0_out_r_TSTRB),
    .out_r_TLAST(compute_L3_U0_out_r_TLAST),
    .out_r_TID(compute_L3_U0_out_r_TID)
);

bnn_fifo_w65_d4_S l1_to_l2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_L1_U0_l1_to_l2_din),
    .if_full_n(l1_to_l2_full_n),
    .if_write(compute_L1_U0_l1_to_l2_write),
    .if_dout(l1_to_l2_dout),
    .if_empty_n(l1_to_l2_empty_n),
    .if_read(compute_L2_U0_l1_to_l2_read),
    .if_num_data_valid(l1_to_l2_num_data_valid),
    .if_fifo_cap(l1_to_l2_fifo_cap)
);

bnn_fifo_w65_d2_S l2_to_l3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_L2_U0_l2_to_l3_din),
    .if_full_n(l2_to_l3_full_n),
    .if_write(compute_L2_U0_l2_to_l3_write),
    .if_dout(l2_to_l3_dout),
    .if_empty_n(l2_to_l3_empty_n),
    .if_read(compute_L3_U0_l2_to_l3_read),
    .if_num_data_valid(l2_to_l3_num_data_valid),
    .if_fifo_cap(l2_to_l3_fifo_cap)
);

bnn_start_for_compute_L2_U0 start_for_compute_L2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_compute_L2_U0_din),
    .if_full_n(start_for_compute_L2_U0_full_n),
    .if_write(compute_L1_U0_start_write),
    .if_dout(start_for_compute_L2_U0_dout),
    .if_empty_n(start_for_compute_L2_U0_empty_n),
    .if_read(compute_L2_U0_ap_ready)
);

bnn_start_for_compute_L3_U0 start_for_compute_L3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_compute_L3_U0_din),
    .if_full_n(start_for_compute_L3_U0_full_n),
    .if_write(compute_L2_U0_start_write),
    .if_dout(start_for_compute_L3_U0_dout),
    .if_empty_n(start_for_compute_L3_U0_empty_n),
    .if_read(compute_L3_U0_ap_ready)
);

assign ap_done = compute_L3_U0_ap_done;

assign ap_idle = (compute_L3_U0_ap_idle & compute_L2_U0_ap_idle & compute_L1_U0_ap_idle);

assign ap_ready = compute_L1_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign compute_L1_U0_ap_continue = 1'b1;

assign compute_L1_U0_ap_start = ap_start;

assign compute_L2_U0_ap_continue = 1'b1;

assign compute_L2_U0_ap_start = start_for_compute_L2_U0_empty_n;

assign compute_L2_U0_l2_to_l3_fifo_cap = l2_to_l3_fifo_cap;

assign compute_L2_U0_l2_to_l3_num_data_valid = l2_to_l3_num_data_valid;

assign compute_L3_U0_ap_continue = 1'b1;

assign compute_L3_U0_ap_start = start_for_compute_L3_U0_empty_n;

assign in_r_TREADY = compute_L1_U0_in_r_TREADY;

assign out_r_TDATA = compute_L3_U0_out_r_TDATA;

assign out_r_TID = compute_L3_U0_out_r_TID;

assign out_r_TKEEP = compute_L3_U0_out_r_TKEEP;

assign out_r_TLAST = compute_L3_U0_out_r_TLAST;

assign out_r_TSTRB = compute_L3_U0_out_r_TSTRB;

assign out_r_TVALID = compute_L3_U0_out_r_TVALID;

assign start_for_compute_L2_U0_din = 1'b1;

assign start_for_compute_L3_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "bnn_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "bnn_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //bnn

