// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_compute_L1_Pipeline_LOAD_L1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_TVALID,
        local_in_24,
        local_in_23,
        local_in_22,
        local_in_21,
        local_in_20,
        local_in_19,
        local_in_18,
        local_in_17,
        local_in_16,
        local_in_15,
        local_in_14,
        local_in_13,
        local_in_12,
        local_in_11,
        local_in_10,
        local_in_9,
        local_in_8,
        local_in_7,
        local_in_6,
        local_in_5,
        local_in_4,
        local_in_3,
        local_in_2,
        local_in_1,
        local_in,
        current_id,
        in_r_TDATA,
        in_r_TREADY,
        in_r_TKEEP,
        in_r_TSTRB,
        in_r_TLAST,
        in_r_TID,
        local_in_49_out,
        local_in_49_out_ap_vld,
        local_in_48_out,
        local_in_48_out_ap_vld,
        local_in_47_out,
        local_in_47_out_ap_vld,
        local_in_46_out,
        local_in_46_out_ap_vld,
        local_in_45_out,
        local_in_45_out_ap_vld,
        local_in_44_out,
        local_in_44_out_ap_vld,
        local_in_43_out,
        local_in_43_out_ap_vld,
        local_in_42_out,
        local_in_42_out_ap_vld,
        local_in_41_out,
        local_in_41_out_ap_vld,
        local_in_40_out,
        local_in_40_out_ap_vld,
        local_in_39_out,
        local_in_39_out_ap_vld,
        local_in_38_out,
        local_in_38_out_ap_vld,
        local_in_37_out,
        local_in_37_out_ap_vld,
        local_in_36_out,
        local_in_36_out_ap_vld,
        local_in_35_out,
        local_in_35_out_ap_vld,
        local_in_34_out,
        local_in_34_out_ap_vld,
        local_in_33_out,
        local_in_33_out_ap_vld,
        local_in_32_out,
        local_in_32_out_ap_vld,
        local_in_31_out,
        local_in_31_out_ap_vld,
        local_in_30_out,
        local_in_30_out_ap_vld,
        local_in_29_out,
        local_in_29_out_ap_vld,
        local_in_28_out,
        local_in_28_out_ap_vld,
        local_in_27_out,
        local_in_27_out_ap_vld,
        local_in_26_out,
        local_in_26_out_ap_vld,
        local_in_25_out,
        local_in_25_out_ap_vld,
        is_last_sample_8_out,
        is_last_sample_8_out_ap_vld,
        current_id_5_out,
        current_id_5_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_r_TVALID;
input  [31:0] local_in_24;
input  [31:0] local_in_23;
input  [31:0] local_in_22;
input  [31:0] local_in_21;
input  [31:0] local_in_20;
input  [31:0] local_in_19;
input  [31:0] local_in_18;
input  [31:0] local_in_17;
input  [31:0] local_in_16;
input  [31:0] local_in_15;
input  [31:0] local_in_14;
input  [31:0] local_in_13;
input  [31:0] local_in_12;
input  [31:0] local_in_11;
input  [31:0] local_in_10;
input  [31:0] local_in_9;
input  [31:0] local_in_8;
input  [31:0] local_in_7;
input  [31:0] local_in_6;
input  [31:0] local_in_5;
input  [31:0] local_in_4;
input  [31:0] local_in_3;
input  [31:0] local_in_2;
input  [31:0] local_in_1;
input  [31:0] local_in;
input  [31:0] current_id;
input  [31:0] in_r_TDATA;
output   in_r_TREADY;
input  [3:0] in_r_TKEEP;
input  [3:0] in_r_TSTRB;
input  [0:0] in_r_TLAST;
input  [31:0] in_r_TID;
output  [31:0] local_in_49_out;
output   local_in_49_out_ap_vld;
output  [31:0] local_in_48_out;
output   local_in_48_out_ap_vld;
output  [31:0] local_in_47_out;
output   local_in_47_out_ap_vld;
output  [31:0] local_in_46_out;
output   local_in_46_out_ap_vld;
output  [31:0] local_in_45_out;
output   local_in_45_out_ap_vld;
output  [31:0] local_in_44_out;
output   local_in_44_out_ap_vld;
output  [31:0] local_in_43_out;
output   local_in_43_out_ap_vld;
output  [31:0] local_in_42_out;
output   local_in_42_out_ap_vld;
output  [31:0] local_in_41_out;
output   local_in_41_out_ap_vld;
output  [31:0] local_in_40_out;
output   local_in_40_out_ap_vld;
output  [31:0] local_in_39_out;
output   local_in_39_out_ap_vld;
output  [31:0] local_in_38_out;
output   local_in_38_out_ap_vld;
output  [31:0] local_in_37_out;
output   local_in_37_out_ap_vld;
output  [31:0] local_in_36_out;
output   local_in_36_out_ap_vld;
output  [31:0] local_in_35_out;
output   local_in_35_out_ap_vld;
output  [31:0] local_in_34_out;
output   local_in_34_out_ap_vld;
output  [31:0] local_in_33_out;
output   local_in_33_out_ap_vld;
output  [31:0] local_in_32_out;
output   local_in_32_out_ap_vld;
output  [31:0] local_in_31_out;
output   local_in_31_out_ap_vld;
output  [31:0] local_in_30_out;
output   local_in_30_out_ap_vld;
output  [31:0] local_in_29_out;
output   local_in_29_out_ap_vld;
output  [31:0] local_in_28_out;
output   local_in_28_out_ap_vld;
output  [31:0] local_in_27_out;
output   local_in_27_out_ap_vld;
output  [31:0] local_in_26_out;
output   local_in_26_out_ap_vld;
output  [31:0] local_in_25_out;
output   local_in_25_out_ap_vld;
output  [0:0] is_last_sample_8_out;
output   is_last_sample_8_out_ap_vld;
output  [31:0] current_id_5_out;
output   current_id_5_out_ap_vld;

reg ap_idle;
reg in_r_TREADY;
reg local_in_49_out_ap_vld;
reg local_in_48_out_ap_vld;
reg local_in_47_out_ap_vld;
reg local_in_46_out_ap_vld;
reg local_in_45_out_ap_vld;
reg local_in_44_out_ap_vld;
reg local_in_43_out_ap_vld;
reg local_in_42_out_ap_vld;
reg local_in_41_out_ap_vld;
reg local_in_40_out_ap_vld;
reg local_in_39_out_ap_vld;
reg local_in_38_out_ap_vld;
reg local_in_37_out_ap_vld;
reg local_in_36_out_ap_vld;
reg local_in_35_out_ap_vld;
reg local_in_34_out_ap_vld;
reg local_in_33_out_ap_vld;
reg local_in_32_out_ap_vld;
reg local_in_31_out_ap_vld;
reg local_in_30_out_ap_vld;
reg local_in_29_out_ap_vld;
reg local_in_28_out_ap_vld;
reg local_in_27_out_ap_vld;
reg local_in_26_out_ap_vld;
reg local_in_25_out_ap_vld;
reg is_last_sample_8_out_ap_vld;
reg current_id_5_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln21_reg_1311;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln21_fu_825_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_r_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [0:0] is_last_sample_reg_675;
reg   [4:0] i_1_reg_1307;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln25_fu_837_p2;
reg   [0:0] icmp_ln25_reg_1315;
wire   [0:0] icmp_ln26_fu_843_p2;
reg   [0:0] icmp_ln26_reg_1320;
wire   [0:0] is_last_sample_6_fu_1001_p3;
reg    ap_block_pp0_stage0_11001_grp1;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [31:0] current_id_5_fu_208;
wire   [31:0] current_id_6_fu_994_p3;
reg   [4:0] i_fu_212;
wire   [4:0] add_ln21_fu_831_p2;
reg   [4:0] ap_sig_allocacmp_i_1;
reg   [31:0] local_in_25_fu_216;
reg   [31:0] local_in_26_fu_220;
reg   [31:0] local_in_27_fu_224;
reg   [31:0] local_in_28_fu_228;
reg   [31:0] local_in_29_fu_232;
reg   [31:0] local_in_30_fu_236;
reg   [31:0] local_in_31_fu_240;
reg   [31:0] local_in_32_fu_244;
reg   [31:0] local_in_33_fu_248;
reg   [31:0] local_in_34_fu_252;
reg   [31:0] local_in_35_fu_256;
reg   [31:0] local_in_36_fu_260;
reg   [31:0] local_in_37_fu_264;
reg   [31:0] local_in_38_fu_268;
reg   [31:0] local_in_39_fu_272;
reg   [31:0] local_in_40_fu_276;
reg   [31:0] local_in_41_fu_280;
reg   [31:0] local_in_42_fu_284;
reg   [31:0] local_in_43_fu_288;
reg   [31:0] local_in_44_fu_292;
reg   [31:0] local_in_45_fu_296;
reg   [31:0] local_in_46_fu_300;
reg   [31:0] local_in_47_fu_304;
reg   [31:0] local_in_48_fu_308;
reg   [31:0] local_in_49_fu_312;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_520;
reg    ap_condition_547;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 current_id_5_fu_208 = 32'd0;
#0 i_fu_212 = 5'd0;
#0 local_in_25_fu_216 = 32'd0;
#0 local_in_26_fu_220 = 32'd0;
#0 local_in_27_fu_224 = 32'd0;
#0 local_in_28_fu_228 = 32'd0;
#0 local_in_29_fu_232 = 32'd0;
#0 local_in_30_fu_236 = 32'd0;
#0 local_in_31_fu_240 = 32'd0;
#0 local_in_32_fu_244 = 32'd0;
#0 local_in_33_fu_248 = 32'd0;
#0 local_in_34_fu_252 = 32'd0;
#0 local_in_35_fu_256 = 32'd0;
#0 local_in_36_fu_260 = 32'd0;
#0 local_in_37_fu_264 = 32'd0;
#0 local_in_38_fu_268 = 32'd0;
#0 local_in_39_fu_272 = 32'd0;
#0 local_in_40_fu_276 = 32'd0;
#0 local_in_41_fu_280 = 32'd0;
#0 local_in_42_fu_284 = 32'd0;
#0 local_in_43_fu_288 = 32'd0;
#0 local_in_44_fu_292 = 32'd0;
#0 local_in_45_fu_296 = 32'd0;
#0 local_in_46_fu_300 = 32'd0;
#0 local_in_47_fu_304 = 32'd0;
#0 local_in_48_fu_308 = 32'd0;
#0 local_in_49_fu_312 = 32'd0;
#0 ap_done_reg = 1'b0;
end

bnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            current_id_5_fu_208 <= current_id;
        end else if (((icmp_ln21_reg_1311 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            current_id_5_fu_208 <= current_id_6_fu_994_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln21_fu_825_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_212 <= add_ln21_fu_831_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_212 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_520)) begin
            is_last_sample_reg_675 <= is_last_sample_6_fu_1001_p3;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            is_last_sample_reg_675 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_25_fu_216 <= local_in;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd0))) begin
            local_in_25_fu_216 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_26_fu_220 <= local_in_1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd1))) begin
            local_in_26_fu_220 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_27_fu_224 <= local_in_2;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd2))) begin
            local_in_27_fu_224 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_28_fu_228 <= local_in_3;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd3))) begin
            local_in_28_fu_228 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_29_fu_232 <= local_in_4;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd4))) begin
            local_in_29_fu_232 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_30_fu_236 <= local_in_5;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd5))) begin
            local_in_30_fu_236 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_31_fu_240 <= local_in_6;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd6))) begin
            local_in_31_fu_240 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_32_fu_244 <= local_in_7;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd7))) begin
            local_in_32_fu_244 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_33_fu_248 <= local_in_8;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd8))) begin
            local_in_33_fu_248 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_34_fu_252 <= local_in_9;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd9))) begin
            local_in_34_fu_252 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_35_fu_256 <= local_in_10;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd10))) begin
            local_in_35_fu_256 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_36_fu_260 <= local_in_11;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd11))) begin
            local_in_36_fu_260 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_37_fu_264 <= local_in_12;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd12))) begin
            local_in_37_fu_264 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_38_fu_268 <= local_in_13;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd13))) begin
            local_in_38_fu_268 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_39_fu_272 <= local_in_14;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd14))) begin
            local_in_39_fu_272 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_40_fu_276 <= local_in_15;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd15))) begin
            local_in_40_fu_276 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_41_fu_280 <= local_in_16;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd16))) begin
            local_in_41_fu_280 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_42_fu_284 <= local_in_17;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd17))) begin
            local_in_42_fu_284 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_43_fu_288 <= local_in_18;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd18))) begin
            local_in_43_fu_288 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_44_fu_292 <= local_in_19;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd19))) begin
            local_in_44_fu_292 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_45_fu_296 <= local_in_20;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd20))) begin
            local_in_45_fu_296 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_46_fu_300 <= local_in_21;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd21))) begin
            local_in_46_fu_300 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_47_fu_304 <= local_in_22;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd22))) begin
            local_in_47_fu_304 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_48_fu_308 <= local_in_23;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (i_1_reg_1307 == 5'd23))) begin
            local_in_48_fu_308 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            local_in_49_fu_312 <= local_in_24;
        end else if ((1'b1 == ap_condition_547)) begin
            local_in_49_fu_312 <= in_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_1307 <= ap_sig_allocacmp_i_1;
        icmp_ln21_reg_1311 <= icmp_ln21_fu_825_p2;
        icmp_ln25_reg_1315 <= icmp_ln25_fu_837_p2;
        icmp_ln26_reg_1320 <= icmp_ln26_fu_843_p2;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_212;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_id_5_out_ap_vld = 1'b1;
    end else begin
        current_id_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln21_reg_1311 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_r_TDATA_blk_n = in_r_TVALID;
    end else begin
        in_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln21_reg_1311 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_r_TREADY = 1'b1;
    end else begin
        in_r_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        is_last_sample_8_out_ap_vld = 1'b1;
    end else begin
        is_last_sample_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_25_out_ap_vld = 1'b1;
    end else begin
        local_in_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_26_out_ap_vld = 1'b1;
    end else begin
        local_in_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_27_out_ap_vld = 1'b1;
    end else begin
        local_in_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_28_out_ap_vld = 1'b1;
    end else begin
        local_in_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_29_out_ap_vld = 1'b1;
    end else begin
        local_in_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_30_out_ap_vld = 1'b1;
    end else begin
        local_in_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_31_out_ap_vld = 1'b1;
    end else begin
        local_in_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_32_out_ap_vld = 1'b1;
    end else begin
        local_in_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_33_out_ap_vld = 1'b1;
    end else begin
        local_in_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_34_out_ap_vld = 1'b1;
    end else begin
        local_in_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_35_out_ap_vld = 1'b1;
    end else begin
        local_in_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_36_out_ap_vld = 1'b1;
    end else begin
        local_in_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_37_out_ap_vld = 1'b1;
    end else begin
        local_in_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_38_out_ap_vld = 1'b1;
    end else begin
        local_in_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_39_out_ap_vld = 1'b1;
    end else begin
        local_in_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_40_out_ap_vld = 1'b1;
    end else begin
        local_in_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_41_out_ap_vld = 1'b1;
    end else begin
        local_in_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_42_out_ap_vld = 1'b1;
    end else begin
        local_in_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_43_out_ap_vld = 1'b1;
    end else begin
        local_in_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_44_out_ap_vld = 1'b1;
    end else begin
        local_in_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_45_out_ap_vld = 1'b1;
    end else begin
        local_in_45_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_46_out_ap_vld = 1'b1;
    end else begin
        local_in_46_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_47_out_ap_vld = 1'b1;
    end else begin
        local_in_47_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_48_out_ap_vld = 1'b1;
    end else begin
        local_in_48_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln21_fu_825_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_49_out_ap_vld = 1'b1;
    end else begin
        local_in_49_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_831_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = ((icmp_ln21_reg_1311 == 1'd0) & (in_r_TVALID == 1'b0));
end

always @ (*) begin
    ap_condition_520 = ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln21_reg_1311 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_547 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((i_1_reg_1307 == 5'd24) | ((i_1_reg_1307 == 5'd25) | ((i_1_reg_1307 == 5'd26) | ((i_1_reg_1307 == 5'd27) | ((i_1_reg_1307 == 5'd28) | ((i_1_reg_1307 == 5'd29) | ((i_1_reg_1307 == 5'd30) | (i_1_reg_1307 == 5'd31)))))))));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign current_id_5_out = current_id_5_fu_208;

assign current_id_6_fu_994_p3 = ((icmp_ln25_reg_1315[0:0] == 1'b1) ? in_r_TID : current_id_5_fu_208);

assign icmp_ln21_fu_825_p2 = ((ap_sig_allocacmp_i_1 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_837_p2 = ((ap_sig_allocacmp_i_1 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_843_p2 = ((ap_sig_allocacmp_i_1 == 5'd24) ? 1'b1 : 1'b0);

assign is_last_sample_6_fu_1001_p3 = ((icmp_ln26_reg_1320[0:0] == 1'b1) ? in_r_TLAST : is_last_sample_reg_675);

assign is_last_sample_8_out = is_last_sample_reg_675;

assign local_in_25_out = local_in_25_fu_216;

assign local_in_26_out = local_in_26_fu_220;

assign local_in_27_out = local_in_27_fu_224;

assign local_in_28_out = local_in_28_fu_228;

assign local_in_29_out = local_in_29_fu_232;

assign local_in_30_out = local_in_30_fu_236;

assign local_in_31_out = local_in_31_fu_240;

assign local_in_32_out = local_in_32_fu_244;

assign local_in_33_out = local_in_33_fu_248;

assign local_in_34_out = local_in_34_fu_252;

assign local_in_35_out = local_in_35_fu_256;

assign local_in_36_out = local_in_36_fu_260;

assign local_in_37_out = local_in_37_fu_264;

assign local_in_38_out = local_in_38_fu_268;

assign local_in_39_out = local_in_39_fu_272;

assign local_in_40_out = local_in_40_fu_276;

assign local_in_41_out = local_in_41_fu_280;

assign local_in_42_out = local_in_42_fu_284;

assign local_in_43_out = local_in_43_fu_288;

assign local_in_44_out = local_in_44_fu_292;

assign local_in_45_out = local_in_45_fu_296;

assign local_in_46_out = local_in_46_fu_300;

assign local_in_47_out = local_in_47_fu_304;

assign local_in_48_out = local_in_48_fu_308;

assign local_in_49_out = local_in_49_fu_312;

endmodule //bnn_compute_L1_Pipeline_LOAD_L1
