// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_compute_L1 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        in_r_TDATA,
        in_r_TVALID,
        in_r_TREADY,
        in_r_TKEEP,
        in_r_TSTRB,
        in_r_TLAST,
        in_r_TID,
        l1_to_l2_din,
        l1_to_l2_full_n,
        l1_to_l2_write,
        l1_to_l2_num_data_valid,
        l1_to_l2_fifo_cap
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] in_r_TDATA;
input   in_r_TVALID;
output   in_r_TREADY;
input  [3:0] in_r_TKEEP;
input  [3:0] in_r_TSTRB;
input  [0:0] in_r_TLAST;
input  [31:0] in_r_TID;
output  [64:0] l1_to_l2_din;
input   l1_to_l2_full_n;
output   l1_to_l2_write;
input  [2:0] l1_to_l2_num_data_valid;
input  [2:0] l1_to_l2_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg[64:0] l1_to_l2_din;
reg l1_to_l2_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [5:0] p_ZL10WEIGHTS_L1_0_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_0_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_0_q1;
wire   [31:0] p_ZL10WEIGHTS_L1_0_q2;
wire   [5:0] p_ZL10WEIGHTS_L1_1_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_1_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_1_q1;
wire   [31:0] p_ZL10WEIGHTS_L1_1_q2;
wire   [5:0] p_ZL10WEIGHTS_L1_2_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_2_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_2_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_3_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_3_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_3_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_4_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_4_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_4_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_5_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_5_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_5_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_6_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_6_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_6_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_7_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_7_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_7_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_8_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_8_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_8_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_9_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_9_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_9_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_10_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_10_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_10_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_11_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_11_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_11_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_12_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_12_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_12_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_13_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_13_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_13_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_14_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_14_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_14_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_15_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_15_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_15_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_16_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_16_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_16_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_17_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_17_q0;
wire   [31:0] p_ZL10WEIGHTS_L1_17_q1;
wire   [5:0] p_ZL10WEIGHTS_L1_18_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_18_q0;
wire   [5:0] p_ZL10WEIGHTS_L1_19_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_19_q0;
wire   [5:0] p_ZL10WEIGHTS_L1_20_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_20_q0;
wire   [5:0] p_ZL10WEIGHTS_L1_21_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_21_q0;
wire   [5:0] p_ZL10WEIGHTS_L1_22_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_22_q0;
wire   [5:0] p_ZL10WEIGHTS_L1_23_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_23_q0;
wire   [5:0] p_ZL10WEIGHTS_L1_24_address0;
wire   [31:0] p_ZL10WEIGHTS_L1_24_q0;
reg    l1_to_l2_blk_n;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [5:0] tmp_s_reg_3485;
wire    ap_CS_fsm_state5;
wire   [7:0] add_ln69_fu_1621_p2;
reg   [7:0] add_ln69_reg_3615;
wire   [0:0] p2_last_fu_1635_p2;
reg   [0:0] p2_last_reg_3620;
wire   [11:0] empty_fu_1755_p2;
reg   [11:0] empty_reg_3625;
wire    ap_CS_fsm_state6;
wire   [10:0] empty_105_fu_1761_p1;
reg   [10:0] empty_105_reg_3630;
reg   [31:0] p_ZL10WEIGHTS_L1_0_load_reg_3636;
reg   [31:0] p_ZL10WEIGHTS_L1_1_load_reg_3641;
reg   [31:0] p_ZL10WEIGHTS_L1_2_load_reg_3646;
reg   [31:0] p_ZL10WEIGHTS_L1_3_load_reg_3651;
reg   [31:0] p_ZL10WEIGHTS_L1_4_load_reg_3656;
reg   [31:0] p_ZL10WEIGHTS_L1_5_load_reg_3661;
reg   [31:0] p_ZL10WEIGHTS_L1_6_load_reg_3666;
reg   [31:0] p_ZL10WEIGHTS_L1_7_load_reg_3671;
reg   [31:0] p_ZL10WEIGHTS_L1_8_load_reg_3676;
reg   [31:0] p_ZL10WEIGHTS_L1_9_load_reg_3681;
reg   [31:0] p_ZL10WEIGHTS_L1_10_load_reg_3686;
reg   [31:0] p_ZL10WEIGHTS_L1_11_load_reg_3691;
reg   [31:0] p_ZL10WEIGHTS_L1_12_load_reg_3696;
reg   [31:0] p_ZL10WEIGHTS_L1_13_load_reg_3701;
reg   [31:0] p_ZL10WEIGHTS_L1_14_load_reg_3706;
reg   [31:0] p_ZL10WEIGHTS_L1_15_load_reg_3711;
reg   [31:0] p_ZL10WEIGHTS_L1_16_load_reg_3716;
reg   [31:0] p_ZL10WEIGHTS_L1_17_load_reg_3721;
reg   [31:0] p_ZL10WEIGHTS_L1_18_load_reg_3726;
reg   [31:0] p_ZL10WEIGHTS_L1_19_load_reg_3731;
reg   [31:0] p_ZL10WEIGHTS_L1_20_load_reg_3736;
reg   [31:0] p_ZL10WEIGHTS_L1_21_load_reg_3741;
reg   [31:0] p_ZL10WEIGHTS_L1_22_load_reg_3746;
reg   [31:0] p_ZL10WEIGHTS_L1_23_load_reg_3751;
reg   [31:0] p_ZL10WEIGHTS_L1_24_load_reg_3756;
wire   [10:0] empty_106_fu_1765_p2;
reg   [10:0] empty_106_reg_3761;
wire    ap_CS_fsm_state7;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_start;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_done;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_idle;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_ready;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_in_r_TREADY;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_49_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_49_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_48_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_48_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_47_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_47_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_46_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_46_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_45_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_45_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_44_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_44_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_43_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_43_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_42_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_42_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_41_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_41_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_40_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_40_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_39_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_39_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_38_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_38_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_37_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_37_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_36_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_36_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_35_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_35_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_34_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_34_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_33_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_33_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_32_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_32_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_31_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_31_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_30_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_30_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_29_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_29_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_28_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_28_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_27_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_27_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_26_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_26_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_25_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_25_out_ap_vld;
wire   [0:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_is_last_sample_8_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_is_last_sample_8_out_ap_vld;
wire   [31:0] grp_compute_L1_Pipeline_LOAD_L1_fu_1038_current_id_5_out;
wire    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_current_id_5_out_ap_vld;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_start;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_done;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_idle;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_ready;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out1;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out1_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out2;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out2_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out3;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out3_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out4;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out4_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out5;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out5_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out6;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out6_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out7;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out7_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out8;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out8_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out9;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out9_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out10;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out10_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out11;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out11_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out12;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out12_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out13;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out13_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out14;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out14_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out15;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out15_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out16;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out16_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out17;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out17_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out18;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out18_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out19;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out19_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out20;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out20_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out21;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out21_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out22;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out22_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out23;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out23_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out24;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out24_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out25;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out25_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out26;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out26_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out27;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out27_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out28;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out28_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out29;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out29_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out30;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out30_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out31;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out31_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out32;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out32_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out33;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out33_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out34;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out34_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out35;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out35_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out36;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out36_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out37;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out37_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out38;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out38_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out39;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out39_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out40;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out40_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out41;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out41_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out42;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out42_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out43;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out43_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out44;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out44_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out45;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out45_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out46;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out46_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out47;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out47_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out48;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out48_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out49;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out49_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out50;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out50_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out51;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out51_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out52;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out52_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out53;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out53_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out54;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out54_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out55;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out55_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out56;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out56_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out57;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out57_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out58;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out58_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out59;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out59_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out60;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out60_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out61;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out61_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out62;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out62_ap_vld;
wire   [10:0] grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out63;
wire    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out63_ap_vld;
wire   [0:0] ap_phi_mux_is_last_sample_phi_fu_1020_p4;
reg   [0:0] is_last_sample_reg_1016;
reg    ap_block_state1;
wire   [0:0] tmp_fu_1562_p3;
reg   [7:0] n_reg_1027;
wire    ap_CS_fsm_state4;
reg    grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_start_reg;
wire    ap_CS_fsm_state8;
wire   [63:0] p_udiv1_cast_cast_cast_cast_fu_1588_p3;
reg   [31:0] current_id_fu_216;
reg   [31:0] local_in_fu_220;
reg   [31:0] local_in_1_fu_224;
reg   [31:0] local_in_2_fu_228;
reg   [31:0] local_in_3_fu_232;
reg   [31:0] local_in_4_fu_236;
reg   [31:0] local_in_5_fu_240;
reg   [31:0] local_in_6_fu_244;
reg   [31:0] local_in_7_fu_248;
reg   [31:0] local_in_8_fu_252;
reg   [31:0] local_in_9_fu_256;
reg   [31:0] local_in_10_fu_260;
reg   [31:0] local_in_11_fu_264;
reg   [31:0] local_in_12_fu_268;
reg   [31:0] local_in_13_fu_272;
reg   [31:0] local_in_14_fu_276;
reg   [31:0] local_in_15_fu_280;
reg   [31:0] local_in_16_fu_284;
reg   [31:0] local_in_17_fu_288;
reg   [31:0] local_in_18_fu_292;
reg   [31:0] local_in_19_fu_296;
reg   [31:0] local_in_20_fu_300;
reg   [31:0] local_in_21_fu_304;
reg   [31:0] local_in_22_fu_308;
reg   [31:0] local_in_23_fu_312;
reg   [31:0] local_in_24_fu_316;
wire   [64:0] zext_ln72_fu_2192_p1;
wire   [64:0] or_ln73_3_fu_2549_p35;
reg    p_ZL10WEIGHTS_L1_0_ce0_local;
reg    p_ZL10WEIGHTS_L1_1_ce0_local;
reg    p_ZL10WEIGHTS_L1_2_ce0_local;
reg    p_ZL10WEIGHTS_L1_3_ce0_local;
reg    p_ZL10WEIGHTS_L1_4_ce0_local;
reg    p_ZL10WEIGHTS_L1_5_ce0_local;
reg    p_ZL10WEIGHTS_L1_6_ce0_local;
reg    p_ZL10WEIGHTS_L1_7_ce0_local;
reg    p_ZL10WEIGHTS_L1_8_ce0_local;
reg    p_ZL10WEIGHTS_L1_9_ce0_local;
reg    p_ZL10WEIGHTS_L1_10_ce0_local;
reg    p_ZL10WEIGHTS_L1_11_ce0_local;
reg    p_ZL10WEIGHTS_L1_12_ce0_local;
reg    p_ZL10WEIGHTS_L1_13_ce0_local;
reg    p_ZL10WEIGHTS_L1_14_ce0_local;
reg    p_ZL10WEIGHTS_L1_15_ce0_local;
reg    p_ZL10WEIGHTS_L1_16_ce0_local;
reg    p_ZL10WEIGHTS_L1_17_ce0_local;
reg    p_ZL10WEIGHTS_L1_18_ce0_local;
reg    p_ZL10WEIGHTS_L1_19_ce0_local;
reg    p_ZL10WEIGHTS_L1_20_ce0_local;
reg    p_ZL10WEIGHTS_L1_21_ce0_local;
reg    p_ZL10WEIGHTS_L1_22_ce0_local;
reg    p_ZL10WEIGHTS_L1_23_ce0_local;
reg    p_ZL10WEIGHTS_L1_24_ce0_local;
wire   [0:0] tmp_2695_fu_1580_p3;
wire   [0:0] end_of_neurons_fu_1627_p3;
wire   [6:0] tmp_10_fu_1744_p3;
wire   [6:0] empty_fu_1755_p0;
wire   [5:0] empty_fu_1755_p1;
wire   [0:0] tmp_2726_fu_2107_p3;
wire   [0:0] tmp_2696_fu_1867_p3;
wire   [0:0] tmp_2697_fu_1875_p3;
wire   [0:0] tmp_2698_fu_1883_p3;
wire   [0:0] tmp_2699_fu_1891_p3;
wire   [0:0] tmp_2700_fu_1899_p3;
wire   [0:0] tmp_2701_fu_1907_p3;
wire   [0:0] tmp_2702_fu_1915_p3;
wire   [0:0] tmp_2703_fu_1923_p3;
wire   [0:0] tmp_2704_fu_1931_p3;
wire   [0:0] tmp_2705_fu_1939_p3;
wire   [0:0] tmp_2706_fu_1947_p3;
wire   [0:0] tmp_2707_fu_1955_p3;
wire   [0:0] tmp_2708_fu_1963_p3;
wire   [0:0] tmp_2709_fu_1971_p3;
wire   [0:0] tmp_2710_fu_1979_p3;
wire   [0:0] tmp_2711_fu_1987_p3;
wire   [0:0] tmp_2712_fu_1995_p3;
wire   [0:0] tmp_2713_fu_2003_p3;
wire   [0:0] tmp_2714_fu_2011_p3;
wire   [0:0] tmp_2715_fu_2019_p3;
wire   [0:0] tmp_2716_fu_2027_p3;
wire   [0:0] tmp_2717_fu_2035_p3;
wire   [0:0] tmp_2718_fu_2043_p3;
wire   [0:0] tmp_2719_fu_2051_p3;
wire   [0:0] tmp_2720_fu_2059_p3;
wire   [0:0] tmp_2721_fu_2067_p3;
wire   [0:0] tmp_2722_fu_2075_p3;
wire   [0:0] tmp_2723_fu_2083_p3;
wire   [0:0] tmp_2724_fu_2091_p3;
wire   [0:0] tmp_2725_fu_2099_p3;
wire   [0:0] tmp_2727_fu_2115_p3;
wire   [63:0] tmp_11_fu_2123_p34;
wire   [0:0] tmp_2758_fu_2533_p3;
wire   [0:0] tmp_2728_fu_2293_p3;
wire   [0:0] tmp_2729_fu_2301_p3;
wire   [0:0] tmp_2730_fu_2309_p3;
wire   [0:0] tmp_2731_fu_2317_p3;
wire   [0:0] tmp_2732_fu_2325_p3;
wire   [0:0] tmp_2733_fu_2333_p3;
wire   [0:0] tmp_2734_fu_2341_p3;
wire   [0:0] tmp_2735_fu_2349_p3;
wire   [0:0] tmp_2736_fu_2357_p3;
wire   [0:0] tmp_2737_fu_2365_p3;
wire   [0:0] tmp_2738_fu_2373_p3;
wire   [0:0] tmp_2739_fu_2381_p3;
wire   [0:0] tmp_2740_fu_2389_p3;
wire   [0:0] tmp_2741_fu_2397_p3;
wire   [0:0] tmp_2742_fu_2405_p3;
wire   [0:0] tmp_2743_fu_2413_p3;
wire   [0:0] tmp_2744_fu_2421_p3;
wire   [0:0] tmp_2745_fu_2429_p3;
wire   [0:0] tmp_2746_fu_2437_p3;
wire   [0:0] tmp_2747_fu_2445_p3;
wire   [0:0] tmp_2748_fu_2453_p3;
wire   [0:0] tmp_2749_fu_2461_p3;
wire   [0:0] tmp_2750_fu_2469_p3;
wire   [0:0] tmp_2751_fu_2477_p3;
wire   [0:0] tmp_2752_fu_2485_p3;
wire   [0:0] tmp_2753_fu_2493_p3;
wire   [0:0] tmp_2754_fu_2501_p3;
wire   [0:0] tmp_2755_fu_2509_p3;
wire   [0:0] tmp_2756_fu_2517_p3;
wire   [0:0] tmp_2757_fu_2525_p3;
wire   [0:0] tmp_2759_fu_2541_p3;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    regslice_both_in_r_V_data_V_U_apdone_blk;
wire   [31:0] in_r_TDATA_int_regslice;
wire    in_r_TVALID_int_regslice;
reg    in_r_TREADY_int_regslice;
wire    regslice_both_in_r_V_data_V_U_ack_in;
wire    regslice_both_in_r_V_keep_V_U_apdone_blk;
wire   [3:0] in_r_TKEEP_int_regslice;
wire    regslice_both_in_r_V_keep_V_U_vld_out;
wire    regslice_both_in_r_V_keep_V_U_ack_in;
wire    regslice_both_in_r_V_strb_V_U_apdone_blk;
wire   [3:0] in_r_TSTRB_int_regslice;
wire    regslice_both_in_r_V_strb_V_U_vld_out;
wire    regslice_both_in_r_V_strb_V_U_ack_in;
wire    regslice_both_in_r_V_last_V_U_apdone_blk;
wire   [0:0] in_r_TLAST_int_regslice;
wire    regslice_both_in_r_V_last_V_U_vld_out;
wire    regslice_both_in_r_V_last_V_U_ack_in;
wire    regslice_both_in_r_V_id_V_U_apdone_blk;
wire   [31:0] in_r_TID_int_regslice;
wire    regslice_both_in_r_V_id_V_U_vld_out;
wire    regslice_both_in_r_V_id_V_U_ack_in;
wire   [11:0] empty_fu_1755_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_start_reg = 1'b0;
#0 grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_start_reg = 1'b0;
#0 current_id_fu_216 = 32'd0;
#0 local_in_fu_220 = 32'd0;
#0 local_in_1_fu_224 = 32'd0;
#0 local_in_2_fu_228 = 32'd0;
#0 local_in_3_fu_232 = 32'd0;
#0 local_in_4_fu_236 = 32'd0;
#0 local_in_5_fu_240 = 32'd0;
#0 local_in_6_fu_244 = 32'd0;
#0 local_in_7_fu_248 = 32'd0;
#0 local_in_8_fu_252 = 32'd0;
#0 local_in_9_fu_256 = 32'd0;
#0 local_in_10_fu_260 = 32'd0;
#0 local_in_11_fu_264 = 32'd0;
#0 local_in_12_fu_268 = 32'd0;
#0 local_in_13_fu_272 = 32'd0;
#0 local_in_14_fu_276 = 32'd0;
#0 local_in_15_fu_280 = 32'd0;
#0 local_in_16_fu_284 = 32'd0;
#0 local_in_17_fu_288 = 32'd0;
#0 local_in_18_fu_292 = 32'd0;
#0 local_in_19_fu_296 = 32'd0;
#0 local_in_20_fu_300 = 32'd0;
#0 local_in_21_fu_304 = 32'd0;
#0 local_in_22_fu_308 = 32'd0;
#0 local_in_23_fu_312 = 32'd0;
#0 local_in_24_fu_316 = 32'd0;
end

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_0_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_0_address0),
    .ce0(p_ZL10WEIGHTS_L1_0_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_0_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_0_q1),
    .address2(6'd0),
    .ce2(1'b0),
    .q2(p_ZL10WEIGHTS_L1_0_q2)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_1_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_1_address0),
    .ce0(p_ZL10WEIGHTS_L1_1_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_1_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_1_q1),
    .address2(6'd0),
    .ce2(1'b0),
    .q2(p_ZL10WEIGHTS_L1_1_q2)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_2_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_2_address0),
    .ce0(p_ZL10WEIGHTS_L1_2_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_2_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_2_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_3_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_3_address0),
    .ce0(p_ZL10WEIGHTS_L1_3_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_3_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_3_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_4_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_4_address0),
    .ce0(p_ZL10WEIGHTS_L1_4_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_4_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_4_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_5_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_5_address0),
    .ce0(p_ZL10WEIGHTS_L1_5_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_5_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_5_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_6_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_6_address0),
    .ce0(p_ZL10WEIGHTS_L1_6_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_6_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_6_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_7_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_7_address0),
    .ce0(p_ZL10WEIGHTS_L1_7_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_7_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_7_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_8_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_8_address0),
    .ce0(p_ZL10WEIGHTS_L1_8_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_8_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_8_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_9_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_9_address0),
    .ce0(p_ZL10WEIGHTS_L1_9_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_9_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_9_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_10_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_10_address0),
    .ce0(p_ZL10WEIGHTS_L1_10_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_10_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_10_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_11_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_11_address0),
    .ce0(p_ZL10WEIGHTS_L1_11_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_11_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_11_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_12_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_12_address0),
    .ce0(p_ZL10WEIGHTS_L1_12_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_12_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_12_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_13_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_13_address0),
    .ce0(p_ZL10WEIGHTS_L1_13_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_13_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_13_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_14_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_14_address0),
    .ce0(p_ZL10WEIGHTS_L1_14_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_14_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_14_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_15_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_15_address0),
    .ce0(p_ZL10WEIGHTS_L1_15_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_15_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_15_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_16_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_16_address0),
    .ce0(p_ZL10WEIGHTS_L1_16_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_16_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_16_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_17_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_17_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_17_address0),
    .ce0(p_ZL10WEIGHTS_L1_17_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_17_q0),
    .address1(6'd0),
    .ce1(1'b0),
    .q1(p_ZL10WEIGHTS_L1_17_q1)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_18_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_18_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_18_address0),
    .ce0(p_ZL10WEIGHTS_L1_18_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_18_q0)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_19_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_19_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_19_address0),
    .ce0(p_ZL10WEIGHTS_L1_19_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_19_q0)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_20_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_20_address0),
    .ce0(p_ZL10WEIGHTS_L1_20_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_20_q0)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_21_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_21_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_21_address0),
    .ce0(p_ZL10WEIGHTS_L1_21_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_21_q0)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_22_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_22_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_22_address0),
    .ce0(p_ZL10WEIGHTS_L1_22_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_22_q0)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_23_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_23_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_23_address0),
    .ce0(p_ZL10WEIGHTS_L1_23_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_23_q0)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD_p_ZL10WEIGHTS_L1_24_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
p_ZL10WEIGHTS_L1_24_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL10WEIGHTS_L1_24_address0),
    .ce0(p_ZL10WEIGHTS_L1_24_ce0_local),
    .q0(p_ZL10WEIGHTS_L1_24_q0)
);

bnn_compute_L1_Pipeline_LOAD_L1 grp_compute_L1_Pipeline_LOAD_L1_fu_1038(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_start),
    .ap_done(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_done),
    .ap_idle(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_idle),
    .ap_ready(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_ready),
    .in_r_TVALID(in_r_TVALID_int_regslice),
    .local_in_24(local_in_24_fu_316),
    .local_in_23(local_in_23_fu_312),
    .local_in_22(local_in_22_fu_308),
    .local_in_21(local_in_21_fu_304),
    .local_in_20(local_in_20_fu_300),
    .local_in_19(local_in_19_fu_296),
    .local_in_18(local_in_18_fu_292),
    .local_in_17(local_in_17_fu_288),
    .local_in_16(local_in_16_fu_284),
    .local_in_15(local_in_15_fu_280),
    .local_in_14(local_in_14_fu_276),
    .local_in_13(local_in_13_fu_272),
    .local_in_12(local_in_12_fu_268),
    .local_in_11(local_in_11_fu_264),
    .local_in_10(local_in_10_fu_260),
    .local_in_9(local_in_9_fu_256),
    .local_in_8(local_in_8_fu_252),
    .local_in_7(local_in_7_fu_248),
    .local_in_6(local_in_6_fu_244),
    .local_in_5(local_in_5_fu_240),
    .local_in_4(local_in_4_fu_236),
    .local_in_3(local_in_3_fu_232),
    .local_in_2(local_in_2_fu_228),
    .local_in_1(local_in_1_fu_224),
    .local_in(local_in_fu_220),
    .current_id(current_id_fu_216),
    .in_r_TDATA(in_r_TDATA_int_regslice),
    .in_r_TREADY(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_in_r_TREADY),
    .in_r_TKEEP(in_r_TKEEP_int_regslice),
    .in_r_TSTRB(in_r_TSTRB_int_regslice),
    .in_r_TLAST(in_r_TLAST_int_regslice),
    .in_r_TID(in_r_TID_int_regslice),
    .local_in_49_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_49_out),
    .local_in_49_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_49_out_ap_vld),
    .local_in_48_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_48_out),
    .local_in_48_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_48_out_ap_vld),
    .local_in_47_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_47_out),
    .local_in_47_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_47_out_ap_vld),
    .local_in_46_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_46_out),
    .local_in_46_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_46_out_ap_vld),
    .local_in_45_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_45_out),
    .local_in_45_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_45_out_ap_vld),
    .local_in_44_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_44_out),
    .local_in_44_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_44_out_ap_vld),
    .local_in_43_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_43_out),
    .local_in_43_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_43_out_ap_vld),
    .local_in_42_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_42_out),
    .local_in_42_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_42_out_ap_vld),
    .local_in_41_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_41_out),
    .local_in_41_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_41_out_ap_vld),
    .local_in_40_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_40_out),
    .local_in_40_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_40_out_ap_vld),
    .local_in_39_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_39_out),
    .local_in_39_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_39_out_ap_vld),
    .local_in_38_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_38_out),
    .local_in_38_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_38_out_ap_vld),
    .local_in_37_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_37_out),
    .local_in_37_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_37_out_ap_vld),
    .local_in_36_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_36_out),
    .local_in_36_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_36_out_ap_vld),
    .local_in_35_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_35_out),
    .local_in_35_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_35_out_ap_vld),
    .local_in_34_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_34_out),
    .local_in_34_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_34_out_ap_vld),
    .local_in_33_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_33_out),
    .local_in_33_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_33_out_ap_vld),
    .local_in_32_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_32_out),
    .local_in_32_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_32_out_ap_vld),
    .local_in_31_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_31_out),
    .local_in_31_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_31_out_ap_vld),
    .local_in_30_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_30_out),
    .local_in_30_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_30_out_ap_vld),
    .local_in_29_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_29_out),
    .local_in_29_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_29_out_ap_vld),
    .local_in_28_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_28_out),
    .local_in_28_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_28_out_ap_vld),
    .local_in_27_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_27_out),
    .local_in_27_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_27_out_ap_vld),
    .local_in_26_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_26_out),
    .local_in_26_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_26_out_ap_vld),
    .local_in_25_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_25_out),
    .local_in_25_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_25_out_ap_vld),
    .is_last_sample_8_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_is_last_sample_8_out),
    .is_last_sample_8_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_is_last_sample_8_out_ap_vld),
    .current_id_5_out(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_current_id_5_out),
    .current_id_5_out_ap_vld(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_current_id_5_out_ap_vld)
);

bnn_compute_L1_Pipeline_L1_DOT_PROD grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_start),
    .ap_done(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_done),
    .ap_idle(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_idle),
    .ap_ready(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_ready),
    .local_in_25_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_25_out),
    .local_in_26_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_26_out),
    .local_in_27_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_27_out),
    .local_in_28_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_28_out),
    .local_in_29_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_29_out),
    .local_in_30_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_30_out),
    .local_in_31_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_31_out),
    .local_in_32_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_32_out),
    .local_in_33_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_33_out),
    .local_in_34_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_34_out),
    .local_in_35_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_35_out),
    .local_in_36_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_36_out),
    .local_in_37_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_37_out),
    .local_in_38_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_38_out),
    .local_in_39_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_39_out),
    .local_in_40_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_40_out),
    .local_in_41_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_41_out),
    .local_in_42_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_42_out),
    .local_in_43_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_43_out),
    .local_in_44_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_44_out),
    .local_in_45_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_45_out),
    .local_in_46_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_46_out),
    .local_in_47_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_47_out),
    .local_in_48_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_48_out),
    .local_in_49_reload(grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_49_out),
    .p_ZL10WEIGHTS_L1_0_load(p_ZL10WEIGHTS_L1_0_load_reg_3636),
    .p_ZL10WEIGHTS_L1_1_load(p_ZL10WEIGHTS_L1_1_load_reg_3641),
    .p_ZL10WEIGHTS_L1_2_load(p_ZL10WEIGHTS_L1_2_load_reg_3646),
    .p_ZL10WEIGHTS_L1_3_load(p_ZL10WEIGHTS_L1_3_load_reg_3651),
    .p_ZL10WEIGHTS_L1_4_load(p_ZL10WEIGHTS_L1_4_load_reg_3656),
    .p_ZL10WEIGHTS_L1_5_load(p_ZL10WEIGHTS_L1_5_load_reg_3661),
    .p_ZL10WEIGHTS_L1_6_load(p_ZL10WEIGHTS_L1_6_load_reg_3666),
    .p_ZL10WEIGHTS_L1_7_load(p_ZL10WEIGHTS_L1_7_load_reg_3671),
    .p_ZL10WEIGHTS_L1_8_load(p_ZL10WEIGHTS_L1_8_load_reg_3676),
    .p_ZL10WEIGHTS_L1_9_load(p_ZL10WEIGHTS_L1_9_load_reg_3681),
    .p_ZL10WEIGHTS_L1_10_load(p_ZL10WEIGHTS_L1_10_load_reg_3686),
    .p_ZL10WEIGHTS_L1_11_load(p_ZL10WEIGHTS_L1_11_load_reg_3691),
    .p_ZL10WEIGHTS_L1_12_load(p_ZL10WEIGHTS_L1_12_load_reg_3696),
    .p_ZL10WEIGHTS_L1_13_load(p_ZL10WEIGHTS_L1_13_load_reg_3701),
    .p_ZL10WEIGHTS_L1_14_load(p_ZL10WEIGHTS_L1_14_load_reg_3706),
    .p_ZL10WEIGHTS_L1_15_load(p_ZL10WEIGHTS_L1_15_load_reg_3711),
    .p_ZL10WEIGHTS_L1_16_load(p_ZL10WEIGHTS_L1_16_load_reg_3716),
    .p_ZL10WEIGHTS_L1_17_load(p_ZL10WEIGHTS_L1_17_load_reg_3721),
    .p_ZL10WEIGHTS_L1_18_load(p_ZL10WEIGHTS_L1_18_load_reg_3726),
    .p_ZL10WEIGHTS_L1_19_load(p_ZL10WEIGHTS_L1_19_load_reg_3731),
    .p_ZL10WEIGHTS_L1_20_load(p_ZL10WEIGHTS_L1_20_load_reg_3736),
    .p_ZL10WEIGHTS_L1_21_load(p_ZL10WEIGHTS_L1_21_load_reg_3741),
    .p_ZL10WEIGHTS_L1_22_load(p_ZL10WEIGHTS_L1_22_load_reg_3746),
    .p_ZL10WEIGHTS_L1_23_load(p_ZL10WEIGHTS_L1_23_load_reg_3751),
    .p_ZL10WEIGHTS_L1_24_load(p_ZL10WEIGHTS_L1_24_load_reg_3756),
    .empty_30(empty_105_reg_3630),
    .p_cast628(empty_106_reg_3761),
    .empty(empty_reg_3625),
    .p_out(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out),
    .p_out_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out_ap_vld),
    .p_out1(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out1),
    .p_out1_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out1_ap_vld),
    .p_out2(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out2),
    .p_out2_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out2_ap_vld),
    .p_out3(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out3),
    .p_out3_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out3_ap_vld),
    .p_out4(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out4),
    .p_out4_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out4_ap_vld),
    .p_out5(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out5),
    .p_out5_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out5_ap_vld),
    .p_out6(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out6),
    .p_out6_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out6_ap_vld),
    .p_out7(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out7),
    .p_out7_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out7_ap_vld),
    .p_out8(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out8),
    .p_out8_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out8_ap_vld),
    .p_out9(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out9),
    .p_out9_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out9_ap_vld),
    .p_out10(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out10),
    .p_out10_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out10_ap_vld),
    .p_out11(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out11),
    .p_out11_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out11_ap_vld),
    .p_out12(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out12),
    .p_out12_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out12_ap_vld),
    .p_out13(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out13),
    .p_out13_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out13_ap_vld),
    .p_out14(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out14),
    .p_out14_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out14_ap_vld),
    .p_out15(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out15),
    .p_out15_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out15_ap_vld),
    .p_out16(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out16),
    .p_out16_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out16_ap_vld),
    .p_out17(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out17),
    .p_out17_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out17_ap_vld),
    .p_out18(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out18),
    .p_out18_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out18_ap_vld),
    .p_out19(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out19),
    .p_out19_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out19_ap_vld),
    .p_out20(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out20),
    .p_out20_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out20_ap_vld),
    .p_out21(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out21),
    .p_out21_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out21_ap_vld),
    .p_out22(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out22),
    .p_out22_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out22_ap_vld),
    .p_out23(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out23),
    .p_out23_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out23_ap_vld),
    .p_out24(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out24),
    .p_out24_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out24_ap_vld),
    .p_out25(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out25),
    .p_out25_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out25_ap_vld),
    .p_out26(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out26),
    .p_out26_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out26_ap_vld),
    .p_out27(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out27),
    .p_out27_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out27_ap_vld),
    .p_out28(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out28),
    .p_out28_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out28_ap_vld),
    .p_out29(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out29),
    .p_out29_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out29_ap_vld),
    .p_out30(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out30),
    .p_out30_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out30_ap_vld),
    .p_out31(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out31),
    .p_out31_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out31_ap_vld),
    .p_out32(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out32),
    .p_out32_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out32_ap_vld),
    .p_out33(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out33),
    .p_out33_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out33_ap_vld),
    .p_out34(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out34),
    .p_out34_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out34_ap_vld),
    .p_out35(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out35),
    .p_out35_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out35_ap_vld),
    .p_out36(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out36),
    .p_out36_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out36_ap_vld),
    .p_out37(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out37),
    .p_out37_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out37_ap_vld),
    .p_out38(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out38),
    .p_out38_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out38_ap_vld),
    .p_out39(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out39),
    .p_out39_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out39_ap_vld),
    .p_out40(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out40),
    .p_out40_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out40_ap_vld),
    .p_out41(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out41),
    .p_out41_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out41_ap_vld),
    .p_out42(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out42),
    .p_out42_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out42_ap_vld),
    .p_out43(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out43),
    .p_out43_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out43_ap_vld),
    .p_out44(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out44),
    .p_out44_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out44_ap_vld),
    .p_out45(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out45),
    .p_out45_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out45_ap_vld),
    .p_out46(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out46),
    .p_out46_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out46_ap_vld),
    .p_out47(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out47),
    .p_out47_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out47_ap_vld),
    .p_out48(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out48),
    .p_out48_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out48_ap_vld),
    .p_out49(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out49),
    .p_out49_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out49_ap_vld),
    .p_out50(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out50),
    .p_out50_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out50_ap_vld),
    .p_out51(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out51),
    .p_out51_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out51_ap_vld),
    .p_out52(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out52),
    .p_out52_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out52_ap_vld),
    .p_out53(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out53),
    .p_out53_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out53_ap_vld),
    .p_out54(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out54),
    .p_out54_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out54_ap_vld),
    .p_out55(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out55),
    .p_out55_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out55_ap_vld),
    .p_out56(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out56),
    .p_out56_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out56_ap_vld),
    .p_out57(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out57),
    .p_out57_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out57_ap_vld),
    .p_out58(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out58),
    .p_out58_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out58_ap_vld),
    .p_out59(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out59),
    .p_out59_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out59_ap_vld),
    .p_out60(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out60),
    .p_out60_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out60_ap_vld),
    .p_out61(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out61),
    .p_out61_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out61_ap_vld),
    .p_out62(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out62),
    .p_out62_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out62_ap_vld),
    .p_out63(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out63),
    .p_out63_ap_vld(grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out63_ap_vld)
);

bnn_mul_7ns_6ns_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mul_7ns_6ns_12_1_1_U330(
    .din0(empty_fu_1755_p0),
    .din1(empty_fu_1755_p1),
    .dout(empty_fu_1755_p2)
);

bnn_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_r_TDATA),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_V_data_V_U_ack_in),
    .data_out(in_r_TDATA_int_regslice),
    .vld_out(in_r_TVALID_int_regslice),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_V_data_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_r_TKEEP),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_V_keep_V_U_ack_in),
    .data_out(in_r_TKEEP_int_regslice),
    .vld_out(regslice_both_in_r_V_keep_V_U_vld_out),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_V_keep_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_r_TSTRB),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_V_strb_V_U_ack_in),
    .data_out(in_r_TSTRB_int_regslice),
    .vld_out(regslice_both_in_r_V_strb_V_U_vld_out),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_V_strb_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_r_TLAST),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_V_last_V_U_ack_in),
    .data_out(in_r_TLAST_int_regslice),
    .vld_out(regslice_both_in_r_V_last_V_U_vld_out),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_V_last_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_r_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_r_TID),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_V_id_V_U_ack_in),
    .data_out(in_r_TID_int_regslice),
    .vld_out(regslice_both_in_r_V_id_V_U_vld_out),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_V_id_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_phi_mux_is_last_sample_phi_fu_1020_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_start_reg <= 1'b1;
        end else if ((grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_ready == 1'b1)) begin
            grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_phi_mux_is_last_sample_phi_fu_1020_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_start_reg <= 1'b1;
        end else if ((grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_ready == 1'b1)) begin
            grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        current_id_fu_216 <= 32'd0;
    end else if (((tmp_fu_1562_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        current_id_fu_216 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_current_id_5_out;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_1562_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        is_last_sample_reg_1016 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_is_last_sample_8_out;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        is_last_sample_reg_1016 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        n_reg_1027 <= 8'd0;
    end else if (((l1_to_l2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        n_reg_1027 <= add_ln69_reg_3615;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln69_reg_3615 <= add_ln69_fu_1621_p2;
        p2_last_reg_3620 <= p2_last_fu_1635_p2;
        tmp_s_reg_3485 <= {{n_reg_1027[6:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        empty_105_reg_3630 <= empty_105_fu_1761_p1;
        empty_reg_3625 <= empty_fu_1755_p2;
        p_ZL10WEIGHTS_L1_0_load_reg_3636 <= p_ZL10WEIGHTS_L1_0_q0;
        p_ZL10WEIGHTS_L1_10_load_reg_3686 <= p_ZL10WEIGHTS_L1_10_q0;
        p_ZL10WEIGHTS_L1_11_load_reg_3691 <= p_ZL10WEIGHTS_L1_11_q0;
        p_ZL10WEIGHTS_L1_12_load_reg_3696 <= p_ZL10WEIGHTS_L1_12_q0;
        p_ZL10WEIGHTS_L1_13_load_reg_3701 <= p_ZL10WEIGHTS_L1_13_q0;
        p_ZL10WEIGHTS_L1_14_load_reg_3706 <= p_ZL10WEIGHTS_L1_14_q0;
        p_ZL10WEIGHTS_L1_15_load_reg_3711 <= p_ZL10WEIGHTS_L1_15_q0;
        p_ZL10WEIGHTS_L1_16_load_reg_3716 <= p_ZL10WEIGHTS_L1_16_q0;
        p_ZL10WEIGHTS_L1_17_load_reg_3721 <= p_ZL10WEIGHTS_L1_17_q0;
        p_ZL10WEIGHTS_L1_18_load_reg_3726 <= p_ZL10WEIGHTS_L1_18_q0;
        p_ZL10WEIGHTS_L1_19_load_reg_3731 <= p_ZL10WEIGHTS_L1_19_q0;
        p_ZL10WEIGHTS_L1_1_load_reg_3641 <= p_ZL10WEIGHTS_L1_1_q0;
        p_ZL10WEIGHTS_L1_20_load_reg_3736 <= p_ZL10WEIGHTS_L1_20_q0;
        p_ZL10WEIGHTS_L1_21_load_reg_3741 <= p_ZL10WEIGHTS_L1_21_q0;
        p_ZL10WEIGHTS_L1_22_load_reg_3746 <= p_ZL10WEIGHTS_L1_22_q0;
        p_ZL10WEIGHTS_L1_23_load_reg_3751 <= p_ZL10WEIGHTS_L1_23_q0;
        p_ZL10WEIGHTS_L1_24_load_reg_3756 <= p_ZL10WEIGHTS_L1_24_q0;
        p_ZL10WEIGHTS_L1_2_load_reg_3646 <= p_ZL10WEIGHTS_L1_2_q0;
        p_ZL10WEIGHTS_L1_3_load_reg_3651 <= p_ZL10WEIGHTS_L1_3_q0;
        p_ZL10WEIGHTS_L1_4_load_reg_3656 <= p_ZL10WEIGHTS_L1_4_q0;
        p_ZL10WEIGHTS_L1_5_load_reg_3661 <= p_ZL10WEIGHTS_L1_5_q0;
        p_ZL10WEIGHTS_L1_6_load_reg_3666 <= p_ZL10WEIGHTS_L1_6_q0;
        p_ZL10WEIGHTS_L1_7_load_reg_3671 <= p_ZL10WEIGHTS_L1_7_q0;
        p_ZL10WEIGHTS_L1_8_load_reg_3676 <= p_ZL10WEIGHTS_L1_8_q0;
        p_ZL10WEIGHTS_L1_9_load_reg_3681 <= p_ZL10WEIGHTS_L1_9_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        empty_106_reg_3761 <= empty_106_fu_1765_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_1562_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        local_in_10_fu_260 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_35_out;
        local_in_11_fu_264 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_36_out;
        local_in_12_fu_268 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_37_out;
        local_in_13_fu_272 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_38_out;
        local_in_14_fu_276 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_39_out;
        local_in_15_fu_280 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_40_out;
        local_in_16_fu_284 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_41_out;
        local_in_17_fu_288 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_42_out;
        local_in_18_fu_292 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_43_out;
        local_in_19_fu_296 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_44_out;
        local_in_1_fu_224 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_26_out;
        local_in_20_fu_300 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_45_out;
        local_in_21_fu_304 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_46_out;
        local_in_22_fu_308 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_47_out;
        local_in_23_fu_312 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_48_out;
        local_in_24_fu_316 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_49_out;
        local_in_2_fu_228 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_27_out;
        local_in_3_fu_232 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_28_out;
        local_in_4_fu_236 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_29_out;
        local_in_5_fu_240 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_30_out;
        local_in_6_fu_244 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_31_out;
        local_in_7_fu_248 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_32_out;
        local_in_8_fu_252 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_33_out;
        local_in_9_fu_256 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_34_out;
        local_in_fu_220 <= grp_compute_L1_Pipeline_LOAD_L1_fu_1038_local_in_25_out;
    end
end

always @ (*) begin
    if ((l1_to_l2_full_n == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((l1_to_l2_full_n == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_is_last_sample_phi_fu_1020_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_r_TREADY_int_regslice = grp_compute_L1_Pipeline_LOAD_L1_fu_1038_in_r_TREADY;
    end else begin
        in_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_is_last_sample_phi_fu_1020_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        l1_to_l2_blk_n = l1_to_l2_full_n;
    end else begin
        l1_to_l2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((l1_to_l2_full_n == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            l1_to_l2_din = or_ln73_3_fu_2549_p35;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            l1_to_l2_din = zext_ln72_fu_2192_p1;
        end else begin
            l1_to_l2_din = 'bx;
        end
    end else begin
        l1_to_l2_din = 'bx;
    end
end

always @ (*) begin
    if ((((l1_to_l2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((l1_to_l2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        l1_to_l2_write = 1'b1;
    end else begin
        l1_to_l2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_0_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_10_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_11_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_12_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_13_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_14_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_15_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_16_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_17_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_18_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_19_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_1_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_20_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_21_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_22_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_23_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_24_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_2_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_3_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_4_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_5_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_6_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_7_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_8_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZL10WEIGHTS_L1_9_ce0_local = 1'b1;
    end else begin
        p_ZL10WEIGHTS_L1_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((ap_phi_mux_is_last_sample_phi_fu_1020_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((tmp_fu_1562_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((l1_to_l2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((l1_to_l2_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln69_fu_1621_p2 = (n_reg_1027 + 8'd64);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_phi_mux_is_last_sample_phi_fu_1020_p4 = is_last_sample_reg_1016;

assign ap_ready = internal_ap_ready;

assign empty_105_fu_1761_p1 = empty_fu_1755_p2[10:0];

assign empty_106_fu_1765_p2 = (empty_105_reg_3630 + 11'd400);

assign empty_fu_1755_p0 = empty_fu_1755_p00;

assign empty_fu_1755_p00 = tmp_10_fu_1744_p3;

assign empty_fu_1755_p1 = 12'd25;

assign end_of_neurons_fu_1627_p3 = add_ln69_fu_1621_p2[32'd7];

assign grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_start = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_ap_start_reg;

assign grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_start = grp_compute_L1_Pipeline_LOAD_L1_fu_1038_ap_start_reg;

assign in_r_TREADY = regslice_both_in_r_V_data_V_U_ack_in;

assign or_ln73_3_fu_2549_p35 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{p2_last_reg_3620}, {grp_compute_L1_Pipeline_LOAD_L1_fu_1038_current_id_5_out}}, {tmp_2758_fu_2533_p3}}, {tmp_2728_fu_2293_p3}}, {tmp_2729_fu_2301_p3}}, {tmp_2730_fu_2309_p3}}, {tmp_2731_fu_2317_p3}}, {tmp_2732_fu_2325_p3}}, {tmp_2733_fu_2333_p3}}, {tmp_2734_fu_2341_p3}}, {tmp_2735_fu_2349_p3}}, {tmp_2736_fu_2357_p3}}, {tmp_2737_fu_2365_p3}}, {tmp_2738_fu_2373_p3}}, {tmp_2739_fu_2381_p3}}, {tmp_2740_fu_2389_p3}}, {tmp_2741_fu_2397_p3}}, {tmp_2742_fu_2405_p3}}, {tmp_2743_fu_2413_p3}}, {tmp_2744_fu_2421_p3}}, {tmp_2745_fu_2429_p3}}, {tmp_2746_fu_2437_p3}}, {tmp_2747_fu_2445_p3}}, {tmp_2748_fu_2453_p3}}, {tmp_2749_fu_2461_p3}}, {tmp_2750_fu_2469_p3}}, {tmp_2751_fu_2477_p3}}, {tmp_2752_fu_2485_p3}}, {tmp_2753_fu_2493_p3}}, {tmp_2754_fu_2501_p3}}, {tmp_2755_fu_2509_p3}}, {tmp_2756_fu_2517_p3}}, {tmp_2757_fu_2525_p3}}, {tmp_2759_fu_2541_p3}};

assign p2_last_fu_1635_p2 = (grp_compute_L1_Pipeline_LOAD_L1_fu_1038_is_last_sample_8_out & end_of_neurons_fu_1627_p3);

assign p_ZL10WEIGHTS_L1_0_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_10_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_11_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_12_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_13_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_14_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_15_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_16_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_17_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_18_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_19_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_1_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_20_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_21_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_22_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_23_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_24_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_2_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_3_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_4_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_5_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_6_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_7_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_8_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_ZL10WEIGHTS_L1_9_address0 = p_udiv1_cast_cast_cast_cast_fu_1588_p3;

assign p_udiv1_cast_cast_cast_cast_fu_1588_p3 = ((tmp_2695_fu_1580_p3[0:0] == 1'b1) ? 64'd25 : 64'd0);

assign start_out = real_start;

assign tmp_10_fu_1744_p3 = {{tmp_s_reg_3485}, {1'd1}};

assign tmp_11_fu_2123_p34 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{grp_compute_L1_Pipeline_LOAD_L1_fu_1038_current_id_5_out}, {tmp_2726_fu_2107_p3}}, {tmp_2696_fu_1867_p3}}, {tmp_2697_fu_1875_p3}}, {tmp_2698_fu_1883_p3}}, {tmp_2699_fu_1891_p3}}, {tmp_2700_fu_1899_p3}}, {tmp_2701_fu_1907_p3}}, {tmp_2702_fu_1915_p3}}, {tmp_2703_fu_1923_p3}}, {tmp_2704_fu_1931_p3}}, {tmp_2705_fu_1939_p3}}, {tmp_2706_fu_1947_p3}}, {tmp_2707_fu_1955_p3}}, {tmp_2708_fu_1963_p3}}, {tmp_2709_fu_1971_p3}}, {tmp_2710_fu_1979_p3}}, {tmp_2711_fu_1987_p3}}, {tmp_2712_fu_1995_p3}}, {tmp_2713_fu_2003_p3}}, {tmp_2714_fu_2011_p3}}, {tmp_2715_fu_2019_p3}}, {tmp_2716_fu_2027_p3}}, {tmp_2717_fu_2035_p3}}, {tmp_2718_fu_2043_p3}}, {tmp_2719_fu_2051_p3}}, {tmp_2720_fu_2059_p3}}, {tmp_2721_fu_2067_p3}}, {tmp_2722_fu_2075_p3}}, {tmp_2723_fu_2083_p3}}, {tmp_2724_fu_2091_p3}}, {tmp_2725_fu_2099_p3}}, {tmp_2727_fu_2115_p3}};

assign tmp_2695_fu_1580_p3 = n_reg_1027[32'd6];

assign tmp_2696_fu_1867_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out62[32'd10];

assign tmp_2697_fu_1875_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out61[32'd10];

assign tmp_2698_fu_1883_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out60[32'd10];

assign tmp_2699_fu_1891_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out59[32'd10];

assign tmp_2700_fu_1899_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out58[32'd10];

assign tmp_2701_fu_1907_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out57[32'd10];

assign tmp_2702_fu_1915_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out56[32'd10];

assign tmp_2703_fu_1923_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out55[32'd10];

assign tmp_2704_fu_1931_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out54[32'd10];

assign tmp_2705_fu_1939_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out53[32'd10];

assign tmp_2706_fu_1947_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out52[32'd10];

assign tmp_2707_fu_1955_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out51[32'd10];

assign tmp_2708_fu_1963_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out50[32'd10];

assign tmp_2709_fu_1971_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out49[32'd10];

assign tmp_2710_fu_1979_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out48[32'd10];

assign tmp_2711_fu_1987_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out47[32'd10];

assign tmp_2712_fu_1995_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out46[32'd10];

assign tmp_2713_fu_2003_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out45[32'd10];

assign tmp_2714_fu_2011_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out44[32'd10];

assign tmp_2715_fu_2019_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out43[32'd10];

assign tmp_2716_fu_2027_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out42[32'd10];

assign tmp_2717_fu_2035_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out41[32'd10];

assign tmp_2718_fu_2043_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out40[32'd10];

assign tmp_2719_fu_2051_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out39[32'd10];

assign tmp_2720_fu_2059_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out38[32'd10];

assign tmp_2721_fu_2067_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out37[32'd10];

assign tmp_2722_fu_2075_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out36[32'd10];

assign tmp_2723_fu_2083_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out35[32'd10];

assign tmp_2724_fu_2091_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out34[32'd10];

assign tmp_2725_fu_2099_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out33[32'd10];

assign tmp_2726_fu_2107_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out63[32'd10];

assign tmp_2727_fu_2115_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out32[32'd10];

assign tmp_2728_fu_2293_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out30[32'd10];

assign tmp_2729_fu_2301_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out29[32'd10];

assign tmp_2730_fu_2309_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out28[32'd10];

assign tmp_2731_fu_2317_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out27[32'd10];

assign tmp_2732_fu_2325_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out26[32'd10];

assign tmp_2733_fu_2333_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out25[32'd10];

assign tmp_2734_fu_2341_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out24[32'd10];

assign tmp_2735_fu_2349_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out23[32'd10];

assign tmp_2736_fu_2357_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out22[32'd10];

assign tmp_2737_fu_2365_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out21[32'd10];

assign tmp_2738_fu_2373_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out20[32'd10];

assign tmp_2739_fu_2381_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out19[32'd10];

assign tmp_2740_fu_2389_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out18[32'd10];

assign tmp_2741_fu_2397_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out17[32'd10];

assign tmp_2742_fu_2405_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out16[32'd10];

assign tmp_2743_fu_2413_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out15[32'd10];

assign tmp_2744_fu_2421_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out14[32'd10];

assign tmp_2745_fu_2429_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out13[32'd10];

assign tmp_2746_fu_2437_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out12[32'd10];

assign tmp_2747_fu_2445_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out11[32'd10];

assign tmp_2748_fu_2453_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out10[32'd10];

assign tmp_2749_fu_2461_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out9[32'd10];

assign tmp_2750_fu_2469_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out8[32'd10];

assign tmp_2751_fu_2477_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out7[32'd10];

assign tmp_2752_fu_2485_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out6[32'd10];

assign tmp_2753_fu_2493_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out5[32'd10];

assign tmp_2754_fu_2501_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out4[32'd10];

assign tmp_2755_fu_2509_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out3[32'd10];

assign tmp_2756_fu_2517_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out2[32'd10];

assign tmp_2757_fu_2525_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out1[32'd10];

assign tmp_2758_fu_2533_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out31[32'd10];

assign tmp_2759_fu_2541_p3 = grp_compute_L1_Pipeline_L1_DOT_PROD_fu_1105_p_out[32'd10];

assign tmp_fu_1562_p3 = n_reg_1027[32'd7];

assign zext_ln72_fu_2192_p1 = tmp_11_fu_2123_p34;

endmodule //bnn_compute_L1
