// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_compute_L3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        l2_to_l3_dout,
        l2_to_l3_empty_n,
        l2_to_l3_read,
        l2_to_l3_num_data_valid,
        l2_to_l3_fifo_cap,
        out_r_TDATA,
        out_r_TVALID,
        out_r_TREADY,
        out_r_TKEEP,
        out_r_TSTRB,
        out_r_TLAST,
        out_r_TID
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [64:0] l2_to_l3_dout;
input   l2_to_l3_empty_n;
output   l2_to_l3_read;
input  [2:0] l2_to_l3_num_data_valid;
input  [2:0] l2_to_l3_fifo_cap;
output  [31:0] out_r_TDATA;
output   out_r_TVALID;
input   out_r_TREADY;
output  [3:0] out_r_TKEEP;
output  [3:0] out_r_TSTRB;
output  [0:0] out_r_TLAST;
output  [31:0] out_r_TID;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    out_r_TDATA_blk_n;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_start;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_done;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_idle;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_ready;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_l2_to_l3_read;
wire   [7:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out_ap_vld;
wire   [7:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out1;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out1_ap_vld;
wire   [7:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out2;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out2_ap_vld;
wire   [7:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out3;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out3_ap_vld;
wire   [7:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out4;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out4_ap_vld;
wire   [7:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out5;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out5_ap_vld;
wire   [7:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out6;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out6_ap_vld;
wire   [7:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out7;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out7_ap_vld;
wire   [7:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out8;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out8_ap_vld;
wire   [7:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out9;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out9_ap_vld;
wire   [0:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_is_last_sample_4_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_is_last_sample_4_out_ap_vld;
wire   [31:0] grp_compute_L3_Pipeline_STREAM_L3_fu_142_current_id_1_out;
wire    grp_compute_L3_Pipeline_STREAM_L3_fu_142_current_id_1_out_ap_vld;
wire    grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_start;
wire    grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_done;
wire    grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_idle;
wire    grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_ready;
wire   [31:0] grp_compute_L3_Pipeline_FIND_MAX_fu_161_max_idx_out;
wire    grp_compute_L3_Pipeline_FIND_MAX_fu_161_max_idx_out_ap_vld;
wire   [0:0] ap_phi_mux_is_last_sample_phi_fu_135_p4;
reg   [0:0] is_last_sample_reg_131;
reg    ap_block_state1;
reg    grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    regslice_both_out_r_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state3;
reg    grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [31:0] current_id_fu_54;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    out_r_TVALID_int_regslice;
wire    out_r_TREADY_int_regslice;
wire    regslice_both_out_r_V_data_V_U_vld_out;
wire    regslice_both_out_r_V_keep_V_U_apdone_blk;
wire    regslice_both_out_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_r_V_keep_V_U_vld_out;
wire    regslice_both_out_r_V_strb_V_U_apdone_blk;
wire    regslice_both_out_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_r_V_strb_V_U_vld_out;
wire    regslice_both_out_r_V_last_V_U_apdone_blk;
wire    regslice_both_out_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_r_V_last_V_U_vld_out;
wire    regslice_both_out_r_V_id_V_U_apdone_blk;
wire    regslice_both_out_r_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_r_V_id_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_start_reg = 1'b0;
#0 grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_start_reg = 1'b0;
#0 current_id_fu_54 = 32'd0;
end

bnn_compute_L3_Pipeline_STREAM_L3 grp_compute_L3_Pipeline_STREAM_L3_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_start),
    .ap_done(grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_done),
    .ap_idle(grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_idle),
    .ap_ready(grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_ready),
    .l2_to_l3_dout(l2_to_l3_dout),
    .l2_to_l3_empty_n(l2_to_l3_empty_n),
    .l2_to_l3_read(grp_compute_L3_Pipeline_STREAM_L3_fu_142_l2_to_l3_read),
    .l2_to_l3_num_data_valid(3'd0),
    .l2_to_l3_fifo_cap(3'd0),
    .current_id(current_id_fu_54),
    .p_out(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out),
    .p_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out_ap_vld),
    .p_out1(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out1),
    .p_out1_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out1_ap_vld),
    .p_out2(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out2),
    .p_out2_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out2_ap_vld),
    .p_out3(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out3),
    .p_out3_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out3_ap_vld),
    .p_out4(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out4),
    .p_out4_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out4_ap_vld),
    .p_out5(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out5),
    .p_out5_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out5_ap_vld),
    .p_out6(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out6),
    .p_out6_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out6_ap_vld),
    .p_out7(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out7),
    .p_out7_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out7_ap_vld),
    .p_out8(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out8),
    .p_out8_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out8_ap_vld),
    .p_out9(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out9),
    .p_out9_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out9_ap_vld),
    .is_last_sample_4_out(grp_compute_L3_Pipeline_STREAM_L3_fu_142_is_last_sample_4_out),
    .is_last_sample_4_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_is_last_sample_4_out_ap_vld),
    .current_id_1_out(grp_compute_L3_Pipeline_STREAM_L3_fu_142_current_id_1_out),
    .current_id_1_out_ap_vld(grp_compute_L3_Pipeline_STREAM_L3_fu_142_current_id_1_out_ap_vld)
);

bnn_compute_L3_Pipeline_FIND_MAX grp_compute_L3_Pipeline_FIND_MAX_fu_161(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_start),
    .ap_done(grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_done),
    .ap_idle(grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_idle),
    .ap_ready(grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_ready),
    .p_reload27(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out9),
    .p_reload26(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out8),
    .p_reload25(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out7),
    .p_reload24(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out6),
    .p_reload23(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out5),
    .p_reload22(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out4),
    .p_reload21(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out3),
    .p_reload20(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out2),
    .p_reload19(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out1),
    .p_reload(grp_compute_L3_Pipeline_STREAM_L3_fu_142_p_out),
    .max_idx_out(grp_compute_L3_Pipeline_FIND_MAX_fu_161_max_idx_out),
    .max_idx_out_ap_vld(grp_compute_L3_Pipeline_FIND_MAX_fu_161_max_idx_out_ap_vld)
);

bnn_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_compute_L3_Pipeline_FIND_MAX_fu_161_max_idx_out),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(out_r_TREADY_int_regslice),
    .data_out(out_r_TDATA),
    .vld_out(regslice_both_out_r_V_data_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_data_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(4'd15),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(regslice_both_out_r_V_keep_V_U_ack_in_dummy),
    .data_out(out_r_TKEEP),
    .vld_out(regslice_both_out_r_V_keep_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_keep_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(4'd15),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(regslice_both_out_r_V_strb_V_U_ack_in_dummy),
    .data_out(out_r_TSTRB),
    .vld_out(regslice_both_out_r_V_strb_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_strb_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_compute_L3_Pipeline_STREAM_L3_fu_142_is_last_sample_4_out),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(regslice_both_out_r_V_last_V_U_ack_in_dummy),
    .data_out(out_r_TLAST),
    .vld_out(regslice_both_out_r_V_last_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_last_V_U_apdone_blk)
);

bnn_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_r_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_compute_L3_Pipeline_STREAM_L3_fu_142_current_id_1_out),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(regslice_both_out_r_V_id_V_U_ack_in_dummy),
    .data_out(out_r_TID),
    .vld_out(regslice_both_out_r_V_id_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_id_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (regslice_both_out_r_V_data_V_U_apdone_blk == 1'b0) & (ap_phi_mux_is_last_sample_phi_fu_135_p4 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_start_reg <= 1'b1;
        end else if ((grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_ready == 1'b1)) begin
            grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (regslice_both_out_r_V_data_V_U_apdone_blk == 1'b0) & (ap_phi_mux_is_last_sample_phi_fu_135_p4 == 1'd0))) begin
            grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_ready == 1'b1)) begin
            grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        current_id_fu_54 <= 32'd0;
    end else if (((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        current_id_fu_54 <= grp_compute_L3_Pipeline_STREAM_L3_fu_142_current_id_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        is_last_sample_reg_131 <= grp_compute_L3_Pipeline_STREAM_L3_fu_142_is_last_sample_4_out;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        is_last_sample_reg_131 <= 1'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_r_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_r_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_r_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (regslice_both_out_r_V_data_V_U_apdone_blk == 1'b0) & (ap_phi_mux_is_last_sample_phi_fu_135_p4 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (regslice_both_out_r_V_data_V_U_apdone_blk == 1'b0) & (ap_phi_mux_is_last_sample_phi_fu_135_p4 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        out_r_TDATA_blk_n = out_r_TREADY_int_regslice;
    end else begin
        out_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        out_r_TVALID_int_regslice = 1'b1;
    end else begin
        out_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (regslice_both_out_r_V_data_V_U_apdone_blk == 1'b0) & (ap_phi_mux_is_last_sample_phi_fu_135_p4 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state2) & (regslice_both_out_r_V_data_V_U_apdone_blk == 1'b0) & (ap_phi_mux_is_last_sample_phi_fu_135_p4 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((out_r_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_phi_mux_is_last_sample_phi_fu_135_p4 = is_last_sample_reg_131;

assign grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_start = grp_compute_L3_Pipeline_FIND_MAX_fu_161_ap_start_reg;

assign grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_start = grp_compute_L3_Pipeline_STREAM_L3_fu_142_ap_start_reg;

assign l2_to_l3_read = grp_compute_L3_Pipeline_STREAM_L3_fu_142_l2_to_l3_read;

assign out_r_TVALID = regslice_both_out_r_V_data_V_U_vld_out;

endmodule //bnn_compute_L3
