# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_dft_1024/design_dft_1024.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024 || ORIG_REF_NAME==design_dft_1024} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_dft_0_0/design_dft_1024_dft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_dft_0_0 || ORIG_REF_NAME==design_dft_1024_dft_0_0} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_processing_system7_0_0/design_dft_1024_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_processing_system7_0_0 || ORIG_REF_NAME==design_dft_1024_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_axi_dma_0_0/design_dft_1024_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_axi_dma_0_0 || ORIG_REF_NAME==design_dft_1024_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_axi_dma_1_0/design_dft_1024_axi_dma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_axi_dma_1_0 || ORIG_REF_NAME==design_dft_1024_axi_dma_1_0} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_axi_smc_0/design_dft_1024_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_axi_smc_0 || ORIG_REF_NAME==design_dft_1024_axi_smc_0} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_rst_ps7_0_50M_0/design_dft_1024_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_dft_1024_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_xbar_0/design_dft_1024_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==design_dft_1024_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_0/design_dft_1024_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_axi_mem_intercon_0 || ORIG_REF_NAME==design_dft_1024_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_us_0/design_dft_1024_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==design_dft_1024_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_us_1/design_dft_1024_axi_mem_intercon_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_axi_mem_intercon_imp_auto_us_1 || ORIG_REF_NAME==design_dft_1024_axi_mem_intercon_imp_auto_us_1} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_us_2/design_dft_1024_axi_mem_intercon_imp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_axi_mem_intercon_imp_auto_us_2 || ORIG_REF_NAME==design_dft_1024_axi_mem_intercon_imp_auto_us_2} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_us_3/design_dft_1024_axi_mem_intercon_imp_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_axi_mem_intercon_imp_auto_us_3 || ORIG_REF_NAME==design_dft_1024_axi_mem_intercon_imp_auto_us_3} -quiet] -quiet

# IP: bd/design_dft_1024/ip/design_dft_1024_axi_mem_intercon_imp_auto_pc_0/design_dft_1024_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dft_1024_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==design_dft_1024_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# XDC: /home/linux/ieng6/students/162/mak025/chole_bhature/project_files/project3/Q9/dft_1024/dft_1024.gen/sources_1/bd/design_dft_1024/design_dft_1024_ooc.xdc
